### ISSUE TITLE
Failed to add pack to device java.lang.NoSuchMethodException: 

### ISSUE THREAD

**Issue by Bidibooum** [marian-m12l/studio#103]
When i want to transfert an new self created story on the lunii, I receive this message (only with the 0.1.16 version), it's work wit 0.1.15

2020-05-25 07:52:51,907 [ERROR] [s.w.s.StoryTellerService]: Failed to add pack to device
java.lang.NoSuchMethodException: com.lunii.device.wrapper.raw.RawVirtualContent.addPack(java.util.UUID,short,int)
    at java.base/java.lang.Class.getDeclaredMethod(Class.java:2553)
    at studio.webui.service.StoryTellerService$3.run(StoryTellerService.java:175)
    at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
    at java.base/java.util.TimerThread.run(Timer.java:506)
java.lang.NoSuchMethodException: com.lunii.device.wrapper.raw.RawVirtualContent.addPack(java.util.UUID,short,int)
    at java.base/java.lang.Class.getDeclaredMethod(Class.java:2553)
    at studio.webui.service.StoryTellerService$3.run(StoryTellerService.java:175)
    at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
    at java.base/java.util.TimerThread.run(Timer.java:506)

**Desktop and environment (please complete the following information):**
 - OS: [MAC OS]
 - Browser chrome]
 - STUdio application version [e.g. 0.1.16]

**Comment by marian-m12l** [comment]
Hi,

Did you upgrade the Luniistore and the Lunii libraries in `$DOT_STUDIO/lib`? This release requires the latest drivers that were published this week (that's actually the main purpose of the release).

Thanks for you feedback!

**Comment by Bidibooum** [comment]
Hello, yes I updated the luniistore.

How Can i update the lunii library?

Thanks

**Comment by Bidibooum** [comment]
Ok, work fine when I copy the new jar file with new drivers.

:-)
Thank you

**Comment by marian-m12l** [comment]
Great :-)
