### ISSUE TITLE
Impossible to transfer pack

### ISSUE THREAD

**Issue by jetwitaussi** [marian-m12l/studio#105]
**Describe the bug**
Error on transfer a pack

**To Reproduce**
Drag and drop a pack on the left sidebar (to lunii)

**Expected behavior**
Pack installed

**Logs**
No error in console, just a log: 
Received `storyteller.transfer.9dc838a0-5485-45dd-91f5-f8f2da530b30.done` event from vert.x event bus.
{success: false}

No error on network panel.

In file studio-latest.log:
2020-05-27 17:19:00,408 [WARN ] [studio.webui.service.LibraryService] [LibraryService.java:122]: Pack to transfer is in archive format. Converting to binary format and storing in temporary file: C:\Users\root\AppData\Local\Temp\surpriselunii-9641c92a-f808-43ac-ae7d-f96ef6165951-v1.zip688907949073745435.pack
2020-05-27 17:19:00,409 [WARN ] [studio.webui.service.LibraryService] [LibraryService.java:124]: Reading archive format pack
2020-05-27 17:19:00,677 [WARN ] [studio.webui.service.LibraryService] [LibraryService.java:133]: Uncompressing pack assets
2020-05-27 17:19:08,661 [WARN ] [studio.webui.service.LibraryService] [LibraryService.java:137]: Writing binary format pack
2020-05-27 17:19:11,710 [INFO ] [com.lunii.device.gateway.raw.AbstractUsb4JavaLuniiDriver] [AbstractUsb4JavaLuniiDriver.java:434]: Get handler handle for handler : Usb4JavaLuniiDevice{path=[2, 0, 0, 0, 0, 0, 2], busNumber=2, portNumber=1, deviceAddress=8, deviceHandle=libusb device handle 0x0, handler=libusb device 0x267081fe960}
2020-05-27 17:19:11,710 [INFO ] [com.lunii.device.gateway.raw.AbstractUsb4JavaLuniiDriver] [AbstractUsb4JavaLuniiDriver.java:475]: Claim interface for handler : Usb4JavaLuniiDevice{path=[2, 0, 0, 0, 0, 0, 2], busNumber=2, portNumber=1, deviceAddress=8, deviceHandle=libusb device handle 0x2672cb9bc80, handler=libusb device 0x267081fe960}
2020-05-27 17:19:11,772 [INFO ] [com.lunii.device.gateway.raw.AbstractUsb4JavaLuniiDriver] [AbstractUsb4JavaLuniiDriver.java:543]: Release interface for handler : Usb4JavaLuniiDevice{path=[2, 0, 0, 0, 0, 0, 2], busNumber=2, portNumber=1, deviceAddress=8, deviceHandle=libusb device handle 0x2672cb9bc80, handler=libusb device 0x267081fe960}
2020-05-27 17:19:11,772 [INFO ] [com.lunii.device.gateway.raw.AbstractUsb4JavaLuniiDriver] [AbstractUsb4JavaLuniiDriver.java:546]: Dispose handler : Usb4JavaLuniiDevice{path=[2, 0, 0, 0, 0, 0, 2], busNumber=2, portNumber=1, deviceAddress=8, deviceHandle=libusb device handle 0x2672cb9bc80, handler=libusb device 0x267081fe960}
2020-05-27 17:19:11,772 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:151]: Computing pack start sector...
2020-05-27 17:19:11,772 [ERROR] [studio.webui.service.StoryTellerService] [StoryTellerService.java:197]: Failed to add pack to device
java.lang.NoSuchMethodException: com.lunii.device.wrapper.raw.RawVirtualContent.addPack(java.util.UUID, short, int)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2476)
	at studio.webui.service.StoryTellerService$3.run(StoryTellerService.java:175)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
2020-05-27 17:20:33,323 [WARN ] [studio.webui.service.LibraryService] [LibraryService.java:122]: Pack to transfer is in archive format. Converting to binary format and storing in temporary file: C:\Users\root\AppData\Local\Temp\surpriselunii-9641c92a-f808-43ac-ae7d-f96ef6165951-v1.zip14983621324640434136.pack
2020-05-27 17:20:33,323 [WARN ] [studio.webui.service.LibraryService] [LibraryService.java:124]: Reading archive format pack
2020-05-27 17:20:33,464 [WARN ] [studio.webui.service.LibraryService] [LibraryService.java:133]: Uncompressing pack assets
2020-05-27 17:20:41,455 [WARN ] [studio.webui.service.LibraryService] [LibraryService.java:137]: Writing binary format pack
2020-05-27 17:20:44,700 [INFO ] [com.lunii.device.gateway.raw.AbstractUsb4JavaLuniiDriver] [AbstractUsb4JavaLuniiDriver.java:434]: Get handler handle for handler : Usb4JavaLuniiDevice{path=[2, 0, 0, 0, 0, 0, 2], busNumber=2, portNumber=1, deviceAddress=8, deviceHandle=libusb device handle 0x0, handler=libusb device 0x267081fe960}
2020-05-27 17:20:44,700 [INFO ] [com.lunii.device.gateway.raw.AbstractUsb4JavaLuniiDriver] [AbstractUsb4JavaLuniiDriver.java:475]: Claim interface for handler : Usb4JavaLuniiDevice{path=[2, 0, 0, 0, 0, 0, 2], busNumber=2, portNumber=1, deviceAddress=8, deviceHandle=libusb device handle 0x2672cb9bc80, handler=libusb device 0x267081fe960}
2020-05-27 17:20:44,758 [INFO ] [com.lunii.device.gateway.raw.AbstractUsb4JavaLuniiDriver] [AbstractUsb4JavaLuniiDriver.java:543]: Release interface for handler : Usb4JavaLuniiDevice{path=[2, 0, 0, 0, 0, 0, 2], busNumber=2, portNumber=1, deviceAddress=8, deviceHandle=libusb device handle 0x2672cb9bc80, handler=libusb device 0x267081fe960}
2020-05-27 17:20:44,758 [INFO ] [com.lunii.device.gateway.raw.AbstractUsb4JavaLuniiDriver] [AbstractUsb4JavaLuniiDriver.java:546]: Dispose handler : Usb4JavaLuniiDevice{path=[2, 0, 0, 0, 0, 0, 2], busNumber=2, portNumber=1, deviceAddress=8, deviceHandle=libusb device handle 0x2672cb9bc80, handler=libusb device 0x267081fe960}
2020-05-27 17:20:44,761 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:151]: Computing pack start sector...
2020-05-27 17:20:44,763 [ERROR] [studio.webui.service.StoryTellerService] [StoryTellerService.java:197]: Failed to add pack to device
java.lang.NoSuchMethodException: com.lunii.device.wrapper.raw.RawVirtualContent.addPack(java.util.UUID, short, int)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2476)
	at studio.webui.service.StoryTellerService$3.run(StoryTellerService.java:175)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.1.16
 - Luniistore uptodate

**Additional context**
I can't install a new pack I have done. I remove another pack already installed on lunii, and I can't add it again, same error.

**Comment by jetwitaussi** [comment]
Replacing 
lunii-java-util.jar
lunii-device-gateway.jar
lunii-device-wrapper.jar

fix the problem!
