### ISSUE TITLE
Can't download the created story in the Lunii

### ISSUE THREAD

**Issue by lagencerpNF** [marian-m12l/studio#108]
Hi,

And thanks a lot for creating STUdio. 

We've just created a new story and we have an error when downloading the story in the Lunii.
"Error when adding the pack to the lunii" if you might help? :)

Thanks a lot,

<img width="357" alt="Capture d’écran 2020-06-06 à 10 46 45" src="https://user-images.githubusercontent.com/49659818/83940218-32357380-a7e3-11ea-8403-32beb87c8046.png">

Best,

**Comment by grisgrisgc12** [comment]
I also have the same error.
The java error is : java.lang.NoSuchMethodException (see below)

2020-06-11 23:39:55,450 [ERROR] [s.w.s.StoryTellerService]: Failed to add pack to device
java.lang.NoSuchMethodException: com.lunii.device.wrapper.raw.RawVirtualContent.addPack(java.util.UUID, short, int)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
	at studio.webui.service.StoryTellerService$3.run(StoryTellerService.java:175)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
java.lang.NoSuchMethodException: com.lunii.device.wrapper.raw.RawVirtualContent.addPack(java.util.UUID, short, int)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
	at studio.webui.service.StoryTellerService$3.run(StoryTellerService.java:175)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
2020-06-11 23:40:50,531 [INFO ] [c.l.d.g.r.AbstractUsb4JavaLuniiDriver]: Exiting libusb

**Comment by marian-m12l** [comment]
@lagencerpNF Thanks for the feedback. In order to help you, I'd need more info from the console and browser logs.

@grisgrisgc12 Looks like your lunii libraries are not up to date. You can also use the beta version which does not rely on proprietary libraries.

**Comment by grisgrisgc12** [comment]
I have updated the lunii libraries and the problem is now solved. Thanks
