### ISSUE TITLE
problem lunii

### ISSUE THREAD

**Issue by pichonwl** [marian-m12l/studio#115]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> Internal Server Error: Error 500: Internal Server Error	at studio.webui.service.StoryTellerService.deviceInfos(StoryTellerService.java:98)
	at studio.webui.api.DeviceController.lambda$apiRouter$2(DeviceController.java:36)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.1.17

**Additional context**

**Comment by marian-m12l** [comment]
Hi. Thanks for the feedback.
Looks like a problem happens while getting the device informations. What steps are you doing in the application? Did you try the beta version, which uses a different driver?

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
