### ISSUE TITLE
Fails to load story pack

### ISSUE THREAD

**Issue by kpouget** [marian-m12l/studio#123]
**Describe the bug**
Cannot load the story with only message: "*Fails to load story pack*" in the app notifications

**To Reproduce**
Not yet possible

**Expected behavior**
Load the story pack or explain what's going wrong

**Screenshots**
N/A

**Logs**
May or may not be related to this stack trace (the trace happens during the 1st access to the app, not when clicking on the story to load it):

```
2020-07-03 08:42:46,234 [INFO ] [s.w.MainVerticle]: Opening URL in default browser...
2020-07-03 08:42:46,325 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle
2020-07-03 08:42:47,526 [ERROR] [s.w.MainVerticle]: Exception thrown
java.nio.channels.ClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.write(WebSocketServerExtensionHandler.java:151)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:124)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:205)
	at io.vertx.core.http.impl.Http1xServerConnection.writeToChannel(Http1xServerConnection.java:267)
	at io.vertx.core.net.impl.ConnectionBase.sendFileRegion(ConnectionBase.java:417)
	at io.vertx.core.net.impl.ConnectionBase.sendFile(ConnectionBase.java:444)
	at io.vertx.core.http.impl.Http1xServerConnection.sendFile(Http1xServerConnection.java:456)
	at io.vertx.core.http.impl.HttpServerResponseImpl.doSendFile(HttpServerResponseImpl.java:514)
	at io.vertx.core.http.impl.HttpServerResponseImpl.sendFile(HttpServerResponseImpl.java:433)
	at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:365)
	at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:351)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendFile$11(StaticHandlerImpl.java:457)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.wrapInTCCLSwitch(StaticHandlerImpl.java:266)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.sendFile(StaticHandlerImpl.java:392)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$null$0(StaticHandlerImpl.java:231)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.getFileProps(StaticHandlerImpl.java:299)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:208)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Desktop and environment (please complete the following information):**
 - OS: Linux x86_64
 - Browser Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.1.17

**Additional context**

* Failing story is there:
> https://tools.972.ovh/story.json
* I was working on a story for multiple days (with full shutdown of the app in between), yesterday I added a few stories/assets and after launching Luniistudio to upload it, I could not access the story anymore

**Comment by marian-m12l** [comment]
Hi,

Thanks for the feedback.

The stacktrace does not seem related. Did you look for errors in the browser (both console and network tabs) as that's probably where you'd get the most insight.

**Comment by kpouget** [comment]
oh indeed, I forgot to have a look at this side, which is more interesting:
```
failed to load story pack TypeError: "A.homeTransition is null"
    de reader.js:284
    de reader.js:268
```
pointing to this `if` line:
```
 if (storyVirtualStage.homeTransition.actionNode !== firstUsefulNodeUuid) {
    // Enable custom Home transition to create Home port
    storyNode.setCustomHomeTransition(true);
    // Create link
    links.push(storyNode.homePort.link(getTransitionTargetNode(storyVirtualStage.homeTransition, actionNodes, simplifiedNodes)));
}
```
and with this test above:
```
if (group[0].type.startsWith('story')) { ... }
```

I can understand that the invalid block is this one:
```
    {
      "uuid": "e4f86abf-ae36-47f8-a48d-363b8cf33f5b",
      "type": "story",
      "name": "Le voyage de Tichou",
      "position": null,
      "image": null,
      "audio": "bb8a8191a9532c0117a2780e09f1000d5928c9e7.mp3",
      "okTransition": {
        "actionNode": "4d20f7b7-ae32-4241-a5dd-111111111111",
        "optionIndex": 0
      },
      "homeTransition": null,
      // ...
    },
```
so I copied the value of `okTransition` to `homeTransition` as it often have the same value.

... but I still cannot reload the story pack after that :(

```
zip ../library/my_story.zip  story.json assets
```
Is this the right way to generate the story, or did I miss something?

```
failed to load story pack TypeError: "e.file(...) is null"
    c reader.js:113
    l reader.js:111
    de reader.js:79
```

from there:
```
if (menuQuestionVirtualStage.audio) {
    archive.file('assets/' + menuQuestionVirtualStage.audio).async('base64').then(base64Asset => {
        resolve(dataUrlPrefix(menuQuestionVirtualStage.audio) + base64Asset);
    });
}
```
thanks for your help

**Comment by marian-m12l** [comment]
Thanks for the detailed info :+1: 

This should be fixed on `master`. Can you try with the latest [nightly build](https://github.com/marian-m12l/studio/actions?query=workflow%3A%22Nightly+Build%22)?

This was probably introduced by the fix for #100, the loader did not check if home transition is disabled, which was OK before the fix because home transition was never null.

**Comment by marian-m12l** [comment]
Also, regarding your fixed pack, it looks like the loader fails to read an asset. Make sure the content is the same as your original story pack archive. I seldom use CLI to handle archives, though, so I would not be of any help...

**Comment by kpouget** [comment]
for fixing my pack, shame on me, the `zip` command is:

`zip ../library/my_story.zip  story.json assets/*`

otherwise the zip contained ... an empty `assets` directory!

so my pack is fixed, thanks for the hints. For the bug itself, I don't know how I created the invalid `json` so I can't be sure it's fixed :# the only think I know is that I clicked on the "Customize Home" and "Disable Home" buttons randomly and then tried to revert to a normal!

and thanks a lot for the tool you designed and shared open source, it's really neat and intuitive, and adds a lot of value to the Lunii :)

**Comment by marian-m12l** [comment]
Actually, the bug was in the loader, your story pack was OK. A `null` home transition is expected in the json when you disable the home button on a story node.

**Comment by kpouget** [comment]
Hello @marian-m12l , I'm failing to load my story book because of this error again, using the latest master (ffe910d6af871245d37aca34ce78edeaa1178d99),

```
failed to load story pack TypeError: A.homeTransition is null
    de reader.js:284
    de reader.js:268
```

the error is there, I guess a check that `node.homeTransition` isn't empty could help:
https://github.com/marian-m12l/studio/blob/ffe910d6af871245d37aca34ce78edeaa1178d99/web-ui/javascript/src/utils/reader.js#L285

thanks,

Kevin

**Comment by kpouget** [comment]
(hum, `284 != 285`, maybe I'm not actually running master ...)

**Comment by kpouget** [comment]
hum, nevermind, the problem is actually solved with master, I wonder why I fell into this bug again many months after it was solved!
