### ISSUE TITLE
Java error when loading pack

### ISSUE THREAD

**Issue by pilou1982** [marian-m12l/studio#124]
**Describe the bug**
Impossible to load some pack, because of java error

**To Reproduce**
Drag and drop my pack

**Expected behavior**
Windows to charge pack appear and nothing else. Windows promp show:

Exception in thread "Timer-3" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3536)
        at java.base/java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:185)
        at studio.core.v1.utils.AudioConversion.anyToWave(AudioConversion.java:65)
        at studio.core.v1.utils.AudioConversion.mp3ToWave(AudioConversion.java:27)
        at studio.core.v1.utils.PackAssetsCompression.withUncompressedAssets(PackAssetsCompression.java:116)
        at studio.webui.service.LibraryService.getBinaryPackFile(LibraryService.java:134)
        at studio.webui.api.DeviceController$1.run(DeviceController.java:79)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)

**Logs**

Exception in thread "Timer-3" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3536)
        at java.base/java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:18
![bug3](https://user-images.githubusercontent.com/67839733/86519953-c6f4b680-be0d-11ea-8b16-0bc631f10f24.jpg)
5)
        at studio.core.v1.utils.AudioConversion.anyToWave(AudioConversion.java:65)
        at studio.core.v1.utils.AudioConversion.mp3ToWave(AudioConversion.java:27)
        at studio.core.v1.utils.PackAssetsCompression.withUncompressedAssets(PackAssetsCompression.java:116)
        at studio.webui.service.LibraryService.getBinaryPackFile(LibraryService.java:134)
        at studio.webui.api.DeviceController$1.run(DeviceController.java:79)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)

![bug3](https://user-images.githubusercontent.com/67839733/86519963-d411a580-be0d-11ea-8e7c-4d313c63dfd9.jpg)

**Desktop and environment
 - OS: Win 10
Chrome/70.0.3538.102
 - Java version: [e.g. JDK 14.0.1 64 bit]
 - STUdio application version: 0.2.0-beta.2

**Comment by marian-m12l** [comment]
Hi,

Thanks for your feedback. Looks like you're overflowing the heap space. How big is your story pack?

There's room for improvement regarding memory management, but in the meantime you should be able to circumvent the issue by increasing your maximum heap size (lookup the `-Xmx` jvm option).

**Comment by pilou1982** [comment]
Thank

Using -Xmx2200M in the batch works for a couple of pack (from 20 to 44mb). I am surprised I didn't it find anybody else with this issue on forum on net. But the bigger one is 168Mb (20 mp3 of 8mb, 12minutes in average). I get the following issue. Size used of my lunii is just 51%.


2020-07-04 23:27:17,852 [WARN ] [s.w.s.LibraryService]: Reading archive format p
ack
2020-07-04 23:27:19,820 [WARN ] [s.w.s.LibraryService]: Uncompressing pack asset
s
2020-07-04 23:30:03,243 [WARN ] [s.w.s.LibraryService]: Writing binary format pa
ck
2020-07-04 23:31:07,477 [INFO ] [s.w.s.StoryTellerService]: Transferring pack to
device: 925466624 bytes
2020-07-04 23:31:07,493 [INFO ] [s.w.s.StoryTellerService]: Transferring pack to
device: 1807552 sectors
2020-07-04 23:31:11,922 [ERROR] [s.d.LibUsbHelper]: Read operation failed while
writing to SD
2020-07-04 23:31:12,141 [ERROR] [s.w.s.StoryTellerService]: Failed to add pack t
o device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Re
ad operation failed while writing to SD
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Comp
letableFuture.java:314<http://letableFuture.java:314>)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Co
mpletableFuture.java:319<http://mpletableFuture.java:319>)
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Com
pletableFuture.java:645<http://pletableFuture.java:645>)
at java.base/java.util.concurrent.CompletableFuture.postComplete(Complet
ableFuture.java:506<http://ableFuture.java:506>)
at java.base/java.util.concurrent.CompletableFuture.complete(Completable
Future.java:2137<http://Future.java:2137>)
at studio.driver.LibUsbHelper.lambda$asyncTransferIn$17(LibUsbHelper.jav
a:446)
at org.usb4java.LibUsb.handleEventsTimeout(Native Method)
at  studio.driver.LibUsbAsyncEventsWorker.run<http://studio.driver.LibUsbAsyncEventsWorker.run>(LibUsbAsyncEventsWorker.jav
a:34)
Caused by: studio.driver.StoryTellerException: Read operation failed while writi
ng to SD
at studio.driver.LibUsbHelper.lambda$asyncWriteSDSectors$13(LibUsbHelper
.java:392)
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Com
pletableFuture.java:642<http://pletableFuture.java:642>)
... 5 more



Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by marian-m12l** [comment]
Thanks for confirming the workaround.

**Comment by pilou1982** [comment]
Yes using -Xms1024M -Xmx8800M allow me to load all my pack. So probably when using computer with few memory it is better to add these 2 options.
