### ISSUE TITLE
Java wont start.

### ISSUE THREAD

**Issue by kouki31** [marian-m12l/studio#127]
I start in terminal studio-windows.bat
and i have this message.

2020-07-23 10:56:08,455 [ERROR] [io.vertx.core.impl.launcher.commands.RunCommand] [ClasspathHandler.java:170]: Failed to deploy verticle studio.webui.MainVerticle
java.lang.UnsupportedClassVersionError: studio/webui/MainVerticle has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:37)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:243)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:216)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:105)
	at io.vertx.core.impl.FutureImpl.onComplete(FutureImpl.java:83)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:183)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:156)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:145)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:683)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:168)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:403)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:383)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
	at io.vertx.core.Launcher.main(Launcher.java:45)

I have instal java 11. 14.
i have trie tu select only 11 or 14 and same.
Can you help me ?
thanks
*Screenshots**

![2020-07-23 11_08_27-Paramètres de Java Runtime Environment](https://user-images.githubusercontent.com/49492635/88269731-da8c9200-ccd4-11ea-8382-3381eeea1adf.jpg)

**Desktop and environment (please complete the following information):**
 - OS: window 10 pro
 - Browser chrome and firefox
 - Java version: 11 14 1.8
 - Maven version: [e.g. 3.6.0] ???
 - STUdio application version 0.1.17 and 0.2.0

**Comment by kouki31** [comment]
hello i have found.
SET PATH=C:\Program Files\Java\jdk-14.0.2\bin
its work.
