### ISSUE TITLE
Echec de la verification de l'appareil

### ISSUE THREAD

**Issue by Grumby** [marian-m12l/studio#130]
Lors du branchement de la lunii box sur le port usb, un message apparaît : echec de la verification de l'appareil
Le fichier latestlog indique :

2020-08-04 20:23:43,938 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Unable to claim libusb interface
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: studio.driver.StoryTellerException: Unable to claim libusb interface
	at studio.driver.LibUsbHelper.lambda$executeOnDeviceHandle$4(LibUsbHelper.java:311)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	... 6 more
Caused by: org.usb4java.LibUsbException: USB error 99: Other error
	... 8 more

Quelle est la cause ? Quel est le remede ?
Je n'ai pas ce probleme avec mon pc sous linux, mais uniquement avec un mac pour lequel je suis oblige d'utiliser un adaptateur USB C.
Merci pour votre aide.

**Comment by paul4690** [comment]
Bonjour à tous.

Même problème que moi sur mac. Une idée ? Une solution ?
De mon côté réinstal, reboot et co ... rien n'y fait.

Merci par avance.

**Comment by Grumby** [comment]
Le problème semble être un problème de version de l'ios ; la dernière version de STUdio n'a pas marché sous HighSierra ; mais lorsque je l'ai testée sur un mac avec Catalina, ça a marché.
Quel est la version de votre ios ?
Peut-être qu'une ancienne version de STUdio marcherait sur votre mac.

**Comment by marian-m12l** [comment]
Bonjour, et merci pour le retour. Cette erreur est levée par la librairie USB bas niveau. Il semble qu'il y ait un bug connu sur macOS 10.14 avec usb4java 1.3.0.

https://github.com/usb4java/usb4java/issues/68

https://github.com/libusb/libusb/issues/519

Si vous compilez vous-même STUdio, vous pouvez peut-être tester en passant à la version 1.2.0.

**Comment by Grumby** [comment]
Merci pour les informations. Je ferme ce sujet.
