### ISSUE TITLE
fail to get .json from token

### ISSUE THREAD

**Issue by yalip31** [marian-m12l/studio#133]
**Describe the bug**
the command to get token gives this result:
{"code":"1.1"}

I used curl command as advised with MYTOKEN extracted from luniitheque properties file: 
curl -o ~/.studio/db/official.json -v -X GET -H 'Accept: application/json' -H 'Content-Type: application/json; charset=UTF-8' -H 'X-AUTH-TOKEN: MYTOKEN' https://server-data-prod.lunii.com/v2/packs

I think this json is not good because when I launch linux.sh script, I have this log I don't understand:
2020-09-16 22:45:20,531 [ERROR] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:77]: Failed in deploying verticle
java.lang.ClassCastException: class com.google.gson.JsonPrimitive cannot be cast to class com.google.gson.JsonObject (com.google.gson.JsonPrimitive and com.google.gson.JsonObject are in unnamed module of loader 'app')
	at com.google.gson.JsonObject.getAsJsonObject(JsonObject.java:205)
	at studio.metadata.DatabaseMetadataService.lambda$new$0(DatabaseMetadataService.java:41)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:40)
	at studio.webui.MainVerticle.start(MainVerticle.java:47)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

I'm using ubuntu 20.04 and JDK 11.0.8
.
Can you identify what is wrong? maybe I am not collecting good token?
Regards

**Comment by marian-m12l** [comment]
Hi. The JSON should contain metadata for all story packs. Which token are you using? You can make sure it is still valid by pasting it on the debugger: https://jwt.io/

**Comment by evil512-dom** [comment]
Hi, I have exactly the same issue while doing a curl in windows none of my try to debug the token work...

**Comment by marian-m12l** [comment]
It's possible that the endpoint changed. Which token are you using? Is it still valid?

**Comment by dabbede** [comment]
Same issue on windows (but curl executed in linux, so I think it does not depend on OS).
Here I attach my [.local.properties](https://github.com/marian-m12l/studio/files/5721604/local.properties.txt) file, to show which fields it contains (tokens and user data removed from file).

**Comment by agademer** [comment]
I had the same problem. Resolved by changing the single quote (') around the X-AUTH-TOKEN: by quotes (")
`curl -o ~/.studio/db/official.json -v -X GET -H 'Accept: application/json' -H 'Content-Type: application/json; charset=UTF-8' -H "X-AUTH-TOKEN: value_of_your_jwt_token" https://server-data-prod.lunii.com/v2/packs`
Really don't know why, but worked for me.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
