### ISSUE TITLE
com.google.gson.JsonPrimitive cannot be cast to class com.google.gson.JsonObject

### ISSUE THREAD

**Issue by diegantobass** [marian-m12l/studio#140]
I'm trying to launch studio-linux.sh on kubuntu 20.10 and it fails to deploy the verticle.

**Steps to reproduce the behavior:**
1. unpack the distribution .tar.gz
2. chmod 777 the whole folder
3. sh studio-linux.sh
4. the java.lang.ClassCastException copied in the log section appears 3 times in my console.

**Expected behavior**
I expected my default browser to open to localhost:8080

**Logs**
2020-11-04 14:54:15,199 [ERROR] [i.v.c.i.l.c.VertxIsolatedDeployer]: Failed in deploying verticle
java.lang.ClassCastException: class com.google.gson.JsonPrimitive cannot be cast to class com.google.gson.JsonObject (com.google.gson.JsonPrimitive and com.google.gson.JsonObject are in unnamed module of loader 'app')
        at com.google.gson.JsonObject.getAsJsonObject(JsonObject.java:205)
        at studio.metadata.DatabaseMetadataService.lambda$new$0(DatabaseMetadataService.java:41)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:40)
        at studio.webui.MainVerticle.start(MainVerticle.java:47)
        at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
        at io.vertx.core.Verticle.start(Verticle.java:66)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Desktop and environment (please complete the following information):**
 - OS: Kubuntu 20.10 (Ubuntu 20.10 + Plasma 5.19)
 - Browser : Firefox 82.0
 - Java version: 
openjdk 11.0.9 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-Ubuntu-0ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.9+11-Ubuntu-0ubuntu1, mixed mode, sharing)
 - Maven version: 3.6.3
 - STUdio application version 0.2.0

**Additional context**
It works if I sudo it, but then STUdio can't read what is on my lunii and I can't add anything to it.

**Comment by marian-m12l** [comment]
Hi. Thanks for your feedback.
Looks like your metadata database (`official.json`) is corrupted (the app reads a primitive when an object is expected).

**Comment by diegantobass** [comment]
Thank you very much. The `official.json` was indeed the problem. Having replaced the file with a valid one allows me to launch the application.

Now, I have a recurring "failed to refresh library" error in the interface, which is another matter for another issue, I guess.

**Comment by Dedcap** [comment]
Hello,

Sorry to write on this closed topics but I have the same issue and I can't find another way to retrieve the json file
I'm using this command line:
curl -o C:/Users/Ded/.studio/db/official.json -v -X GET -H 'Accept:application/json' -H 'Content-Type:application/json;charset=UTF-8' -H 'X-AUTH-TOKEN:eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1aWQiOiJHdWVzdCIsInJvbGUiOiJHVUVTVCJ9.hsXcZmt7jKFQWYzOkFuzCraiXKdRJlVfHUGGRuHAFTXLraDGCar4HI9LR6rAHLQEd8h1r_4ydghbEVyPx5UnpjlCS9PcO6jOw1GRDg4Lsfp7_sF196xV3ITn9zAITUvZuCk8wxXIjFCt9f5KOXuBevxsXc20-E82XNArgjZ2ALA5wVGEoWOJliaEOCR2JELLNw_AUKer1De-7M3Co7S-q0zeVm3VuR8f6_FetJAl5mJ5U_I8qfT_9yMq-dyVACuguR1BAIeQrkyJTko5K_vR2L_0KUr9DxmQGeKo4EWfc_D8snqdeKjhaDdvlOr5uDo_E_XbJYTptAyRCAoUJm5Ggg' https://server-data-prod.lunii.com/v2/packs

Can you tell me where my mistake is?

Thanks
Andre

**Comment by marian-m12l** [comment]
@Dedcap You can try the [latest beta release](https://github.com/marian-m12l/studio/releases/tag/0.3.0-beta.3) which can fetch the "official metadata" automatically.

**Comment by Dedcap** [comment]
Hello,

I'm very sorry for the late answer

I use the latest version today and it works like a charm

Thank you so much for the work!

Andre

Le dim. 25 avr. 2021 à 00:04, marian-m12l ***@***.***> a
écrit :
