### ISSUE TITLE
mise a jour bibliotheque impossible

### ISSUE THREAD

**Issue by cehanne** [marian-m12l/studio#141]
bonjour
j'ai importer 3 packs de nouvelles histoires.
le 1er s'est bien déroulé et la bibliotheque s'est bien mise  a jour.
la seconde s'est televersée mais messaghe qui dit mise a jour de la bibliotheque impossible.
j'ai relancé le STudio et mise a jour de la bibliotheque impossible
j'ai relancé windows et mise a jour de la bibliotheque impossible
voilà
merci d'avance

**Comment by marian-m12l** [comment]
Bonjour,

Merci pour le retour. Mais je ne suis pas sûr d'avoir bien compris la manipulation qui pose problème. C'est le transfert de la Lunii vers le PC qui ne fonctionne pas ? Pour pouvoir diagnostiquer le problème, le mieux est de partir du message d'erreur exact, et éventuellement des logs de l'application.

**Comment by diegantobass** [comment]
Désolé de m'imiscer. J'obtiens le même comportement : au lancement de l'application, sans aucune manipulation, le message d'erreur "échec du rafraichissement de la bibliothèque" apparaît.

Voici ma stacktrace (message d'erreur).

2020-11-05 22:28:32,494 [ERROR] [s.w.MainVerticle]: Exception thrown
java.lang.IllegalArgumentException: malformed input off : 58, length : 1
        at java.base/java.lang.StringCoding.throwMalformed(StringCoding.java:685)
        at java.base/java.lang.StringCoding.decodeUTF8_0(StringCoding.java:872)
        at java.base/java.lang.StringCoding.newStringUTF8NoRepl(StringCoding.java:965)
        at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2205)
        at java.base/java.util.zip.ZipCoder$UTF8.toString(ZipCoder.java:60)
        at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:87)
        at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:301)
        at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:123)
        at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
        at studio.webui.service.LibraryService.readPackFile(LibraryService.java:244)
        at studio.webui.service.LibraryService.lambda$packs$4(LibraryService.java:77)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at studio.webui.service.LibraryService.packs(LibraryService.java:77)
        at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:39)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        ... 32 more

Signé : le mec qui détourne les issues sans honte.

**Comment by cehanne** [comment]
Ok. Je reviens demain avec log et message d'erreur exact.
J'ai essayé toute la journée sur chrome, mozilla, avec la version bêta...
J'avais 22 packs dans la bibliothèque,  je me suis dit que peut être c'était trop et que ca faisait bugguer . J'en laissé qu'un et ça a fonctionné mais lorsque j'en ai remis 4 rebelotte erreur téléchargement bibliothèque. 
En tous les cas bravo pour le boulot et l'interface de l'éditeur qui est d'une facilité d'utilisation incroyable.
Je comprends pas pourquoi lunii ne le fait pas car ça ne nous empêche pas d'acheter des packs officiels mais ça ouvre des possibilités de personnalisation de ouf! Mes gosses rigolent quand ils entendent ma voix sur leur boite !:-)

**Comment by marian-m12l** [comment]
@diegantobass @cehanne Le dossier `.studio/library` doit contenir un pack d'histoires corrompu. Videz le dossier, puis essayez d'ajouter les packs un par un jusqu'à ce que l'erreur apparaisse pour identifier le fichier problématique.

**Comment by diegantobass** [comment]
C'était ça pour moi. Merci. Je continue ma chasse au bug... Et j'en profite pour te tirer mon chapeau @marian-m12l, beau boulot.

**Comment by ocedric** [comment]
Idem, cela a réglé mon soucis !
Merci

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
