### ISSUE TITLE
copy error

### ISSUE THREAD

**Issue by detafi** [marian-m12l/studio#143]
**Describe the bug**
when trying to copy a story to my local libray it fail with an error
It start failing when i try to delete a story of the luuni during a copy of another story to my local library

**To Reproduce**
1. Go to 'the library with a luuni 1.2 connected'
2. Click on a luuni story and put it to the local library : it start transfert
3. Scroll down to another story of the lunii and try to delete it

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

>  Device plugged
2020-11-21 13:50:20,048 [INFO ] [s.w.s.StoryTellerService]: Pack extracted.
2020-11-21 13:51:15,004 [INFO ] [s.w.s.StoryTellerService]: Pack extracted.
2020-11-21 13:51:50,637 [ERROR] [s.d.LibUsbHelper]: TRANSFER IN NOT COMPLETED: 4
2020-11-21 13:51:50,642 [ERROR] [s.w.a.DeviceController]: Failed to remove pack from device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Transfer IN failed
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1137)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152)
        at studio.driver.LibUsbHelper.lambda$asyncTransferIn$17(LibUsbHelper.java:442)
        at org.usb4java.LibUsb.handleEventsTimeout(Native Method)
        at studio.driver.LibUsbAsyncEventsWorker.run(LibUsbAsyncEventsWorker.java:34)
Caused by: studio.driver.StoryTellerException: Transfer IN failed
        ... 3 more
2020-11-21 13:51:50,643 [ERROR] [s.w.MainVerticle]: Exception thrown
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Transfer IN failed
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1137)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152)
        at studio.driver.LibUsbHelper.lambda$asyncTransferIn$17(LibUsbHelper.java:442)
        at org.usb4java.LibUsb.handleEventsTimeout(Native Method)
        at studio.driver.LibUsbAsyncEventsWorker.run(LibUsbAsyncEventsWorker.java:34)
Caused by: studio.driver.StoryTellerException: Transfer IN failed
        ... 3 more
2020-11-21 13:52:00,650 [ERROR] [s.d.LibUsbHelper]: TRANSFER IN NOT COMPLETED: 2
2020-11-21 13:52:00,651 [ERROR] [s.w.s.StoryTellerService]: Failed to extract pack from device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Transfer IN failed
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152)
        at studio.driver.LibUsbHelper.lambda$asyncTransferIn$17(LibUsbHelper.java:442)
        at org.usb4java.LibUsb.handleEventsTimeout(Native Method)
        at studio.driver.LibUsbAsyncEventsWorker.run(LibUsbAsyncEventsWorker.java:34)
Caused by: studio.driver.StoryTellerException: Transfer IN failed
        ... 3 more
2020-11-21 13:52:06,556 [ERROR] [s.w.s.StoryTellerService]: Cannot extract pack from device because the destination file already exists
2020-11-21 13:52:06,557 [ERROR] [s.w.a.DeviceController]: Failed to transfer pack from device
2020-11-21 13:52:06,557 [ERROR] [s.w.MainVerticle]: Exception thrown
2020-11-21 13:52:13,292 [ERROR] [s.d.LibUsbHelper]: TRANSFER OUT NOT COMPLETED: 4
2020-11-21 13:52:13,293 [ERROR] [s.w.s.StoryTellerService]: Failed to extract pack from device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Transfer OUT failed
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1137)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152)
        at studio.driver.LibUsbHelper.lambda$asyncTransferOut$16(LibUsbHelper.java:412)
        at org.usb4java.LibUsb.handleEventsTimeout(Native Method)
        at studio.driver.LibUsbAsyncEventsWorker.run(LibUsbAsyncEventsWorker.java:34)
Caused by: studio.driver.StoryTellerException: Transfer OUT failed
        ... 3 more

**Desktop and environment (please complete the following information):**
 - OS: Win64
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0
 - Java version: =
java 15 2020-09-15
Java(TM) SE Runtime Environment (build 15+36-1562)
Java HotSpot(TM) 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)

 - Maven version: not installed

 - STUdio application version: 0.2.0

**Additional context**
i'm a java coder : i can maybe help

**Comment by marian-m12l** [comment]
@detafi Indeed, that behaviour is expected, as the device cannot handle both commands simultaneously. Although it would be better if the UI prevented this in the first place.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
