### ISSUE TITLE
Failed to check device -- firmware 2

### ISSUE THREAD

**Issue by severin-lemaignan** [marian-m12l/studio#150]
**Describe the bug**

While testing branch `feature/firmware2dot4`, the STUdio fails to connect to the device (`/.md` not found). Most likely linked to #122

**To Reproduce**
1. checkout `feature/firmware2dot4` commit 1ca6aabeb4be
2. `mvn clean install` and launch `studio-linux.sh`
3. Connect and turn on device
4. Error on the console

**Expected behavior**

Successfully connect to the device

**Logs**

```
2021-01-02 19:14:43,609 [INFO ] [s.w.s.StoryTellerService]: Setting up story teller driver
2021-01-02 19:14:43,613 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2021-01-02 19:14:43,623 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is supported. Registering hotplug callback(s)...
2021-01-02 19:14:43,631 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2021-01-02 19:14:43,634 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is supported. Registering hotplug callback(s)...
2021-01-02 19:14:43,635 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug event callback (0483:a341): 1
2021-01-02 19:14:43,639 [INFO ] [s.w.s.StoryTellerService]: Device 2.x plugged
2021-01-02 19:14:43,639 [INFO ] [s.w.s.StoryTellerService]: Device 2.x plugged
2021-01-02 19:14:43,661 [ERROR] [s.w.s.StoryTellerService]: Failed to plug device 2.x
studio.driver.StoryTellerException: Failed to read device metadata on partition
	at studio.driver.fs.FsStoryTellerAsyncDriver.getDeviceInfos(FsStoryTellerAsyncDriver.java:142)
	at studio.webui.service.StoryTellerService$2.lambda$onDevicePlugged$1(StoryTellerService.java:115)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.io.FileNotFoundException: /.md (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at studio.driver.fs.FsStoryTellerAsyncDriver.getDeviceInfos(FsStoryTellerAsyncDriver.java:97)
	... 8 more
2021-01-02 19:14:43,665 [ERROR] [s.w.s.StoryTellerService]: Failed to plug device 2.x
studio.driver.StoryTellerException: Failed to read device metadata on partition
	at studio.driver.fs.FsStoryTellerAsyncDriver.getDeviceInfos(FsStoryTellerAsyncDriver.java:142)
	at studio.webui.service.StoryTellerService$2.lambda$onDevicePlugged$1(StoryTellerService.java:115)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.io.FileNotFoundException: /.md (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at studio.driver.fs.FsStoryTellerAsyncDriver.getDeviceInfos(FsStoryTellerAsyncDriver.java:97)
	... 8 more
```
**Desktop and environment (please complete the following information):**
 - OS: Linux x86_64
 - Browser Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
 - Java version: JDK 11.0.9.1
 - Maven version: e.g. 3.6.3
 - STUdio application version: 0.2.1-SNAPSHOT

**Additional context**

Lunii firmware from Luniistore console:
```
[INFO ] 2021-01-02 19:13:21,864 PluggedInitTask.onDeviceLoaded() - Device loaded : Device{state=LOADED, firmwareVersion=FirmwareVersion{firmwareUpdateMajor=-1, firmwareUpdateMinor=-1, major=2, minor=20}, vendorId=0x0483, productId=0xa341, sdCardSize=4022304768, usableSDCardSize=4022304768, uuid='vD8GcZxM74l9fDDPLm9InqJdIND3K2NiebPx+6LoOd/i9qAPbZrp3INpzFOfecguEEOnnLTWbnSCB80GuKDVVAivP41c5Nws7RSs5orCjUgrj2kaqFaofW5Llm+7bAIxhdRLOuuIVuFt7i2qPj5qYdqIjg8UIPCWlxH8IgtTystoKyR2n7JMrMpt1vEStwSM71KMSkLaIWPziD6qZOHUoIooMK/GS/kGOw2yW1IDJ2XN2tG9QaiwQVYlGB8yCT/pfqXecF3yA+1yZwPaz3MSDNLYAMIMghl7b13VU6R2eBJ0iNKl03kbimyFkRGVvRfLjq3XhGoRUSYyWp5UWBCr6Q==', serialNumber='0020120101700470', flagError=false, virtualContent=VirtualContent{packs=[VirtualPack{status=com.lunii.java.util.properties.ReadOnlyPropertyWrapper@378b0fb7, uuid=c4139d59-872a-4d15-8cf1-76d34cdf38c6, version=2, size=126629251}, VirtualPack{status=com.lunii.java.util.properties.ReadOnlyPropertyWrapper@8e043d4, uuid=e07c3196-e26a-41dc-93e6-a6b45cf5cfbb, version=1, size=87638729}, VirtualPack{status=com.lunii.java.util.properties.ReadOnlyPropertyWrapper@34ac3531, uuid=588130df-61c6-46ee-af95-017d9823734f, version=1, size=78071716}, VirtualPack{status=com.lunii.java.util.properties.ReadOnlyPropertyWrapper@5ec4345b, uuid=3b390c92-fe33-410f-b002-ebcc502b4f79, version=1, size=70204213}, VirtualPack{status=com.lunii.java.util.properties.ReadOnlyPropertyWrapper@315d7e83, uuid=a1e81d83-7482-48c0-8544-855ffc085d86, version=1, size=32172235}], sdCardSize=4022304768, usableSDCardSize=4022304768, fragmentation=null}}
```

**Comment by Aptustech** [comment]
You have to specify the mount point in the launch script I think.

**Comment by severin-lemaignan** [comment]
Indeed! Thanks. CLosing the issue.

**Comment by campafap** [comment]
I have the same problem, how can I specify the mount point ?
