### ISSUE TITLE
Creation de 

### ISSUE THREAD

**Issue by TeensyDucM** [marian-m12l/studio#156]
Bonjour marian,

Toutes mes félicitations pour ton excellent travail et le temps consacré à celui-ci ....

Je viens ici après beaucoup de lectures et d'essais infructueux.

Pour résumé la situation
Windows 10
Java DK bien installé car j'ai bien la version qui s'affiche à l'invite de commande java --version
Maven bien installé car j'ai bien la version qui s'affiche à l'invite de commande

J'ai téléchargé la release 2.0 comme suggéré dans ton readme
le dossier dézippé est placé dans .studio
J'ai lancé le fichier bat mais j'ai toujours le même probleme 

2021-01-07 09:27:32,646 [ERROR] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:77]: Failed in deploying verticle
java.lang.ClassCastException: class com.google.gson.JsonPrimitive cannot be cast to class com.google.gson.JsonObject (com.google.gson.JsonPrimitive and com.google.gson.JsonObject are in unnamed module of loader 'app')
	at com.google.gson.JsonObject.getAsJsonObject(JsonObject.java:205)
	at studio.metadata.DatabaseMetadataService.lambda$new$0(DatabaseMetadataService.java:41)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:40)
	at studio.webui.MainVerticle.start(MainVerticle.java:47)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)

Dans ton readme, tu suggerais "Pour le firmware 2.x uniquement: configurez le point de montage de votre appareil dans le script de lancement grâce à FS_MOUNTPOINT" je ne vois pas ce que je dois modifier dans le fichier batch ?

merci de ton aide

**Comment by agademer** [comment]
Bonjour @TeensyDucM,
Tu dois ouvrir le fichier `studio-windows.bat` avec Bloc Notes et rajouter à la fin de la ligne `set FS_MOUNTPOINT=F:\` la lettre du lecteur de la lunii (en général la lettre d'après de ton disque dur).

Bon courage !

**Comment by TeensyDucM** [comment]
merci de cette reponse.

J'ai bien mis dans mon fichier batch 
set FS_MOUNTPOINT= F:\

mais j'ai toujours le même probleme de deploiement
2021-01-07 11:30:01,629 [ERROR] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:77]: Failed in deploying verticle
java.lang.ClassCastException: class com.google.gson.JsonPrimitive cannot be cast to class com.google.gson.JsonObject (com.google.gson.JsonPrimitive and com.google.gson.JsonObject are in unnamed module of loader 'app')
	at com.google.gson.JsonObject.getAsJsonObject(JsonObject.java:205)
	at studio.metadata.DatabaseMetadataService.lambda$new$0(DatabaseMetadataService.java:41)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:40)
	at studio.webui.MainVerticle.start(MainVerticle.java:47)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by agademer** [comment]
Sans espace ? (Vu que c'est du batch)

`set FS_MOUNTPOINT=F:\`

Après, ce n'est peut-être pas lié à ça ?

Quand la Lunii se monte, quelle est la lettre qui lui est associé ? (Dans l'explorateur Windows ?)

**Comment by TeensyDucM** [comment]
tout à fait il n'y a pas d'espace et la lettre correspond bien celle affichée quand je branche la lunii sur le pc

**Comment by agademer** [comment]
Tente de poster le fichier `studio-latest.log` (Glisser/Déposer) pour avoir toute la pile d'erreur.

**Comment by TeensyDucM** [comment]
[studio-latest.log](https://github.com/marian-m12l/studio/files/5781132/studio-latest.log)

**Comment by agademer** [comment]
Je ne suis pas sur que le dossier `studio-web-ui-0.3.0-alpha.2` doivent se trouver dans le `$HOME\.studio`.
C'est étrange, ça à l'air de planter tout de suite.

@marian-m12l  pourra probablement te répondre mieux...

**Comment by marian-m12l** [comment]
@TeensyDucM L'exception vient du fichier `official.json` qui n'est pas correct. Que contient-il ? Pour le support du nouveau firmware, c'est la version 0.3.0 et non 0.2.0 qu'il faut installer :-)

**Comment by TeensyDucM** [comment]
Merci marian, je pensais que l'on pouvait construire l'application sans l'official.json. faute à moi. Merci je vais mettre la version 0.30 car effectivement nous avions fait la mise à jour de l'été dernier. Je vais reessayer et reviens ici en cas de problème.

**Comment by marian-m12l** [comment]
@TeensyDucM L'application devrait fonctionner sans le fichier official.json, mais s'il est présent et incorrect cela cause une erreur.

La commande curl est donnée comme exemple, mais doit être adaptée sous windows. Plud d'infos ici: #155

**Comment by TeensyDucM** [comment]
L'application fonctionne, le fichier unofficial.json apparait bien dans le dossier db après lancement du fichier batch. Par contre, impossible d'enregistrer une nouvelle histoire dans la fabrique à histoire. faut il obligatoirement passer par l'etape du fichier official.json pour pouvoir sauvegarder dans celle-ci ?

Je precise que je suis avec la dernier release Beta 1. Par ailleurs, dans l'application, je me retrouve dans le cas décrit plus haut ou aucune image n'apparait en vignette sur les bibliotheques existantes.

**Comment by marian-m12l** [comment]
@TeensyDucM Ça ne devrait pas poser de problème. Que se passe-t-il lorsque la Lunii est branchée ? Lorsque le transfert commence ?

**Comment by TeensyDucM** [comment]
Pour l'etape de lofficiel.json, tout marche correctement. Quand je lance l'interface web STUDio, les packs existants apparaissent avec les images. Le problème reside dans le fait qu'il n'apparait aucun pack dans la partie droite de l'ecran et ce, même si j'utilise le pack exemple. je l'enregistre, valide les noeuds. Mais le pack n'est jamais transferé vers la bibliotheque afin de pouvoir y faire le deplacement vers la partie gauche.

**Comment by marian-m12l** [comment]
@TeensyDucM Étrange. Le dossier `.studio/library` contient des fichiers ?

**Comment by TeensyDucM** [comment]
bonjour

Il est vide.

J'ai laissé tourner longtemps pour test.

**Comment by marian-m12l** [comment]
@TeensyDucM Ce n'est pas normal. Il n'y a pas d'erreur lors de l'enregistrement du pack depuis l'éditeur ? Que disent les logs ?

**Comment by TeensyDucM** [comment]
Il n'y a aucune erreur si ce n'est que ça tourne sans s'arreter. Pour les logs, voici un extrait 👍 
2021-01-22 10:19:47,171 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.moveFile(java.io.File, java.io.File)'
	at studio.webui.service.LibraryService.addPackFile(LibraryService.java:317)
	at studio.webui.api.LibraryController.lambda$apiRouter$5(LibraryController.java:65)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-01-22 10:21:44,214 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.moveFile(java.io.File, java.io.File)'
	at studio.webui.service.LibraryService.addPackFile(LibraryService.java:317)
	at studio.webui.api.LibraryController.lambda$apiRouter$5(LibraryController.java:65)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-01-22 10:21:44,414 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.moveFile(java.io.File, java.io.File)'
	at studio.webui.service.LibraryService.addPackFile(LibraryService.java:317)
	at studio.webui.api.LibraryController.lambda$apiRouter$5(LibraryController.java:65)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-01-22 10:22:37,445 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.moveFile(java.io.File, java.io.File)'
	at studio.webui.service.LibraryService.addPackFile(LibraryService.java:317)
	at studio.webui.api.LibraryController.lambda$apiRouter$5(LibraryController.java:65)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-01-22 10:23:04,467 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.moveFile(java.io.File, java.io.File)'
	at studio.webui.service.LibraryService.addPackFile(LibraryService.java:317)
	at studio.webui.api.LibraryController.lambda$apiRouter$5(LibraryController.java:65)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-01-22 10:23:52,530 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.moveFile(java.io.File, java.io.File)'
	at studio.webui.service.LibraryService.addPackFile(LibraryService.java:317)
	at studio.webui.api.LibraryController.lambda$apiRouter$5(LibraryController.java:65)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-01-22 10:24:16,507 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.moveFile(java.io.File, java.io.File)'
	at studio.webui.service.LibraryService.addPackFile(LibraryService.java:317)
	at studio.webui.api.LibraryController.lambda$apiRouter$5(LibraryController.java:65)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-01-22 10:24:31,293 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.moveFile(java.io.File, java.io.File)'
	at studio.webui.service.LibraryService.addPackFile(LibraryService.java:317)
	at studio.webui.api.LibraryController.lambda$apiRouter$5(LibraryController.java:65)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-01-22 10:25:28,614 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.moveFile(java.io.File, java.io.File)'
	at studio.webui.service.LibraryService.addPackFile(LibraryService.java:317)
	at studio.webui.api.LibraryController.lambda$apiRouter$5(LibraryController.java:65)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-01-22 10:26:40,775 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.moveFile(java.io.File, java.io.File)'
	at studio.webui.service.LibraryService.addPackFile(LibraryService.java:317)
	at studio.webui.api.LibraryController.lambda$apiRouter$5(LibraryController.java:65)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-01-22 10:27:24,378 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.moveFile(java.io.File, java.io.File)'
	at studio.webui.service.LibraryService.addPackFile(LibraryService.java:317)
	at studio.webui.api.LibraryController.lambda$apiRouter$5(LibraryController.java:65)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-01-22 10:34:23,254 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.moveFile(java.io.File, java.io.File)'
	at studio.webui.service.LibraryService.addPackFile(LibraryService.java:317)
	at studio.webui.api.LibraryController.lambda$apiRouter$5(LibraryController.java:65)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-01-22 10:34:23,504 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.moveFile(java.io.File, java.io.File)'
	at studio.webui.service.LibraryService.addPackFile(LibraryService.java:317)
	at studio.webui.api.LibraryController.lambda$apiRouter$5(LibraryController.java:65)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-01-22 10:34:49,240 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.moveFile(java.io.File, java.io.File)'
	at studio.webui.service.LibraryService.addPackFile(LibraryService.java:317)
	at studio.webui.api.LibraryController.lambda$apiRouter$5(LibraryController.java:65)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)

merci

**Comment by marian-m12l** [comment]
@TeensyDucM C'est étrange comme exception. Quelle est la version de STUdio ? Quelle est la version de la bibliothèque "commons-io" dans le dossier "lib" de l'application ?

**Comment by TeensyDucM** [comment]
j'ai deux fichiers commencant par commons-io à savoir 
commons-io-1.3.2.jar
commons-io-2.6.jar

Merci

**Comment by marian-m12l** [comment]
@TeensyDucM il ne devrait pas y avoir la version 1.3.2, quelle archive a été utilisée ?

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.

**Comment by Ironmikedan** [comment]
Bonjour,
merci beaucoup pour votre outil,
il y a plus d'un an que je l'utilise et ce soir j'ai un message d'erreur,
2024-08-23 06:58:03,523 [ERROR] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:77]: Failed in deploying verticle
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 107 column 15545 path $.7e23bb98-30c0-4bd6-89fa-dfa414b792be.image
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at studio.metadata.DatabaseMetadataService.cleanUnofficialDatabase(DatabaseMetadataService.java:245)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:77)
	at studio.webui.MainVerticle.start(MainVerticle.java:47)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 107 column 15545 path $.7e23bb98-30c0-4bd6-89fa-dfa414b792be.image
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031)
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:702)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 17 more

impossible de lancer studio-web-ui-0.3.1 (j'ai essayer 0.4.0, 0.4.1 idem)
j'ai désinstallé java, réinstallé mais toujours le même problème
pouvez-vous m'apporter votre aide svp.
Merci à vous

**Comment by marian-m12l** [comment]
@Ironmikedan L'erreur indique que STUdio ne peut pas lire la base de données des packs d'histoires `unofficial.json`. Supprimer ou déplacer ce fichier devrait permettre d'exécuter à nouveau l'application, mais en perdant les données des packs non-officiels.

**Comment by Hayat91800** [comment]
Bonjour, 
depuis hier, j'ai ce message d'erreur qui s'affiche sur studio web ui 0.5.22024-11-14 11:52:02,666 [INFO ] [s.m.DatabaseMetadataService]: Reading official metadata in /Users/zakhoukh/.studio/db/official.json
2024-11-14 11:52:03,005 [INFO ] [s.m.DatabaseMetadataService]: Reading unofficial database in /Users/zakhoukh/.studio/db/unofficial.json
2024-11-14 11:52:03,480 [ERROR] [i.v.c.i.l.c.VertxIsolatedDeployer]: Failed in deploying verticle
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 419 column 115564 path $.cfaf1474-13b8-4a3e-afda-b2f780976ac6.image
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:85)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:60)
	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:87)
	at studio.webui.MainVerticle.start(MainVerticle.java:53)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 419 column 115564 path $.cfaf1474-13b8-4a3e-afda-b2f780976ac6.image
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1597)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031)
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:705)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:726)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:726)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:697)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 17 more
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Opération terminée]

Du coup, studio ne s'ouvre plus du tout.
j'ai essayer de tout désinstaller, de supprimer les histoire non officiel de mon ordinateur et de supprimer les fichiers unofficial.json et official.json mais rien n'y fait.

Merci pour votre aide
Hayat

**Comment by marian-m12l** [comment]
@Hayat91800 la version 0.52 correspond probablement à un fork de STUdio, vous devriez ouvrir une issue sur le dépôt correspondant.
