### ISSUE TITLE
Hotplug event trying to read the lunii partition too quickly resulting in a failure.

### ISSUE THREAD

**Issue by cvandeplas** [marian-m12l/studio#164]
**Describe the bug**
Hotplug event trying to read the lunii partition too quickly resulting in a failure.

**To Reproduce**
1. Start Studio
2. Open studio in the browser 
3. Turn on the lunii
5. Wait a bit more, and then refresh the webbrowser page. All then works fine.

**Logs**
```
021-01-24 07:53:50,743 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug event callback (0c45:6840): 1
2021-01-24 07:53:50,750 [INFO ] [s.w.s.StoryTellerService]: Device 2.x plugged
2021-01-24 07:53:50,757 [ERROR] [s.w.s.StoryTellerService]: Failed to plug device 2.x
studio.driver.StoryTellerException: Failed to read device metadata on partition
	at studio.driver.fs.FsStoryTellerAsyncDriver.getDeviceInfos(FsStoryTellerAsyncDriver.java:142)
	at studio.webui.service.StoryTellerService$2.lambda$onDevicePlugged$1(StoryTellerService.java:115)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.io.FileNotFoundException: /media/chri/disk/.md (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at studio.driver.fs.FsStoryTellerAsyncDriver.getDeviceInfos(FsStoryTellerAsyncDriver.java:97)
	... 8 more
```
 
**Desktop and environment (please complete the following information):**
 - OS:  Linux, ubuntu 20.04.1
 - Browser : chrome (latest)
 - STUdio application version: latest from git

**Comment by marian-m12l** [comment]
@cvandeplas Thanks for the feedback. STUdio checks for the mount point every second for ten seconds, to avoid this "reading too quickly" problem. And you're getting "Device 2.x plugged" so the ".md" file on the mount point **is** found. However the exception happens when trying to actually open the file. Can you check the permissions?

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
