### ISSUE TITLE
Failed to add big pack to device

### ISSUE THREAD

**Issue by thi71126** [marian-m12l/studio#171]
**Describe the bug**
Salut, j'ai un problème avec un pack un peu lourd que je veux transferer sur une Lunni V2.2.
je pense que le problème vient de la taille et non du contenu. 
Pourtant il  semble y avoir assez de place sur la Lunii

**To Reproduce**
J'ai créé un json avec 209 Histoires. 
 - si je mets un fichier final léger pour chaque Histoire ca passe
 - si je met le vrai fichier audio de chaque histoire ca passe si je met juste 100 histoire. et il me reste 70% de place livre sur la Lunii
 -  Masi dès que j'en met "trop" ~150:
        - la conversion est longue mais marche bien
        - au moment de transférer le pack sur la Lunni ca jette une erreur dès le début du transfert:  

        Pack folder size: 469094175
        Failed to add pack to device
        Failed to copy pack folder

**Expected behavior**
J'aimerai pouvoir faire un seul pack sans avoir a le séparer en plusieurs parties

**Logs**
2021-02-04 19:09:46,802 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:306]: Transferring pack folder to device: C:\Users\xxxxxxx\AppData\Local\Temp\histoires.zip14139793245028574055\A9379FA2
2021-02-04 19:09:46,847 [FINEST] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:392]: Pack folder size: 469094175
2021-02-04 19:09:46,848 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:401]: Uploading pack to folder: D:\.content\A9379FA2
2021-02-04 19:09:55,259 [FINEST] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:454]: Pack folder size: 469094175
2021-02-04 19:09:55,264 [TRACE] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:462]: Creating directory D:\.content\A9379FA2
2021-02-04 19:09:55,264 [ERROR] [studio.webui.service.StoryTellerService] [StoryTellerService.java:323]: Failed to add pack to device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to copy pack folder
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: studio.driver.StoryTellerException: Failed to copy pack folder
	at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$copyPackFolder$18(FsStoryTellerAsyncDriver.java:487)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at studio.driver.fs.FsStoryTellerAsyncDriver.copyPackFolder(FsStoryTellerAsyncDriver.java:457)
	at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$uploadPack$12(FsStoryTellerAsyncDriver.java:409)
	... 7 more
Caused by: java.nio.file.NoSuchFileException: D:\.content\A9379FA2
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectory(Unknown Source)
	at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$copyPackFolder$18(FsStoryTellerAsyncDriver.java:463)
	... 19 more

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
 - Java version: AdoptOpenJDK\jre-11.0.9.101-hotspot
 - STUdio application version: 0.3.0-beta.2

**Additional context**
La conversion des audio est longue alors que mes fichiers sont déjà des MP3. pourquoi est ce que STUdio les réencodent?
est il possible de déposer des fichiers déjà encodés correctement sans qu'il soient décodés et réencodés?
Pour info le pack a été généré avec un outil perso. Je me sert de STUdio juste pour l'envoyer vers la Lunni.
Mais dans le simulateur il fonctionne parfaitement même avec les 209 histoires

Merci pour le temps passé sur ce projet et le suivi!

**Comment by thi71126** [comment]
Apres de multiples tests le problème semble venir d'une perte de connexion de STUdio avec le port USB.
Un moyen simple de contourner le problème est de déconnecter/reconnecter la Lunni de temps en temps pendant que Studio encode les mp3. 
On peut éventuellement suivre l'avancement en examinant le fichier studio-latest.log avec notepadd++ et en comptant le nombre d'occurrence de "Re-encoding MP3" et en le comparant au nombre d'histoire qu'on a dans le projet. il suffit alors de déconnecter/reconnecter 1 a 2 minutes avant la fin.

Idéalement au lieu d'afficher une erreur au moment de transférer les données sur la Lunni, il faudrait demander à l'utilisateur de débrancher/rebrancher la Lunni puis cliquer sur "OK" pour lancer a nouveau le transfert.

un autre moyen serait de ne pas réencoder les mp3 qui sont déjà bien encodé. ;)
l'encodage de mes 209 histoires à pris plus de 30 minutes chez moi...

**Comment by marian-m12l** [comment]
@thi71126 Merci pour le retour détaillé !

L'erreur dans le premier message indique que le transfert échoue dès la création du répertoire du pack d'histoires. Ce qui m'intrigue, c'est que le chemin ne semble pas correct (`D:.content\A9379FA2`). Ce n'est peut-être qu'un problème de log, mais qu'elle valeur est renseignée comme point de montage ?

Quand le problème se pose, est-ce que la partition de la lunii est toujours visible dans l'explorateur de fichiers ?

Enfin, l'application ne devrait pas réencoder si les fichiers audio sont des MP3 Mono à 44100Hz.

Je travaille à l'amélioration de l'UI pour notamment faire la conversion explicitement avant le transfert, ce qui devrait résoudre ce problème.

**Comment by thi71126** [comment]
Visiblement Github n'aime pas l'enchainement de l'antislash et du point! mais il est bien présent dans mon log ;)
D est bien la lettre de mon lecteur => set FS_MOUNTPOINT=D:

De mémoire le lecteur D était toujours présent sur l'ordi avant le problème. je réessayerais pour être sûr. les enfants ne me laissent pas la Lunii pour l'instant...

La conversion avant le transfert serait l'idéal oui. merci de ne pas l'implémenter sur l'upload d'un fichier via l'interface mais juste avant le transfert vers la Lunii (ou via un bouton a part) pour les gens comme moi qui génèrent des json et le zip automatiquement et n'utilisent donc pas l'interface.

**Comment by thi71126** [comment]
Je confirme que avant l'erreur de transfert je peux me balader sans problème sur le disque de la Lunii depuis l'ordinateur.
seul une déconnexion/reconnexion de la Lunii avant le moment fatidique permet de pouvoir poursuivre le transfert.

**Comment by marian-m12l** [comment]
@thi71126 L'idée est effectivement de proposer un bouton de conversion explicite dans la partie "bibliothèque". Tout en conservant la conversion à la volée lors du transfert, et en enregistrant le fichier converti dans la bibliothèque (contrairement au comportement actuel).

**Comment by marian-m12l** [comment]
@thi71126 oui, la conversion se fait en dehors de l'éditeur.

**Comment by thi71126** [comment]
Bonjour @marian-m12l, je viens de tester la v0.3.0-beta.3
Et j'ai malheureusement le problème qu'avant mais en pire:

Sur le papier c'est bien de séparer la conversion du transfert vers la lunii, mais dans la pratique ca me demande quand même que la Lunii soit connectée pour lancer la conversion.
en soit c'est pas forcément très gênant même si ce serait plus pratique de le l'avoir que pour le transfert, Et du coup j'ai toujours l'erreur à la fin de la conversion quand le temps de conversion est trop long (27 minutes ici en l'occurrence)

2021-05-01 10:40:40,813 [INFO ] [studio.webui.service.LibraryService] [LibraryService.java:307]: Writing FS format pack
2021-05-01 10:40:51,836 [INFO ] [studio.webui.service.LibraryService] [LibraryService.java:313]: Moving FS format pack into local library: C:\Users\xxxxx\.studio\library\849d879c-f8fc-434e-81d9-b801c5b171d2.converted_1619858451836
2021-05-01 10:40:51,836 [ERROR] [studio.webui.service.LibraryService] [LibraryService.java:318]: Failed to convert archive format pack to FS format
java.nio.file.AccessDeniedException: C:\Users\xxxxx\AppData\Local\Temp\histoires.zip18201103633064798164\C5B171D2 -> C:\Users\xxxxx\.studio\library\849d879c-f8fc-434e-81d9-b801c5b171d2.converted_1619858451836
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.base/java.nio.file.Files.move(Unknown Source)
	at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:314)
	at studio.webui.api.LibraryController$2.run(LibraryController.java:103)
	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
	at java.base/java.util.TimerThread.run(Unknown Source)

En fait je ne sais pas si c'est lié a la connexion, même en déconnectant reconnectant la lunii comme je le faisait avec la v0.3.0-beta.2 j'ai le même problème

cependant y a une histoire de timout qui apparait a l'ecran et qui n'est pas dans les logs
Exception in thread "Timer-0" java.lang.RuntimeException: Failed to convert archive format pack to FS format
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:319)
        at studio.webui.api.LibraryController$2.run(LibraryController.java:103)
        at java.base/java.util.TimerThread.mainLoop(Unknown Source)
        at java.base/java.util.TimerThread.run(Unknown Source)
Caused by: java.nio.file.AccessDeniedException: C:\Users\xxxxx\AppData\Local\Temp\histoires.zip4572627978216349102\C5B171D2 -> C:\Users\xxxxx\.studio\library\849d879c-f8fc-434e-81d9-b801c5b171d2.converted_1619862556741
        at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileCopy.move(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
        at java.base/java.nio.file.Files.move(Unknown Source)
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:314)

De mon point de vue c'est dommage que la conversion au format TS soit lié a l'anonymisation des données. ce serait intéressant de pouvoir juste convertir les fichiers audio et images au bon format et de pouvoir les conserver ainsi dans la bibliothèque histoire que si on modifie le pack par la suite on ne doive pas tout reconvertir

C'est dommage aussi de ne pas pouvoir ouvrir les gros packs dans l'éditeur. dès qu'il a quelques centaines de nœud c'est quasi impossible. ca prend énormément de ressources.
Mais j'en demande peut être trop ;)

Bon courage

**Comment by marian-m12l** [comment]
@thi71126 Pour le premier point, la dernière version permet de faire la conversion sans brancher l'appareil. Pour le deuxième point, en l'état le format des ressources converties n'est pas approprié car le début de chaque fichier est chiffré. Mais ce n'est pas incontournable, l'idée mérite d'être creusée car effectivement devoir reconvertir toutes les ressources si on ne modifie qu'un peu le pack, ce n'est pas idéal. Côté éditeur, effectivement il n'est pas du tout optimisé, toutes les ressources sont chargées dans le navigateur... Là encore ce n'est pas trivial mais ça serait bénéfique pour tout le monde, y compris pour les petits packs d'histoires, et pour supporter des configurations de PC moins véloces.

**Comment by thi71126** [comment]
J'ai testé la v0.3.0
Plus besoin en effet d'avoir la Lunni connecté pour préparer une archive. c'est parfait !
La première fois que j'ai tenté le transfert j'ai quand même eu la même erreur que précédemment.
Puis j'ai réessayé en coupant un maximum de chose sur mon ordi (antivirus, connexion réseau, skype, mails ...) pour avoir le plus de ressource possible disponible pour Studio. et là ca a pris du temps (40 minutes ) mais ca a fonctionné! et du coup j'ai eu besoin de monopoliser la Lunni juste 3 minutes pour le transfert.
donc a priori ca devait venir d'un problème sur mon ordi.
Merci @marian-m12l

**Comment by marian-m12l** [comment]
Content de voir que ça fonctionne. Par contre 40 minutes, il y a beaucoup de fichiers audios à convertir ? Ça vaudrait peut-être le coup de les enregistrer directement dans un format compatible. Il faudrait que je mette à jour le readme ou le wiki avec le détail du format attendu pour les MP3, et éventuellement une commande ffmpeg qui va bien..
