### ISSUE TITLE
Erreur de conversion lors du téléversement

### ISSUE THREAD

**Issue by jyoci** [marian-m12l/studio#178]
Lors du téléversement sur l'appareil, il y a dans la fenêtre de lancement une erreur de conversion.
le pack nest pas de mon cru, on peut le télécharger ici: https://drive.google.com/open?id=1lWY2h3xCF8LlDV7WFK2qGQczlUWBDU5g
Il est vraisemblable qu'une image ne soit pas au bon format, mais le message d'erreur ne dit pas laquelle... ce qui ne facilite pas le travail de recherche!
Le message d'erreur:

2021-02-20 17:16:59,518 [ERROR] [s.w.s.LibraryService]: Failed to convert archive format pack to FS folder format
java.lang.IllegalArgumentException: FS pack file requires image assets to be 320x240 pixels.
        at studio.core.v1.writer.fs.FsStoryPackWriter.write(FsStoryPackWriter.java:127)
        at studio.webui.service.LibraryService.getFsPackFile(LibraryService.java:264)
        at studio.webui.api.DeviceController$2.run(DeviceController.java:96)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
2021-02-20 17:16:59,519 [ERROR] [s.w.a.DeviceController]: Failed to read or convert pack
2021-02-20 17:16:59,520 [ERROR] [s.w.MainVerticle]: Exception thrown io.vertx.core.impl.NoStackTraceThrowable: Failed to read or convert pack to folder format

**Comment by thi71126** [comment]
Salut,
Si tu dézippe et que tu regardes la taille des images, tu verra que l'image 95ed56f7b0d2e8d26a6cdaa2ddcce77557a7cfc3.jpg fait 320x241 pixels.
Je pense que si tu enlèves le pixel en trop ca devrait fonctionner.
PS : Avec Windows tu peux afficher la "dimension" en faisant un click droit sur l'entête des colonne de ton explorateur de fichier

![image](https://user-images.githubusercontent.com/77553154/108897289-3c6bfc00-7616-11eb-985e-9ac231bd7345.png)

**Comment by marian-m12l** [comment]
@jyoci À cet endroit-là du code, on ne dispose pas du nom de fichier. On pourrait peut-être afficher l'uuid du noeud concerné.

**Comment by jyoci** [comment]
@marian-m12l  Ce serait une bonne ID ;o)

**Comment by Orfait** [comment]
@marian-m12l
Petite proposition pour une utilisation plus user-friendly :
- redimensionner par défaut en 320x240 
- si l'image source n'était pas dans un format proportionnel alors faire un warning avec uuid + miniature de l'image

Le petit plus : l'éditeur vérifie le format de l'image et signale quand il n'est pas bon (encadré rouge / panneau exclamation)

**Comment by marian-m12l** [comment]
@Orfait L'éditeur contrôle maintenant les dimensions lors de l'ajout d'une image. Mais ce serait intéressant d'avoir une erreur plus visible pour un pack pré-existant, effectivement.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
