### ISSUE TITLE
Erreur de conversion d'archive V1 vers V2 lors du transfert depuis le repertoire /tmp (fonction Files.move)

### ISSUE THREAD

**Issue by kollibar** [marian-m12l/studio#183]
**Describe the bug**
Erreur systèmatique lors de la conversion de l'archive au format v2 qui n'aboutit jamais. (voir log d'erreur)

**To Reproduce**
sur un système linux avec partition /tmp séparée de la /home.
avec un histoire déjà crée, lors du click sur le bouton "convertir cette histoire au format FS (v2.x)" 

**Expected behavior**
D'après les logs d'erreur ça plante sur at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:314)
`Files.move(folderPath, destinationPath);`
Dans mon cas le déplacement doit se faire depuis la partition /tmp vers la partition /home. Or d'après la doc java:

> You can move a file or directory by using the move(Path, Path, CopyOption...) method. The move fails if the target file exists, unless the REPLACE_EXISTING option is specified.

> Empty directories can be moved. If the directory is not empty, the move is allowed when the directory can be moved without moving the contents of that directory. On UNIX systems, moving a directory within the same partition generally consists of renaming the directory. In that situation, this method works even when the directory contains files.

Étant donnée que le déplacement doit se faire depuis une partition (/tmp) vers une autre (/home) il est normal que le transfert échoue.

**Logs**
2021-03-18 19:30:49,647 [FINEST] [s.d.f.FsStoryTellerAsyncDriver]: Reading packs index from file: /media/thom/disk/.pi
2021-03-18 19:30:49,647 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Number of packs in index: 3
2021-03-18 19:30:49,648 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: c8b39950-de17-4eaa-8e85-2a07fc468267
2021-03-18 19:30:49,657 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2021-03-18 19:30:49,665 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: d489f67b-0e51-4669-b1e1-1555f3c18541
2021-03-18 19:30:49,666 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2021-03-18 19:30:49,668 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: c4139d59-872a-4d15-8cf1-76d34cdf38c6
2021-03-18 19:30:49,668 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 2
2021-03-18 19:30:52,963 [INFO ] [s.w.s.LibraryService]: Pack to transfer is in archive format. Converting to FS format and storing in temporary folder: /tmp/les_histoires_de_petit_cheval-f54fd85d-c87f-4a11-b22e-738790ffbd8d-v1.zip7670982598273133980
2021-03-18 19:30:52,965 [INFO ] [s.w.s.LibraryService]: Reading archive format pack
2021-03-18 19:30:52,984 [INFO ] [s.w.s.LibraryService]: Converting assets if necessary
2021-03-18 19:30:52,995 [DEBUG] [s.c.v.u.PackAssetsCompression]: Converting image asset into 4-bits/RLE BMP
2021-03-18 19:30:53,139 [DEBUG] [s.c.v.u.ID3Tags]: Removing ID3v2 tag at beginning of file (1034 bytes).
2021-03-18 19:30:53,224 [DEBUG] [s.c.v.u.ID3Tags]: Removing ID3v2 tag at beginning of file (1034 bytes).
2021-03-18 19:30:53,248 [DEBUG] [s.c.v.u.ID3Tags]: Removing ID3v2 tag at beginning of file (1034 bytes).
2021-03-18 19:30:53,251 [DEBUG] [s.c.v.u.PackAssetsCompression]: Converting image asset into 4-bits/RLE BMP
2021-03-18 19:30:53,366 [DEBUG] [s.c.v.u.ID3Tags]: Removing ID3v2 tag at beginning of file (1034 bytes).
2021-03-18 19:30:53,377 [INFO ] [s.w.s.LibraryService]: Writing FS format pack
2021-03-18 19:30:53,471 [INFO ] [s.w.s.LibraryService]: Moving FS format pack into local library: /home/thom/.studio/library/f54fd85d-c87f-4a11-b22e-738790ffbd8d.converted_1616092253467
2021-03-18 19:30:53,472 [ERROR] [s.w.s.LibraryService]: Failed to convert archive format pack to FS format
java.nio.file.DirectoryNotEmptyException: /tmp/les_histoires_de_petit_cheval-f54fd85d-c87f-4a11-b22e-738790ffbd8d-v1.zip7670982598273133980/90FFBD8D
	at java.base/sun.nio.fs.UnixCopyFile.ensureEmptyDir(UnixCopyFile.java:382)
	at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:482)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267)
	at java.base/java.nio.file.Files.move(Files.java:1426)
	at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:314)
	at studio.webui.api.LibraryController$2.run(LibraryController.java:103)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

**Desktop and environment (please complete the following information):**
 - OS: linux (ubuntu 20.04)
 - Browser firefox
 - Java version: openjdk-14
 - Maven version: 3.6.3-1
 - STUdio application version (0.3.0-beta.3-SNAPSHOT)

**Additional context**
partition /tmp séparée de la partition /home

**Comment by kollibar** [comment]
Bonjour,

J'ai fait quelques modif dans le code et maintenant ça marche. En gros création d'un repertoire temporaire dans le repertoire .studio, à côté du repertoire library.

le diff entre le fichier LibraryService .java original et celui modifié:
avec en gros,:
* ajout d'une variable LOCAL_TMP_PATH
* ajout de la création de ce rapertoire temporaire au démarrage (en même temps que la création du repertoire library)
* ajout d'une méthode tmpPath() qui retourne un String avec le repertoire tmp (peut être y ajouter un choix du repertoire tmp à utiliser ??)
* modification de tous les accès au repertoire temporaire (il y en a 6) pour le faire dans le repertoire LOCAL_TMP_PATH

```
--- LibraryService.java.old	2021-03-24 11:41:32.979511933 +0100
+++ LibraryService.java	2021-03-24 11:36:52.765109217 +0100
@@ -43,6 +43,7 @@
 
     public static final String LOCAL_LIBRARY_PROP = "studio.library";
     public static final String LOCAL_LIBRARY_PATH = "/.studio/library/";
+    public static final String LOCAL_TMP_PATH = "/.studio/tmp/";
 
     private final Logger LOGGER = LoggerFactory.getLogger(LibraryService.class);
 
@@ -61,6 +62,17 @@
                 throw new IllegalStateException("Failed to initialize local library");
             }
         }
+        
+        // Create the local tmp folder if needed
+        File tmpFolder = new File(tmpPath());
+        if (!tmpFolder.exists() || !tmpFolder.isDirectory()) {
+            try {
+                Files.createDirectories(Paths.get(tmpPath()));
+            } catch (IOException e) {
+                LOGGER.error("Failed to initialize tmp folder", e);
+                throw new IllegalStateException("Failed to initialize tmp folder");
+            }
+        }
     }
 
     public JsonObject libraryInfos() {
@@ -146,7 +158,8 @@
         // Archive format packs must first be converted to raw format
         if (packPath.endsWith(".zip")) {
             try {
-                File tmp = File.createTempFile(packPath, ".pack");
+                Path path = Files.createTempFile(Paths.get(tmpPath()), packPath, ".pack");
+                File tmp = path.toFile();
 
                 LOGGER.info("Pack is in archive format. Converting to raw format and storing in temporary file: " + tmp.getAbsolutePath());
 
@@ -184,7 +197,8 @@
             throw new RuntimeException("Pack is already in raw format");
         } else {
             try {
-                File tmp = File.createTempFile(packPath, ".pack");
+                Path path = Files.createTempFile(Paths.get(tmpPath()), packPath, ".pack");
+                File tmp = path.toFile();
 
                 LOGGER.info("Pack is in FS format. Converting to raw format and storing in temporary file: " + tmp.getAbsolutePath());
 
@@ -225,7 +239,8 @@
             throw new RuntimeException("Pack is already in archive format");
         } else if (packPath.endsWith(".pack")) {
             try {
-                File tmp = File.createTempFile(packPath, ".zip");
+                Path path = Files.createTempFile(Paths.get(tmpPath()), packPath, ".zip");
+                File tmp = path.toFile();
 
                 LOGGER.info("Pack is in raw format. Converting to archive format and storing in temporary file: " + tmp.getAbsolutePath());
 
@@ -257,7 +272,8 @@
             }
         } else {
             try {
-                File tmp = File.createTempFile(packPath, ".zip");
+                Path path = Files.createTempFile(Paths.get(tmpPath()), packPath, ".zip");
+                File tmp = path.toFile();
 
                 LOGGER.info("Pack is in FS format. Converting to archive format and storing in temporary file: " + tmp.getAbsolutePath());
 
@@ -290,7 +306,10 @@
         // Archive format packs must first be converted to FS format
         if (packPath.endsWith(".zip")) {
             try {
-                Path tmp = Files.createTempDirectory(packPath);
+                //Path tmp = Files.createTempDirectory(packPath, tmpPath() );
+                //Path tmp = createTmpDirectory(packPath);
+                Path tmp = Files.createTempDirectory(Paths.get(tmpPath()), packPath);
+                
 
                 LOGGER.info("Pack to transfer is in archive format. Converting to FS format and storing in temporary folder: " + tmp.toAbsolutePath().toString());
 
@@ -320,7 +339,9 @@
             }
         } else if (packPath.endsWith(".pack")) {
             try {
-                Path tmp = Files.createTempDirectory(packPath);
+                //Path tmp = Files.createTempDirectory(packPath, tmpPath());
+                //Path tmp = createTmpDirectory(packPath);
+                Path tmp = Files.createTempDirectory(Paths.get(tmpPath()), packPath);
 
                 LOGGER.info("Pack is in raw format. Converting to FS format and storing in temporary folder: " + tmp.toAbsolutePath().toString());
 
@@ -399,6 +420,11 @@
         // Path may be overridden by system property `studio.library`
         return System.getProperty(LOCAL_LIBRARY_PROP, System.getProperty("user.home") + LOCAL_LIBRARY_PATH);
     }
+    
+    public String tmpPath() {
+        // Path may be overridden by system property `studio.library`
+        return System.getProperty(LOCAL_LIBRARY_PROP, System.getProperty("user.home") + LOCAL_TMP_PATH);
+    }
 
     private Optional<LibraryPack> readPackFile(Path path) {
         LOGGER.debug("Reading pack file: " + path.toString());

```

**Comment by vpoulailleau** [comment]
@marian-m12l J'ai le même problème avec la béta 3 officielle. L'interface utilisateur me dit que la conversion est toujours en cours, par contre dans la console, j'ai le fameux :

```
2021-04-25 12:27:47,200 [ERROR] [s.w.s.LibraryService]: Failed to convert archive format pack to FS format
java.nio.file.DirectoryNotEmptyException: /tmp/...
	at java.base/sun.nio.fs.UnixCopyFile.ensureEmptyDir(UnixCopyFile.java:384)
	at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:484)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267)
	at java.base/java.nio.file.Files.move(Files.java:1422)
	at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:314)
	at studio.webui.api.LibraryController$2.run(LibraryController.java:103)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Exception in thread "Timer-0" java.lang.RuntimeException: Failed to convert archive format pack to FS format
	at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:319)
	at studio.webui.api.LibraryController$2.run(LibraryController.java:103)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.nio.file.DirectoryNotEmptyException: /tmp/...
	at java.base/sun.nio.fs.UnixCopyFile.ensureEmptyDir(UnixCopyFile.java:384)
	at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:484)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267)
	at java.base/java.nio.file.Files.move(Files.java:1422)
	at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:314)
	... 3 more
```

J'ai supprimé les chemins dans le log ci-dessus, mais c'est aussi une histoire de `/tmp` sur une autre partition que `/home`. J'ai pour l'instant contourné le problème en utilisant la béta 2.

**Comment by marian-m12l** [comment]
@kollibar @vpoulailleau  just pushed to patch, let me know if its OK for you now.

**Comment by vpoulailleau** [comment]
@marian-m12l It's working great for me! Thanks @marian-m12l and @kollibar.

**Comment by kollibar** [comment]
@marian-m12l 👍  same for me ! t's working great. perfect !

**Comment by otiste** [comment]
Same error with last stable build 0.4.2... (Lunii v2)

```
2026-07-27 13:07:54,980 [ERROR] [s.w.s.LibraryService]: Failed to convert archive format pack to FS format
java.lang.IllegalArgumentException: Invalid UUID string: FAC5562D
        at java.base/java.util.UUID.fromString1(UUID.java:333)
        at java.base/java.util.UUID.fromString(UUID.java:311)
        at studio.core.v1.writer.fs.FsStoryPackWriter.write(FsStoryPackWriter.java:47)
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:326)
        at studio.webui.api.LibraryController$2.run(LibraryController.java:102)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:572)
        at java.base/java.util.TimerThread.run(Timer.java:522)
Exception in thread "Timer-0" java.lang.RuntimeException: Failed to convert archive format pack to FS format
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:336)
        at studio.webui.api.LibraryController$2.run(LibraryController.java:102)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:572)
        at java.base/java.util.TimerThread.run(Timer.java:522)
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: FAC5562D
        at java.base/java.util.UUID.fromString1(UUID.java:333)
        at java.base/java.util.UUID.fromString(UUID.java:311)
        at studio.core.v1.writer.fs.FsStoryPackWriter.write(FsStoryPackWriter.java:47)
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:326)
        ... 3 more
```
