### ISSUE TITLE
Failed to convert the pack to the device

### ISSUE THREAD

**Issue by loupblack** [marian-m12l/studio#193]
**Describe the bug**
I can't drag and drop the new pack I created to my device

**To Reproduce**
1. Go to 'LOCAL LIBRARY'
2. drag and drop a pack to the device zone
3. See error

**Expected behavior**
I created a pack with 1 cover node, 1 Menu node and 2 story node. My pictures are in png, my menu audio files are in mp3 and the story in ogg.

**Logs**
2021-04-22 10:00:22,654 [ERROR] [studio.metadata.DatabaseMetadataService] [DatabaseMetadataService.java:46]: Missing official metadata database file
java.io.FileNotFoundException: C:\Users\Loupblack\.studio\db\official.json (Le fichier spécifié est introuvable)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:108)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:36)
	at studio.webui.MainVerticle.start(MainVerticle.java:47)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
2021-04-22 10:00:22,742 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:53]: Setting up story teller driver
2021-04-22 10:00:22,746 [DEBUG] [studio.driver.raw.RawStoryTellerAsyncDriver] [RawStoryTellerAsyncDriver.java:44]: Registering hotplug listener
2021-04-22 10:00:22,749 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:48]: Initializing libusb...
2021-04-22 10:00:22,913 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:73]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2021-04-22 10:00:22,913 [DEBUG] [studio.driver.LibUsbAsyncEventsWorker] [LibUsbAsyncEventsWorker.java:32]: Starting worker thread to handle libusb async events...
2021-04-22 10:00:22,918 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:56]: Registering hotplug listener
2021-04-22 10:00:22,919 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:48]: Initializing libusb...
2021-04-22 10:00:22,919 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:73]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2021-04-22 10:00:22,920 [DEBUG] [studio.driver.LibUsbAsyncEventsWorker] [LibUsbAsyncEventsWorker.java:32]: Starting worker thread to handle libusb async events...
2021-04-22 10:00:23,037 [INFO ] [studio.webui.MainVerticle] [MainVerticle.java:106]: Opening URL in default browser...
2021-04-22 10:00:23,090 [INFO ] [studio.driver.LibUsbActivePollingWorker] [LibUsbActivePollingWorker.java:65]: Active polling found a new device. Firing event.
2021-04-22 10:00:23,140 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:65]: Lunii FS mount point: K:\
2021-04-22 10:00:23,141 [INFO ] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:74]: FS device partition is mounted.
2021-04-22 10:00:23,143 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:113]: Device 2.x plugged
2021-04-22 10:00:23,146 [FINEST] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:122]: Reading device infos from file: K:\\.md
2021-04-22 10:00:23,149 [FINEST] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:127]: Device metadata format version: 2
2021-04-22 10:00:23,153 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:138]: Firmware version: 2.20
2021-04-22 10:00:23,154 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:145]: Serial Number: 9026995046326594
2021-04-22 10:00:23,186 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:155]: UUID: f4f85a71bfb574acc5f8c57e2360f03939b2fd3fb2fde2af7c925ccadd00fbf4bc32aa834d5195605ada0171de40689c8d18b54fb3e3977e3f29988776f65ca8c08b384d82e4fcc9059724436d44cd1f4962c5c7c1537b3e2af5d56175ad7d6c692d1bcbb8c8421eaecdcd728d2fe29ed60670c378d2e43838ac6825ab0eacaea5c615f27a070d30f288257e73198070230ab72df8fe5dc4dcc1306ce07816c8825e9b240e9b4665051f98ab2dc80969eb9fa0d76e3bd1ada65b8b4ff56168180d5435f5d7e597f708651468f26c1b81d081599de2d38a291ef7f04de8c89fb1faa33e7c6de8fd4c337a12f35203dd12cdeaa7d8c1afbf870a967bdfee2828c5
2021-04-22 10:00:23,197 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:165]: SD card size: 15476981760
2021-04-22 10:00:23,198 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:166]: SD card used space: 162398208
2021-04-22 10:00:23,493 [INFO ] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:81]: Succeeded in deploying verticle
2021-04-22 10:00:24,138 [ERROR] [io.vertx.core.http.impl.HttpServerImpl] [HttpServerImpl.java:307]: java.net.BindException: Address already in use: bind
2021-04-22 10:01:04,496 [INFO ] [studio.driver.LibUsbActivePollingWorker] [LibUsbActivePollingWorker.java:69]: Active polling lost the device. Firing event.
2021-04-22 10:01:04,497 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:144]: Device 2.x unplugged
2021-04-22 10:01:07,959 [INFO ] [studio.driver.LibUsbActivePollingWorker] [LibUsbActivePollingWorker.java:69]: Active polling lost the device. Firing event.
2021-04-22 10:01:07,961 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:144]: Device 2.x unplugged
2021-04-22 10:01:08,209 [INFO ] [studio.driver.LibUsbActivePollingWorker] [LibUsbActivePollingWorker.java:65]: Active polling found a new device. Firing event.
2021-04-22 10:01:08,212 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:65]: Lunii FS mount point: 
2021-04-22 10:01:12,963 [INFO ] [studio.driver.LibUsbActivePollingWorker] [LibUsbActivePollingWorker.java:65]: Active polling found a new device. Firing event.
2021-04-22 10:01:12,964 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:65]: Lunii FS mount point: K:\
2021-04-22 10:01:12,966 [INFO ] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:74]: FS device partition is mounted.
2021-04-22 10:01:12,967 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:113]: Device 2.x plugged
2021-04-22 10:01:12,968 [FINEST] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:122]: Reading device infos from file: K:\\.md
2021-04-22 10:01:12,969 [FINEST] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:127]: Device metadata format version: 2
2021-04-22 10:01:12,970 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:138]: Firmware version: 2.20
2021-04-22 10:01:12,971 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:145]: Serial Number: 9026995046326594
2021-04-22 10:01:12,971 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:155]: UUID: f4f85a71bfb574acc5f8c57e2360f03939b2fd3fb2fde2af7c925ccadd00fbf4bc32aa834d5195605ada0171de40689c8d18b54fb3e3977e3f29988776f65ca8c08b384d82e4fcc9059724436d44cd1f4962c5c7c1537b3e2af5d56175ad7d6c692d1bcbb8c8421eaecdcd728d2fe29ed60670c378d2e43838ac6825ab0eacaea5c615f27a070d30f288257e73198070230ab72df8fe5dc4dcc1306ce07816c8825e9b240e9b4665051f98ab2dc80969eb9fa0d76e3bd1ada65b8b4ff56168180d5435f5d7e597f708651468f26c1b81d081599de2d38a291ef7f04de8c89fb1faa33e7c6de8fd4c337a12f35203dd12cdeaa7d8c1afbf870a967bdfee2828c5
2021-04-22 10:01:12,973 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:165]: SD card size: 15476981760
2021-04-22 10:01:12,975 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:166]: SD card used space: 162398208

> Internal Server Error: Error 500: Internal Server Error

**Desktop and environment (please complete the following information):**
 - OS: Win64
 - Browser  Chrome/89.0.4389.128 
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.3.0-beta.2

**Comment by marian-m12l** [comment]
@loupblack Thanks for the feedback. Looks like you have a port conflict:

```
 2021-04-22 10:00:24,138 [ERROR] [io.vertx.core.http.impl.HttpServerImpl] [HttpServerImpl.java:307]: java.net.BindException: Address already in use: bind
```

Can you check if you have another application running which uses port 8080?

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
