### ISSUE TITLE
Failed to convert archive format pack to FS format

### ISSUE THREAD

**Issue by Hydro8** [marian-m12l/studio#195]
Bonjour
Lorsque j'essaye de mettre des packs sur ma lunii v2, par exemple les histoires du confinement ou le pack des histoires mcdo, j'ai cette erreur :

21-05-01 09:09:38,598 [INFO ] [s.w.s.LibraryService]: Writing FS format pack
2021-05-01 09:09:39,241 [ERROR] [s.w.s.LibraryService]: Failed to convert archive format pack to FS format
java.lang.IllegalArgumentException: FS pack file requires image assets to be 320x240 pixels.
at studio.core.v1.writer.fs.FsStoryPackWriter.write(FsStoryPackWriter.java:127)
at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:309)
at studio.webui.api.LibraryController$2.run(LibraryController.java:103)
at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
at java.base/java.util.TimerThread.run(Timer.java:506)
Exception in thread "Timer-5" java.lang.RuntimeException: Failed to convert archive format pack to FS format
at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:319)
at studio.webui.api.LibraryController$2.run(LibraryController.java:103)
at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.lang.IllegalArgumentException: FS pack file requires image assets to be 320x240 pixels.
at studio.core.v1.writer.fs.FsStoryPackWriter.write(FsStoryPackWriter.java:127)
at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:309)
... 3 more

Puis il ne se passe plus rien dans les logs. Une idée du problème ? On dirait que cela provient des images sauf que personnes d'autres ne semble remonter ce problème....

Je suis en version 0.3 beta 3 et j'ai essayé avec la beta 2, même problème mais cette fois-ci j'ai un message d'erreur du site local.
Merci !

**Comment by thi71126** [comment]
salut,
a priori tu as des images qui ne font pas 320x240 pixel dans ton pack.
regardes ce post https://github.com/marian-m12l/studio/issues/178

les dernières versions beta2 et 3  obligent a avoir des images de ces dimension.
je crois que c'est ma faute car j'ai eu un problème de dimensions un jour que j'ai signalé et marian a bridé depuis...
ce qui pose effectivement problème avec des anciens packs
ce serait mieux si les images pouvaient être automatiquement redimensionnées en 320x240

**Comment by Hydro8** [comment]
Merci pour ta réponse.

Voici les dimensions à l'intérieur du dossier assets :

![image](https://user-images.githubusercontent.com/5537697/116781707-010e0380-aa85-11eb-896b-60c1a8cbe352.png)

La seul image qui est trop grande est "thumbnail.png" à la racine du dossier. Celle-ci aussi doit être de 320x240 ?

**Comment by Hydro8** [comment]
Bonjour
Pour le pack mcdo, après avoir redimensionner la plus petite image, j'ai pu transférer le pack.
Par contre le pack des histoires pomme d'api possède une seule image à la bonne taille mais il m'indique cette erreur.

**Comment by Hydro8** [comment]
J'ai finalement vu une image avec 1 pixel en trop :)
