### ISSUE TITLE
Échec de la récupération des packs d'histoires de la bibliothèque.

### ISSUE THREAD

**Issue by jullebarge** [marian-m12l/studio#203]
**Describe the bug**
Je n'arrive plus à afficher la bibliothèque. J'ai tout de suite une erreur "Échec de la récupération des packs d'histoires de la bibliothèque."
Ceci après mise à jour en version 0.3.0 et tentative de chargement d'un pack d'histoires customs (dispo ici: https://drive.google.com/file/d/1P31Mkasv81qjoFiIrvWGyZqyiKnli9E4/view?usp=sharing)

**To Reproduce**

- Lancer studio
- Glisser-déposer le pack cité plus haut
- Le pack se convertit et ensuite l'erreur s'affiche
- Si je relance l'appli, j'ai toujours l'erreur qui s'affiche, je ne peux plus rien faire avec studio.

**Expected behavior**
Affichage de la bibliothèque avec le nouveau pack ajouté

**Screenshots**
![image](https://user-images.githubusercontent.com/11553167/120014201-1160c200-bfe2-11eb-98cc-00a6e7074025.png)

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> malformed input off : 16, length : 1: Error 500: malformed input off : 16, length : 1	at java.base/java.lang.StringCoding.throwMalformed(StringCoding.java:698)
	at java.base/java.lang.StringCoding.decodeUTF8_0(StringCoding.java:885)
	at java.base/java.lang.StringCoding.newStringUTF8NoRepl(StringCoding.java:978)
	at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2267)
	at java.base/java.util.zip.ZipCoder$UTF8ZipCoder.toString(ZipCoder.java:208)
	at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:66)
	at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:302)
	at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:124)
	at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
	at studio.webui.service.LibraryService.readPackFile(LibraryService.java:436)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at studio.webui.service.LibraryService.packs(LibraryService.java:99)
	at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.3.0

**Additional context**

**Comment by marian-m12l** [comment]
@jullebarge Merci pour le retour. Je ne suis pas sûr de comprendre exactement la démarche suivie : le pack au format archive est importé dans la bibliothèque locale par glissé-déposé, et l'erreur apparaît immédiatement ? Il n'y a pas de transfert depuis ou vers l'appareil ? Il y a six packs dans l'archive, quel est celui qui pose problème ?

**Comment by targyll** [comment]
Bonjour,

J'ai eu le même problème (que j'ai décrit ci-dessous, j'avais ouvert un autre post, que j'ai fermé depuis).
Comme @juliebarge j'ai eu ce problème après avoir voulu uploader le pack d'histoire custom dont le lien était donné dans son post.
J'ai constaté par la suite que ce "gros" pack contenait lui-même plusieurs packs d'histoires zippés. D'où l'erreur initiale, sans doute.
Ce que je ne comprends pas, c'est pourquoi il n'y a pas moyen de retrouver un STUdio fonctionnel après réinitialisation de la Lunii via le luniistore. 
Je pense à un fichier à effacer sur la partition de la lunii (autre que le dossier .content, ça j'ai forcément essayé), mais j'ai peur de faire une bêtise car je n'ai aucune idée de ce qui s'y trouve...

**Describe the bug**
STUdio lauches normally.
When I connect my device, I get the error message: "Failed to fetch packs from library"
When I try to upload a new story pack, it seems to load (but it is not on the device after I disconnect) and STUdio displays "Failed to refresh library"

**To Reproduce**
Steps to reproduce the behavior:
Everytime... since I tried to load a big story pack (then I noticed this pack had several zip files in it).
But then, I opened the Lunii App to reset the device.

**Logs**
Here is the log from my Terminal window:

2021-07-27 17:39:18,195 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle
2021-07-27 17:39:18,793 [ERROR] [s.w.MainVerticle]: Exception thrown
java.nio.channels.ClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.write(WebSocketServerExtensionHandler.java:151)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:124)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:205)
	at io.vertx.core.http.impl.Http1xServerConnection.writeToChannel(Http1xServerConnection.java:267)
	at io.vertx.core.net.impl.ConnectionBase.sendFileRegion(ConnectionBase.java:417)
	at io.vertx.core.net.impl.ConnectionBase.sendFile(ConnectionBase.java:444)
	at io.vertx.core.http.impl.Http1xServerConnection.sendFile(Http1xServerConnection.java:456)
	at io.vertx.core.http.impl.HttpServerResponseImpl.doSendFile(HttpServerResponseImpl.java:514)
	at io.vertx.core.http.impl.HttpServerResponseImpl.sendFile(HttpServerResponseImpl.java:433)
	at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:365)
	at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:351)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendFile$11(StaticHandlerImpl.java:457)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.wrapInTCCLSwitch(StaticHandlerImpl.java:266)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.sendFile(StaticHandlerImpl.java:392)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$null$0(StaticHandlerImpl.java:231)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.getFileProps(StaticHandlerImpl.java:299)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:208)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-07-27 17:39:18,958 [INFO ] [s.d.f.FsStoryTellerAsyncDriver]: FS device partition located: /Volumes/LUNII
2021-07-27 17:39:18,958 [INFO ] [s.w.s.StoryTellerService]: Device 2.x plugged
2021-07-27 17:39:18,962 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Firmware version: 2.6
2021-07-27 17:39:18,963 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Serial Number: 10004190415449
2021-07-27 17:39:18,967 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: UUID: ac2c6f489edf7b64876252ccf730be8b380c5686b391c423b7c8638f9692614c4d91c0922571785c72a0cc23dbe324ab1b06cda250e0ca1bf638c4d6020c5bf5d1d889dff689b4d3289ba1b0c1f171c83d271d0b825aeefecc0b10cbf420cb878838c081e9e727615edfa81e5b9c94761d17ef454d5e68a5864683c61d70b816589046482cc7e5dc7d27df1837d7dec82eb55268ccc50c35429031dbfd87895ca4b7ae4b5edcb52893716471e3b5ede7b174f472c5ccb28c10e9104bfe810d594504faeda03ca40946d21164bbf44bdd37a89b814454d4c785bd84bc4ee77b93562a559841578c4c980652103a6a1320b74cb54248873ad70dad8e523e0a7732
2021-07-27 17:39:18,970 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card size: 7932694528
2021-07-27 17:39:18,970 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card used space: 128282624
2021-07-27 17:39:19,322 [ERROR] [s.w.MainVerticle]: Exception thrown
java.lang.IllegalArgumentException: malformed input off : 16, length : 1
	at java.base/java.lang.StringCoding.throwMalformed(StringCoding.java:698)
	at java.base/java.lang.StringCoding.decodeUTF8_0(StringCoding.java:885)
	at java.base/java.lang.StringCoding.newStringUTF8NoRepl(StringCoding.java:978)
	at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2267)
	at java.base/java.util.zip.ZipCoder$UTF8ZipCoder.toString(ZipCoder.java:208)
	at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:66)
	at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:302)
	at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:124)
	at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
	at studio.webui.service.LibraryService.readPackFile(LibraryService.java:436)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at studio.webui.service.LibraryService.packs(LibraryService.java:99)
	at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	... 30 more



> malformed input off : 16, length : 1: Error 500: malformed input off : 16, length : 1	at java.base/java.lang.StringCoding.throwMalformed(StringCoding.java:698)
	at java.base/java.lang.StringCoding.decodeUTF8_0(StringCoding.java:885)
	at java.base/java.lang.StringCoding.newStringUTF8NoRepl(StringCoding.java:978)
	at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2267)
	at java.base/java.util.zip.ZipCoder$UTF8ZipCoder.toString(ZipCoder.java:208)
	at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:66)
	at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:302)
	at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:124)
	at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
	at studio.webui.service.LibraryService.readPackFile(LibraryService.java:436)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at studio.webui.service.LibraryService.packs(LibraryService.java:99)
	at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)


**Desktop and environment (please complete the following information):**
 - OS: MacIntel
 - Browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:90.0) Gecko/20100101 Firefox/90.0
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.3.0

**Additional info**
I am not into coding... :-)

I imagine that I should empty some cache or so...

**Comment by targyll** [comment]
I spent some more time reading the posts and I found the answer in #141.
Thanks a lot for your tremendous work!

@jullebarge : Si tu n'as pas encore trouvé ta réponse, elle est dans le post #141 
Il te faut effacer le pack GrosFichiers.zip du répertoire `.studio/library` sur ton ordinateur.

Ensuite, si tu souhaites profiter de ce pack d'histoires, tu dois d'abord décompresser "GrosFichiers".zip". Il en contient plusieurs que tu pourras uploader sur la lunii.

**Comment by jullebarge** [comment]
Ok merci, je vais tester cela !

**Comment by sarriagf** [comment]
Bonjour,

Ou est ce repertoire sur windows???

Merci

**Comment by marian-m12l** [comment]
@sarriagf Le répertoire de la bibliothèque locale sous Windows est du type : `C:\Users\utilisateur\.studio\library`. Il me semble qu'il devrait être affiché sur l'interface web même lorsqu'il y a une erreur de lecture des packs d'histoires.

**Comment by albinoskl** [comment]
Bonjour, rencontrant le même problème de récupération des packs dans STUdio j'ai vider le fichier .studio/library
Malheureusement rien n'y fait pour le moment, je ne parviens pas à afficher dans STUdio les fichiers ajouter à la bibliothèque (ceux-ci sont pourtant bien enregistrés depuis STUdio et apparaissent dans le dossier).
Merci pour toute aide de votre part.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
