### ISSUE TITLE
Failed to load/refresh a story

### ISSUE THREAD

**Issue by Lasuede001** [marian-m12l/studio#205]
**Describe the bug**
I don't succeed anymore to load a story or to load the sory library I have

**To Reproduce**
By launching stuodio V3, it don't succeed to load the story library
When I select a story file .zip it can't load it.
I don't know why, it was working yesterday

**Expected behavior**
the library should be full of story

**Screenshots**
if needed I can add screenshots butI think that the log s more intersting , is it enough ?

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> malformed input off : 16, length : 1: Error 500: malformed input off : 16, length : 1	at java.base/java.lang.StringCoding.throwMalformed(StringCoding.java:698)
	at java.base/java.lang.StringCoding.decodeUTF8_0(StringCoding.java:885)
	at java.base/java.lang.StringCoding.newStringUTF8NoRepl(StringCoding.java:978)
	at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2273)
	at java.base/java.util.zip.ZipCoder$UTF8ZipCoder.toString(ZipCoder.java:208)
	at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:66)
	at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:302)
	at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:124)
	at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
	at studio.webui.service.LibraryService.readPackFile(LibraryService.java:436)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at studio.webui.service.LibraryService.packs(LibraryService.java:99)
	at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.3.0

**Additional context**

**Comment by MiekBrantovskii** [comment]
J'ai remarqué ça également, il faut attendre, une quinzaine de minutes et finalement la bibliothèque apparaît...

**Comment by marian-m12l** [comment]
@Lasuede001 Thanks for the feedback. This error generally means that you have an invalid story pack in your local library. Try moving all packs in another folder, and adding packs one by one to identify the culprit.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
