### ISSUE TITLE
STudio ne veut plus démarrer (alors qu'il fonctionnnait très bien), même en le réinstallant

### ISSUE THREAD

**Issue by tromatrikule** [marian-m12l/studio#209]
STudio ne veut plus se lancer alors qu'il fonctionnait très bien jusqu'alors. Je n'ai rien installer ou désinstaller, il ne fonctionne plus alors que 2minutes avant il fonctionnait nickel.

voici le log : 

2021-06-24 15:21:22,063 [ERROR] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:77]: Failed in deploying verticle
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 53 column 38380 path $.79c7addc-67e4-4069-b120-e51200bd2fad.image
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at studio.metadata.DatabaseMetadataService.cleanUnofficialDatabase(DatabaseMetadataService.java:245)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:77)
	at studio.webui.MainVerticle.start(MainVerticle.java:47)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 53 column 38380 path $.79c7addc-67e4-4069-b120-e51200bd2fad.image
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031)
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:702)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 17 more

Je commençais juste de finir une compilation de génériques de dessins animés des années 80's pour mon fils de 4 ans qui adore çà et là impossible d'ouvrir STudio...

Merci par avance...et aussi en retard pour tout le travail accompli.

**Comment by tromatrikule** [comment]
C'est bon...à tout hasard j'ai supprimé le dossier ".studio" de mon compte utilisateur de windows et j'ai relancé...çà fonctionne de nouveau, chouette!!! J'espère que çà pourra aider d'autres personnes.

**Comment by marian-m12l** [comment]
@tromatrikule Merci pour le retour. Effectivement l'erreur devait être due à un pack d'histoires mal formé.
