### ISSUE TITLE
Bug avec le schéma Départ - Action - Stage

### ISSUE THREAD

**Issue by appenzellois** [marian-m12l/studio#212]
Je reprends enfin ma Lunii et j'ai eu quelques succès avec la v0.3.0 et ma Lunii en V2. Merci pour tout ce travail, j'ai pu remettre les albums des kids sur la boîte :-)

Mais, là je ne comprends rien.

J'essaie de faire un truc hyper simple, mais rien n'y fait.
Départ - Action - Stage
J'ai une histoire mp3 à ajouter à la boîte. Aucun embranchement, juste une seule histoire à lancer après sélection dans le menu principal. Diagramme valide.
Une image, un mp3 dans le menu, une image et un mp3 (10mb, 16min) pour l'histoire.
Je l'ai refait plusieurs fois. J'ai changé le format du mp3 de l'histoire (mono : vbr, cbr). aucun résultat.
J'avais une erreur sur la Lunii, mais STUdio me transférait le pack, maintenant, ça coince directement lors du transfert.
J'ai enlevé l'apostrophe du nom du pack et j'ai pu refaire un transfert (j'avais déjà réussi avec l'apostrophe), mais c'est reparti en erreur sur la Lunii.

Pourtant j'ai un autre pack super compliqué qui marche bien (150mb, 5 albums de musiques avec un menu pour les choisir et pour deux d'entre un, la possibilité de passer d'un morceau à l'autre, tandis que les 3 autres c'est juste des gros mp3 des albums complets...). Donc pas une question ni de taille de pack, ni de fichiers.

![error1](https://user-images.githubusercontent.com/64407893/124397299-6b565500-dd0f-11eb-8a22-38c012af4423.png)

Le LOG de quand ça part en erreur au transfert:
----------------------------------------------------------

2021-07-04 21:02:57,109 [INFO ] [s.w.s.LibraryService]: Pack to transfer is in archive format. Converting to FS format and storing in temporary folder: C:\Users\reto\.studio\tmp\Le_Rossignol_de_l'Empereur-58033702-3316-43fc-a65f-8de0a02b98ba-v1.zip1595490092611867959
2021-07-04 21:02:57,109 [INFO ] [s.w.s.LibraryService]: Reading archive format pack
2021-07-04 21:02:57,136 [INFO ] [s.w.s.LibraryService]: Converting assets if necessary
2021-07-04 21:02:57,137 [DEBUG] [s.c.v.u.PackAssetsCompression]: Converting image asset into 4-bits/RLE BMP
2021-07-04 21:02:57,302 [INFO ] [s.w.s.LibraryService]: Writing FS format pack
2021-07-04 21:02:57,487 [INFO ] [s.w.s.LibraryService]: Moving FS format pack into local library: C:\Users\reto\.studio\library\58033702-3316-43fc-a65f-8de0a02b98ba.converted_1625425377487
2021-07-04 21:02:57,516 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Number of packs in index: 3
2021-07-04 21:02:57,517 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: c4139d59-872a-4d15-8cf1-76d34cdf38c6
2021-07-04 21:02:57,518 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 2
2021-07-04 21:02:57,542 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: d489f67b-0e51-4669-b1e1-1555f3c18541
2021-07-04 21:02:57,543 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2021-07-04 21:02:57,551 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 76eff95b-cacf-4993-bcb6-3ae626016e40
2021-07-04 21:02:57,552 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 2
2021-07-04 21:02:57,559 [INFO ] [s.w.s.StoryTellerService]: Transferring pack folder to device: C:\Users\reto\.studio\library\58033702-3316-43fc-a65f-8de0a02b98ba.converted_1625425377487
2021-07-04 21:02:57,568 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Uploading pack to folder: F:\\.content\A02B98BA
2021-07-04 21:02:57,574 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Copying file C:\Users\reto\.studio\library\58033702-3316-43fc-a65f-8de0a02b98ba.converted_1625425377487\li to F:\.content\A02B98BA\li (4 bytes)
2021-07-04 21:02:57,575 [ERROR] [s.w.s.StoryTellerService]: Failed to add pack to device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to copy pack folder
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: studio.driver.StoryTellerException: Failed to copy pack folder
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$copyPackFolder$20(FsStoryTellerAsyncDriver.java:493)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at studio.driver.fs.FsStoryTellerAsyncDriver.copyPackFolder(FsStoryTellerAsyncDriver.java:463)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$uploadPack$12(FsStoryTellerAsyncDriver.java:403)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
        ... 6 more
Caused by: java.nio.file.FileAlreadyExistsException: F:\.content\A02B98BA\li
        at java.base/sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:123)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:283)
        at java.base/java.nio.file.Files.copy(Files.java:1299)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$copyPackFolder$20(FsStoryTellerAsyncDriver.java:474)
        ... 19 more

Le LOG de quand ça transfert (et converti), mais que ça ne marche pas sur la Lunii : 
-------------------------------------------------------------------------------------------
2021-07-04 21:23:53,636 [INFO ] [s.w.s.LibraryService]: Pack to transfer is in archive format. Converting to FS format and storing in temporary folder: C:\Users\reto\.studio\tmp\Le_Rossignol-2bbca1b4-5836-47c3-b32b-d662d1fc591a-v1.zip9318996935244893987
2021-07-04 21:23:53,636 [INFO ] [s.w.s.LibraryService]: Reading archive format pack
2021-07-04 21:23:53,676 [INFO ] [s.w.s.LibraryService]: Converting assets if necessary
2021-07-04 21:23:53,678 [DEBUG] [s.c.v.u.PackAssetsCompression]: Converting image asset into 4-bits/RLE BMP
2021-07-04 21:23:53,870 [DEBUG] [s.c.v.u.ID3Tags]: Removing ID3v2 tag at beginning of file (137 bytes).
2021-07-04 21:23:53,877 [INFO ] [s.w.s.LibraryService]: Writing FS format pack
2021-07-04 21:23:54,046 [INFO ] [s.w.s.LibraryService]: Moving FS format pack into local library: C:\Users\reto\.studio\library\2bbca1b4-5836-47c3-b32b-d662d1fc591a.converted_1625426634046
2021-07-04 21:23:54,070 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Number of packs in index: 3
2021-07-04 21:23:54,075 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: c4139d59-872a-4d15-8cf1-76d34cdf38c6
2021-07-04 21:23:54,076 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 2
2021-07-04 21:23:54,098 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: d489f67b-0e51-4669-b1e1-1555f3c18541
2021-07-04 21:23:54,106 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2021-07-04 21:23:54,112 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 76eff95b-cacf-4993-bcb6-3ae626016e40
2021-07-04 21:23:54,113 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 2
2021-07-04 21:23:54,127 [INFO ] [s.w.s.StoryTellerService]: Transferring pack folder to device: C:\Users\reto\.studio\library\2bbca1b4-5836-47c3-b32b-d662d1fc591a.converted_1625426634046
2021-07-04 21:23:54,132 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Uploading pack to folder: F:\\.content\D1FC591A
2021-07-04 21:23:54,175 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Copying file C:\Users\reto\.studio\library\2bbca1b4-5836-47c3-b32b-d662d1fc591a.converted_1625426634046\li to F:\.content\D1FC591A\li (4 bytes)
2021-07-04 21:23:54,203 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Transferred 4 bytes in 39 ms
2021-07-04 21:23:54,206 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Average speed = 102.56410256410257 bytes/sec
2021-07-04 21:23:54,210 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Copying file C:\Users\reto\.studio\library\2bbca1b4-5836-47c3-b32b-d662d1fc591a.converted_1625426634046\ni to F:\.content\D1FC591A\ni (600 bytes)
2021-07-04 21:23:54,243 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Transferred 604 bytes in 80 ms
2021-07-04 21:23:54,244 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Average speed = 7550.0 bytes/sec
2021-07-04 21:23:54,248 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Creating directory F:\.content\D1FC591A\rf
2021-07-04 21:23:54,277 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Creating directory F:\.content\D1FC591A\rf\000
2021-07-04 21:23:54,294 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Copying file C:\Users\reto\.studio\library\2bbca1b4-5836-47c3-b32b-d662d1fc591a.converted_1625426634046\rf\000\00000000 to F:\.content\D1FC591A\rf\000\00000000 (15536 bytes)
2021-07-04 21:23:54,329 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Transferred 16140 bytes in 166 ms
2021-07-04 21:23:54,331 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Average speed = 97228.9156626506 bytes/sec
2021-07-04 21:23:54,343 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Copying file C:\Users\reto\.studio\library\2bbca1b4-5836-47c3-b32b-d662d1fc591a.converted_1625426634046\ri to F:\.content\D1FC591A\ri (12 bytes)
2021-07-04 21:23:54,383 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Transferred 16152 bytes in 218 ms
2021-07-04 21:23:54,387 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Average speed = 74091.74311926606 bytes/sec
2021-07-04 21:23:54,392 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Creating directory F:\.content\D1FC591A\sf
2021-07-04 21:23:54,411 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Creating directory F:\.content\D1FC591A\sf\000
2021-07-04 21:23:54,426 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Copying file C:\Users\reto\.studio\library\2bbca1b4-5836-47c3-b32b-d662d1fc591a.converted_1625426634046\sf\000\00000000 to F:\.content\D1FC591A\sf\000\00000000 (28636 bytes)
2021-07-04 21:23:54,463 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Transferred 44788 bytes in 300 ms
2021-07-04 21:23:54,463 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Average speed = 149293.33333333334 bytes/sec
2021-07-04 21:23:54,472 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Copying file C:\Users\reto\.studio\library\2bbca1b4-5836-47c3-b32b-d662d1fc591a.converted_1625426634046\sf\000\00000001 to F:\.content\D1FC591A\sf\000\00000001 (10300630 bytes)
2021-07-04 21:23:59,216 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Transferred 10345418 bytes in 5053 ms
2021-07-04 21:23:59,217 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Average speed = 2047381.357609341 bytes/sec
2021-07-04 21:23:59,221 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Copying file C:\Users\reto\.studio\library\2bbca1b4-5836-47c3-b32b-d662d1fc591a.converted_1625426634046\si to F:\.content\D1FC591A\si (24 bytes)
2021-07-04 21:23:59,246 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Transferred 10345442 bytes in 5083 ms
2021-07-04 21:23:59,247 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Average speed = 2035302.380483966 bytes/sec
2021-07-04 21:23:59,254 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Generating device-specific boot file
2021-07-04 21:23:59,258 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Firmware version: 2.5
2021-07-04 21:23:59,259 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Serial Number: 00016180900704
2021-07-04 21:23:59,260 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: UUID: a801ef8175215ae1ae3bedb93a8a15075ce11778ca46398f4163755b7b257086a963cc749e5e7a1c47d3c8c6ca48223e1ceb0fdb068fd73a0dec8c2f22b85e9db3b83b1376c80671a12ad60d2df91b0c4e941400f212d0962f95bb5bff4f25be5dc34d6a35d537f2a2c7180a171b6fc7c8cf8f1eaa253e52d6bc1f80a4b02aa901e97e3d1ac2c8b553b6c5d56ef6df729c4f86646d5bd29ae44e986a9d617b834de3dd9a96f09e5b2eea9cd18979dd43dd72faaeb4248d6db1ffcd117f5fca38f0237e1307a81be2940764470bf2cf9232720b27c23259088efeae5453cd5e21e4f1c14f58cfc2214c6b9b1b526fe740977289956ca28e407f8335671f722273
2021-07-04 21:23:59,261 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card size: 7932694528
2021-07-04 21:23:59,262 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card used space: 259997696
2021-07-04 21:23:59,351 [INFO ] [s.w.s.StoryTellerService]: Pack added.
2021-07-04 21:23:59,374 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Firmware version: 2.5
2021-07-04 21:23:59,375 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Serial Number: 00016180900704
2021-07-04 21:23:59,375 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: UUID: a801ef8175215ae1ae3bedb93a8a15075ce11778ca46398f4163755b7b257086a963cc749e5e7a1c47d3c8c6ca48223e1ceb0fdb068fd73a0dec8c2f22b85e9db3b83b1376c80671a12ad60d2df91b0c4e941400f212d0962f95bb5bff4f25be5dc34d6a35d537f2a2c7180a171b6fc7c8cf8f1eaa253e52d6bc1f80a4b02aa901e97e3d1ac2c8b553b6c5d56ef6df729c4f86646d5bd29ae44e986a9d617b834de3dd9a96f09e5b2eea9cd18979dd43dd72faaeb4248d6db1ffcd117f5fca38f0237e1307a81be2940764470bf2cf9232720b27c23259088efeae5453cd5e21e4f1c14f58cfc2214c6b9b1b526fe740977289956ca28e407f8335671f722273
2021-07-04 21:23:59,380 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card size: 7932694528
2021-07-04 21:23:59,381 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card used space: 260001792
2021-07-04 21:23:59,407 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Number of packs in index: 4
2021-07-04 21:23:59,409 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: c4139d59-872a-4d15-8cf1-76d34cdf38c6
2021-07-04 21:23:59,414 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 2
2021-07-04 21:23:59,429 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: d489f67b-0e51-4669-b1e1-1555f3c18541
2021-07-04 21:23:59,430 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2021-07-04 21:23:59,442 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 76eff95b-cacf-4993-bcb6-3ae626016e40
2021-07-04 21:23:59,443 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 2
2021-07-04 21:23:59,457 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 2bbca1b4-5836-47c3-b32b-d662d1fc591a
2021-07-04 21:23:59,461 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1

**Comment by appenzellois** [comment]
J'ai refait une histoire avec Départ - Menu - Histoire et les mêmes fichiers image et mp3 et là ça marche (sauf que pour le déroulement, il faut appuyer 3 fois sur Ok pour accéder à l'histoire, bref pas très clair pour des enfants)...

**Comment by appenzellois** [comment]
J'arrive à la conclusion que le schéma "Départ - Action - Stage" n'est pas valable.

**Comment by marian-m12l** [comment]
@appenzellois Merci pour le retour détaillé.

Pour le premier log d'erreur, il semble que le pack soit déjà présent dans l'appareil : ` Caused by: java.nio.file.FileAlreadyExistsException: F:.content\A02B98BA\li`. Il y a peut-être eu une erreur lors d'un transfert précédent, ou lors de la suppression du pack sur l'appareil ?

Pour le cas avec les noeuds action/stage, il me semble que ça devrait fonctionner. Quel est le comportement sur la lunii ? En revanche il n'y a ni bouton OK, ni Autoplay sur le dernier noeud, ça risque de poser problème à la fin de la lecture.

**Comment by appenzellois** [comment]
> @appenzellois Merci pour le retour détaillé.
> 
> Pour le premier log d'erreur, il semble que le pack soit déjà présent dans l'appareil : ` Caused by: java.nio.file.FileAlreadyExistsException: F:.content\A02B98BA\li`. Il y a peut-être eu une erreur lors d'un transfert précédent, ou lors de la suppression du pack sur l'appareil ?

C'est possible. Je ne peux pas dire. J'ai fait du nettoyage depuis.

> Pour le cas avec les noeuds action/stage, il me semble que ça devrait fonctionner. Quel est le comportement sur la lunii ?

La Lunii fonctionne, j'ai l'image de la story dans le menu, mais quand je clique OK, il y a le symbole avec le câble, le le PC, la Lunii et le text "ERROR" et c'est le freeze.

> En revanche il n'y a ni bouton OK, ni Autoplay sur le dernier noeud, ça risque de poser problème à la fin de la lecture.

Le comportement que je voulais, c'est qu'une fois l'histoire finie, il faut appuyer sur Home pour revenir au menu. Si je mets un Autoplay ou que j'active le bouton Ok, sans faire de lien le diagramme n'est pas valide (je n'ai aucun autre noeud sur lequel en faire et si je fais le lien sur l'Option #1 du noeud d'Action, j'aurais une boucle sans fin, non?).

Comme alternative j'ai fait comme ça, avec une étape intermédiaire ("Appuie sur Ok pour démarrer l'histoire"). C'est un peu plus lourd.

![error](https://user-images.githubusercontent.com/64407893/124559477-0cdac500-de3c-11eb-9f21-94be2e86be87.png)

Je vais refaire un test ce soir avec Départ - Action - Stage. Je te mettrai le pack à disposition pour debug si ça ne marche pas.

**Comment by gromain** [comment]
Je vois le même problème, impossible de créer une histoire simple. J'ai essayé pas mal de combinaisons, mais rien ne fonctionne à part le Départ - Menu - Histoire (qui est donc super lourd).

**Comment by marian-m12l** [comment]
Effectivement pour revenir au premier noeud après lecture de l'histoire, il faut utiliser un noeud "stage" configuré comme "noeud de départ". Il faudra aussi un noeud d'action pour faire la transition après la lecture de l'histoire (il faut toujours une alternance action-stage).

**Comment by gromain** [comment]
Je ne suis pas sûr de comprendre. J'ai déjà un noeud stage configuré comme noeud de départ, dans ce cas, impossible de relier la sortie d'un noeud d'action au noeud stage en question. Et si je rajoute un noeud stage vide à la fin, je me retrouve dans la même situation que précédemment.

Je pense que c'est quelque chose qu'on pourra ajouter dans la documentation, le "getting started to create a simple story"! C'est pas évident de bien saisir le truc.

**Comment by marian-m12l** [comment]
@gromain Effectivement, il faudrait vérifier sur la lunii mais on ne doit pas pouvoir retourner comme ça au noeud de départ, d'où l'absence de "port" d'entrée sur ces noeuds.
Pour un pack avec une seule histoire, je pense qu'il faudrait ajouter un noeud "stage" du type "recommencer ?", qui permet soit de relire l'histoire avec OK, soit de retourner au menu avec HOME. Quelque chose comme ça :

![graph](https://user-images.githubusercontent.com/50991156/124755550-cc5a7480-df2b-11eb-9e1f-1b6534772227.png)

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
