### ISSUE TITLE
Impossible de transférer un pack

### ISSUE THREAD

**Issue by Vkrauth** [marian-m12l/studio#218]
J'utilise la version 0.3.0 de studio
La simulation du pack est ok
J'ai le dernier firmware et drive à jour luniistore.

Logs de chrome ::
latest pack: {format: "fs", uuid: "f101968e-b67d-4ca1-8ecd-f826b68e7c80", version: 1, path: "f101968e-b67d-4ca1-8ecd-f826b68e7c80.converted_1626081687990", timestamp: 1626081687990, …}description: ""format: "fs"image: nullofficial: falsepath: "f101968e-b67d-4ca1-8ecd-f826b68e7c80.converted_1626081687990"sectorSize: 8timestamp: 1626081687990title: "Rammstein"uuid: "f101968e-b67d-4ca1-8ecd-f826b68e7c80"version: 1__proto__: Object
PackLibrary.js:94 device-compatible pack: {format: "fs", uuid: "f101968e-b67d-4ca1-8ecd-f826b68e7c80", version: 1, path: "f101968e-b67d-4ca1-8ecd-f826b68e7c80.converted_1626081687990", timestamp: 1626081687990, …}description: ""format: "fs"image: nullofficial: falsepath: "f101968e-b67d-4ca1-8ecd-f826b68e7c80.converted_1626081687990"sectorSize: 8timestamp: 1626081687990title: "Rammstein"uuid: "f101968e-b67d-4ca1-8ecd-f826b68e7c80"version: 1__proto__: Object
PackLibrary.js:123 OK, transferring pack:

Logs de la console :+1: 2021-07-12 11:40:25,127 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Number of pack
s in index: 5
2021-07-12 11:40:25,127 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: c41
39d59-872a-4d15-8cf1-76d34cdf38c6
2021-07-12 11:40:25,135 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version:
2
2021-07-12 11:40:25,701 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 9ba
e3327-cc04-4170-8e40-b41b5a8f2a43
2021-07-12 11:40:25,705 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version:
1
2021-07-12 11:40:25,932 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: c47
65b2a-b00d-4060-bfb4-8f083a192a73
2021-07-12 11:40:25,937 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version:
1
2021-07-12 11:40:26,189 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: d48
9f67b-0e51-4669-b1e1-1555f3c18541
2021-07-12 11:40:26,189 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version:
1
2021-07-12 11:40:26,314 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 31d
9978a-6e89-411a-b133-88080bb18d56
2021-07-12 11:40:26,314 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version:
1
2021-07-12 11:40:26,345 [INFO ] [s.w.s.StoryTellerService]: Transferring pack fo
lder to device: C:\Users\Vincent\.studio\library\f101968e-b67d-4ca1-8ecd-f826b68
e7c80.converted_1626081687990
2021-07-12 11:40:26,360 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Uploading pack
 to folder: H:\\.content\B68E7C80
2021-07-12 11:40:26,360 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Creating direc
tory H:\.content\B68E7C80
2021-07-12 11:40:26,360 [ERROR] [s.w.s.StoryTellerService]: Failed to add pack t
o device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Fa
iled to copy pack folder
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Comp
letableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Co
mpletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Comp
letableFuture.java:1766)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Com
pletableFuture.java:1756)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:
295)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Fo
rkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:16
65)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.ja
va:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorke
rThread.java:183)
Caused by: studio.driver.StoryTellerException: Failed to copy pack folder
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$copyPackFolder$20(Fs
StoryTellerAsyncDriver.java:493)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachO
ps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipe
line.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining
(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline
.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractP
ipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Fo
rEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequent
ial(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline
.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipelin
e.java:596)
        at studio.driver.fs.FsStoryTellerAsyncDriver.copyPackFolder(FsStoryTelle
rAsyncDriver.java:463)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$uploadPack$12(FsStor
yTellerAsyncDriver.java:403)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Comp
letableFuture.java:1764)
        ... 6 more
Caused by: java.nio.file.FileSystemException: H:\.content\B68E7C80: M├®dia prot├
®g├® en ├®criture
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsE
xception.java:92)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsExc
eption.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsExc
eption.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(Window
sFileSystemProvider.java:519)
        at java.base/java.nio.file.Files.createDirectory(Files.java:694)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$copyPackFolder$20(Fs
StoryTellerAsyncDriver.java:469)
        ... 19 more
2021-07-12 11:43:52,309 [INFO ] [s.d.LibUsbActivePollingWorker]: Active polling
lost the device. Firing event.
2021-07-12 11:43:52,309 [INFO ] [s.w.s.StoryTellerService]: Device 2.x unplugged

une idée ?

**Comment by Vkrauth** [comment]
Côté driver, j'ai réussi à copier un pack depuis le lunii vers le pc

**Comment by Vkrauth** [comment]
I get no answer. Should I write english ?

**Comment by marian-m12l** [comment]
@Vkrauth Visiblement la partition Luniii est protégée, ce qui empêche d'y copier le pack d'histoires :

> Caused by: java.nio.file.FileSystemException: H:.content\B68E7C80: M├®dia prot├
> ®g├® en ├®criture

Il y a peut-être un réglage à faire du côté de Windows ?

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
