### ISSUE TITLE
Erreur de conversion RAW -> Archive

### ISSUE THREAD

**Issue by alheehooo** [marian-m12l/studio#226]
**Describe the bug**
Bonjour,

Il semble impossible de convertir un pack téléchargé depuis Luniistore :

**To Reproduce**
1. Télécharger un pack depuis le Luniistore ;
2. Renommer le ".pk" en ".pack"
2. Importer le fichier ".pack" dans Studio ;
3. Convertir le pack vers le format "archive" ;

**Expected behavior**

**Screenshots**
<img width="795" alt="Capture d’écran 2021-08-09 à 17 05 33" src="https://user-images.githubusercontent.com/88686317/128769768-b6d5d603-ee1e-4602-8140-eb85d6e0f430.png">

**Logs**

2021-08-09 09:52:42,534 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle
2021-08-09 09:53:04,752 [INFO ] [s.w.s.LibraryService]: Pack is in raw format. Converting to archive format and storing in temporary file: /Users/XXXX/.studio/tmp/c4139d59872a4d158cf176d34cdf38c6.pack12788679101826451402.zip
2021-08-09 09:53:04,754 [INFO ] [s.w.s.LibraryService]: Reading raw format pack
2021-08-09 09:54:33,974 [ERROR] [s.w.s.LibraryService]: Failed to convert raw format pack to archive format
java.io.EOFException
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
	at java.base/java.io.DataInputStream.readLong(DataInputStream.java:420)
	at studio.core.v1.reader.binary.BinaryStoryPackReader.readEnrichedNodeMetadata(BinaryStoryPackReader.java:278)
	at studio.core.v1.reader.binary.BinaryStoryPackReader.read(BinaryStoryPackReader.java:216)
	at studio.webui.service.LibraryService.addConvertedArchivePackFile(LibraryService.java:248)
	at studio.webui.api.LibraryController$3.run(LibraryController.java:114)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Exception in thread "Timer-0" java.lang.RuntimeException: Failed to convert raw format pack to archive format
	at studio.webui.service.LibraryService.addConvertedArchivePackFile(LibraryService.java:269)
	at studio.webui.api.LibraryController$3.run(LibraryController.java:114)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
	at java.base/java.io.DataInputStream.readLong(DataInputStream.java:420)
	at studio.core.v1.reader.binary.BinaryStoryPackReader.readEnrichedNodeMetadata(BinaryStoryPackReader.java:278)
	at studio.core.v1.reader.binary.BinaryStoryPackReader.read(BinaryStoryPackReader.java:216)
	at studio.webui.service.LibraryService.addConvertedArchivePackFile(LibraryService.java:248)
	... 3 more
2021-08-09 10:07:32,621 [ERROR] [s.w.MainVerticle]: Exception thrown 

**Desktop and environment (please complete the following information):**
 - OS: Mac Os X - Catalina - 10.15.7 (19H1217)
 - Browser: Chrome
 - Java version: openjdk 15.0.2 2021-01-19
 - Maven version: N/A
 - STUdio application version: 3.0 (installé depuis la release)

**Additional context**
N/A

Merci beaucoup pour votre super travail !!!

**Comment by marian-m12l** [comment]
@alheehooo Merci pour le retour. Le format ".pk" n'est pas le même que le format ".pack", d'où l'erreur. Pour les packs d'histoires officiels, je recommande d'utiliser l'application officielle Luniistore.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
