### ISSUE TITLE
Error with version 2.22 (recent upgrade of Lunii)

### ISSUE THREAD

**Issue by xounamoun** [marian-m12l/studio#227]
Hi,

I had a bad feeling when I clicked on it but ... on the official Luniistore, an upgrade is proposed for a " night mode ". 

It seems that this new version of the device does not allow STUdio to work properly.

On the 3.0 stabilized version (and same for beta) of STUdio I got the message " Échec de vérification de l'appareil " or a  similar message. 

The message appears when I switch on the Lunii after the USB plug. I precise that I've been using STUdio for a few months now, without any issues.

I copy below the latest log I have. 

`2021-08-09 22:21:03,289 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:53]: Setting up story teller driver
2021-08-09 22:21:03,293 [DEBUG] [studio.driver.raw.RawStoryTellerAsyncDriver] [RawStoryTellerAsyncDriver.java:44]: Registering hotplug listener
2021-08-09 22:21:03,295 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:48]: Initializing libusb...
2021-08-09 22:21:03,301 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:64]: Hotplug is supported. Registering hotplug callback(s)...
2021-08-09 22:21:03,301 [DEBUG] [studio.driver.LibUsbAsyncEventsWorker] [LibUsbAsyncEventsWorker.java:32]: Starting worker thread to handle libusb async events...
2021-08-09 22:21:03,305 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:56]: Registering hotplug listener
2021-08-09 22:21:03,306 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:48]: Initializing libusb...
2021-08-09 22:21:03,307 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:64]: Hotplug is supported. Registering hotplug callback(s)...
2021-08-09 22:21:03,307 [DEBUG] [studio.driver.LibUsbAsyncEventsWorker] [LibUsbAsyncEventsWorker.java:32]: Starting worker thread to handle libusb async events...
2021-08-09 22:21:03,308 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:115]: Hotplug event callback (0483:a341): 1
2021-08-09 22:21:03,311 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:61]: Waiting for device partition...
2021-08-09 22:21:03,391 [INFO ] [studio.webui.MainVerticle] [MainVerticle.java:106]: Opening URL in default browser...
2021-08-09 22:21:03,528 [INFO ] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:81]: Succeeded in deploying verticle
2021-08-09 22:21:03,569 [ERROR] [io.vertx.core.http.impl.HttpServerImpl] [HttpServerImpl.java:307]: java.net.BindException: Address already in use
2021-08-09 22:21:04,341 [INFO ] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:70]: FS device partition located: /media/ayman/LUNII
2021-08-09 22:21:04,342 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:113]: Device 2.x plugged
2021-08-09 22:21:04,351 [ERROR] [studio.webui.service.StoryTellerService] [StoryTellerService.java:118]: Failed to plug device 2.x
studio.driver.StoryTellerException: Unsupported device metadata format version: 3
	at studio.driver.fs.FsStoryTellerAsyncDriver.getDeviceInfos(FsStoryTellerAsyncDriver.java:123)
	at studio.webui.service.StoryTellerService$2.lambda$onDevicePlugged$1(StoryTellerService.java:115)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2021-08-09 22:21:09,803 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:115]: Hotplug event callback (0483:a341): 2
2021-08-09 22:21:09,804 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:144]: Device 2.x unplugged
2021-08-09 22:21:14,523 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:115]: Hotplug event callback (0483:a341): 1
2021-08-09 22:21:14,524 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:61]: Waiting for device partition...
2021-08-09 22:21:16,632 [INFO ] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:70]: FS device partition located: /media/ayman/LUNII
2021-08-09 22:21:16,633 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:113]: Device 2.x plugged
2021-08-09 22:21:16,636 [ERROR] [studio.webui.service.StoryTellerService] [StoryTellerService.java:118]: Failed to plug device 2.x
studio.driver.StoryTellerException: Unsupported device metadata format version: 3
	at studio.driver.fs.FsStoryTellerAsyncDriver.getDeviceInfos(FsStoryTellerAsyncDriver.java:123)
	at studio.webui.service.StoryTellerService$2.lambda$onDevicePlugged$1(StoryTellerService.java:115)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2021-08-09 22:22:04,078 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:115]: Hotplug event callback (0483:a341): 2
2021-08-09 22:22:04,079 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:144]: Device 2.x unplugged
2021-08-09 22:22:13,098 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:115]: Hotplug event callback (0483:a341): 1
2021-08-09 22:22:13,100 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:61]: Waiting for device partition...
2021-08-09 22:22:15,207 [INFO ] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:70]: FS device partition located: /media/ayman/LUNII
2021-08-09 22:22:15,208 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:113]: Device 2.x plugged
2021-08-09 22:22:15,212 [ERROR] [studio.webui.service.StoryTellerService] [StoryTellerService.java:118]: Failed to plug device 2.x
studio.driver.StoryTellerException: Unsupported device metadata format version: 3
	at studio.driver.fs.FsStoryTellerAsyncDriver.getDeviceInfos(FsStoryTellerAsyncDriver.java:123)
	at studio.webui.service.StoryTellerService$2.lambda$onDevicePlugged$1(StoryTellerService.java:115)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)`

I am running on Ubuntu 20.04.

Thanks for any help !

**Comment by gael4910** [comment]
Hello, same probleme with 0.3.0-beta on windows 10, brand new device, but worked since several months with an oldest.

**Comment by truntz** [comment]
Hello, same problem with 0.3.0-beta on Mac OS :)  it looks like every OS is concerned

**Comment by YaKKuZa** [comment]
same problem too with my lunii v1 on the lastest fw.
i wait update , thanks =)

**Comment by marian-m12l** [comment]
@xounamoun @gael4910 @truntz @YaKKuZa Should be fixed with the latest nightly build. Let me know how it goes.

**Comment by marian-m12l** [comment]
New version released with support for firmware 2.7 / 2.22 and basic support for night mode: https://github.com/marian-m12l/studio/releases/tag/0.3.1

**Comment by truntz** [comment]
Big thanks :)

**Comment by xounamoun** [comment]
@marian-m12l it's work perfectly. I cease the occasion to thank you another time, you and the whole community ! I guess you have kids and yet in the middle of August you manage to keep this incredible reactivity :+1:
