### ISSUE TITLE
Failed to refresh library after loading a bad zip file

### ISSUE THREAD

**Issue by wavefrontshaping** [marian-m12l/studio#273]
**Describe the bug**
After I loaded a wrong .zip file by mistake, which was not opened cause it had nothing to do with Lunii, Studiio fails to load my story collection. 
When I reload my library folder or try to create and save a story with the editor, I received a "Failed to refresh library", and the main page displays the sad message "No story packs in library, yet."

**Logs**
>  [ERROR] [s.w.MainVerticle]: Exception thrown
java.lang.NullPointerException
	at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:50)
	at studio.webui.service.LibraryService.readPackFile(LibraryService.java:436)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at studio.webui.service.LibraryService.packs(LibraryService.java:99)
	at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Desktop and environment (please complete the following information):**
 - OS: Linux x86_64
 - Browser Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.3.1

**Additional context**
Thanks for the wonderful tool!

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
