### ISSUE TITLE
Null pointer in usb access

### ISSUE THREAD

**Issue by PierreHanser** [marian-m12l/studio#274]
**Describe the bug**
no access to lunii v1

**To Reproduce**
start lunii
start soft

**Expected behavior**
access to stories inside the box

**Logs**
2022-01-27 13:39:22,275 [WARN ] [s.d.r.RawStoryTellerAsyncDriver]: No UUID in SPI
2022-01-27 13:39:22,275 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: Serial Number: 00020181201868
2022-01-27 13:39:22,279 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: Firmware version: 1.1
2022-01-27 13:39:22,279 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: SD card size: 15403360
2022-01-27 13:39:22,279 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: Error code: 30208
2022-01-27 13:39:22,280 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: Number of packs in index: 1
2022-01-27 13:39:22,280 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: Pack #1: 1 - 1441508
2022-01-27 13:39:22,281 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: Pack version: 1
2022-01-27 13:39:22,281 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: Pack UUID: c4139d59-872a-4d15-8cf1-76d34cdf38c6
2022-01-27 13:39:22,282 [ERROR] [s.w.a.DeviceController]: Failed to read device infos
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:840)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at studio.webui.service.StoryTellerService.lambda$deviceInfosV1$0(StoryTellerService.java:165)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 9 more

**Desktop and environment (please complete the following information):**
 - OS: Linux x86_64
 - Browser Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: ?
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.21.10)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.21.10, mixed mode, sharing)

**Additional context**

**Comment by PierreHanser** [comment]
in fact it was with lunii software 1.1
I upgraded the software with the luniistore and this problem is gone
