### ISSUE TITLE
Could not locate device partition

### ISSUE THREAD

**Issue by kpouget** [marian-m12l/studio#283]
**Describe the bug**

```
Could not locate device partition
```

**To Reproduce**
Plug a recent Lunii (received it today from SAV, brand new)

**Expected behavior**

**Screenshots**

**Logs**
```
Exception: Could not locate device partition
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: studio.driver.StoryTellerException: Could not locate device partition
	at studio.driver.fs.FsStoryTellerAsyncDriver$1.onDevicePlugged(FsStoryTellerAsyncDriver.java:78)
	at studio.driver.LibUsbDetectionHelper.lambda$registerCallback$1(LibUsbDetectionHelper.java:118)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	... 6 more
```

**Desktop and environment (please complete the following information):**

- Linux
- STUdio application version 0.3.1 

**Additional context**

I'm not sure exactly how STUdio is supposed ot detect the Lunii,
I'm mounting it manually (`pmount /dev/sdx1`), then the exception occur.

Looking at the source code, I ended up there:
https://github.com/marian-m12l/studio/blob/e57e58c855260e8514ea1573e3a5f72cc779e4b5/driver/src/main/java/studio/driver/fs/FsStoryTellerAsyncDriver.java#L66

... and worked around the issue with:
```
touch /media/sdx1/.md
``` 
then I restart STUdio, and it works as expected 🤷🏻‍♂️ 

[thanks again for the great work, happy to help troubleshoot this issue :]

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
