### ISSUE TITLE
Echec de l'ajout du pack à l'appreil

### ISSUE THREAD

**Issue by pierrotdu33** [marian-m12l/studio#289]
**Describe the bug**
Bonjour , je n'arrive pas a transferer mes packs sur ma Lunii.
Ceci fonctionnait trés bien jusqu'a présent et maintenant j'obtiens l'erreur "echec de l'ajout du pack à l'appareil". J'ai joins le log. merci 

**Logs**
2022-05-29 19:48:35,301 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:53]: Setting up story teller driver
2022-05-29 19:48:35,317 [DEBUG] [studio.driver.raw.RawStoryTellerAsyncDriver] [RawStoryTellerAsyncDriver.java:44]: Registering hotplug listener
2022-05-29 19:48:35,317 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:48]: Initializing libusb...
2022-05-29 19:48:35,379 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:73]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2022-05-29 19:48:35,379 [DEBUG] [studio.driver.LibUsbAsyncEventsWorker] [LibUsbAsyncEventsWorker.java:32]: Starting worker thread to handle libusb async events...
2022-05-29 19:48:35,395 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:55]: Registering hotplug listener
2022-05-29 19:48:35,395 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:48]: Initializing libusb...
2022-05-29 19:48:35,395 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:73]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2022-05-29 19:48:35,395 [DEBUG] [studio.driver.LibUsbAsyncEventsWorker] [LibUsbAsyncEventsWorker.java:32]: Starting worker thread to handle libusb async events...
2022-05-29 19:48:35,727 [INFO ] [studio.driver.LibUsbActivePollingWorker] [LibUsbActivePollingWorker.java:65]: Active polling found a new device. Firing event.
2022-05-29 19:48:35,743 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:60]: Waiting for device partition...
2022-05-29 19:48:35,790 [INFO ] [studio.webui.MainVerticle] [MainVerticle.java:106]: Opening URL in default browser...
2022-05-29 19:48:36,446 [INFO ] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:81]: Succeeded in deploying verticle
2022-05-29 19:48:36,837 [INFO ] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:69]: FS device partition located: D:\
2022-05-29 19:48:36,837 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:113]: Device 2.x plugged
2022-05-29 19:48:36,962 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:131]: Firmware version: 2.22
2022-05-29 19:48:36,962 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:138]: Serial Number: 9027061620413793
2022-05-29 19:48:37,009 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:148]: UUID: e55803c47ae972369069629baea089a29e00d658d2c37319afa8717b8a593f44f34dac1656278a6c8f319739a3b81ca47d906e8f04164c2b37a5a16fce7f583e857c3db62bc28c6d1b39589f1300d2f608c6682e14263d32a75f92afaa9595243225d051c38ba35f0c13509e06bc13566365b83962064728722871c5f7922837539d31ff73b5885ee9b5b44bc60a2b6dd55531ab11c94eeb8ccb9b7bc213a481d914612ec59b6cd9a69a6990fd249a9ebd73fb187afa4d445acd7f42a6b3c85e7eb7764dcd5c9d2a3617fa3241150e785cc54a889254e7b7958b61b959c1c4e274aed52ee37ce49fb5521a973036b8bfa461f66b4d969a50825fdb08230c6214
2022-05-29 19:48:37,056 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:158]: SD card size: 7939817472
2022-05-29 19:48:37,087 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:159]: SD card used space: 269385728
2022-05-29 19:48:41,172 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:131]: Firmware version: 2.22
2022-05-29 19:48:41,177 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:138]: Serial Number: 9027061620413793
2022-05-29 19:48:41,189 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:148]: UUID: e55803c47ae972369069629baea089a29e00d658d2c37319afa8717b8a593f44f34dac1656278a6c8f319739a3b81ca47d906e8f04164c2b37a5a16fce7f583e857c3db62bc28c6d1b39589f1300d2f608c6682e14263d32a75f92afaa9595243225d051c38ba35f0c13509e06bc13566365b83962064728722871c5f7922837539d31ff73b5885ee9b5b44bc60a2b6dd55531ab11c94eeb8ccb9b7bc213a481d914612ec59b6cd9a69a6990fd249a9ebd73fb187afa4d445acd7f42a6b3c85e7eb7764dcd5c9d2a3617fa3241150e785cc54a889254e7b7958b61b959c1c4e274aed52ee37ce49fb5521a973036b8bfa461f66b4d969a50825fdb08230c6214
2022-05-29 19:48:41,196 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:158]: SD card size: 7939817472
2022-05-29 19:48:41,202 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:159]: SD card used space: 269385728
2022-05-29 19:48:41,924 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:192]: Number of packs in index: 2
2022-05-29 19:48:41,939 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:197]: Pack UUID: c4139d59-872a-4d15-8cf1-76d34cdf38c6
2022-05-29 19:48:41,960 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:211]: Pack version: 2
2022-05-29 19:48:42,121 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:197]: Pack UUID: d489f67b-0e51-4669-b1e1-1555f3c18541
2022-05-29 19:48:42,132 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:211]: Pack version: 1
2022-05-29 19:50:00,425 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:192]: Number of packs in index: 2
2022-05-29 19:50:00,430 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:197]: Pack UUID: c4139d59-872a-4d15-8cf1-76d34cdf38c6
2022-05-29 19:50:00,434 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:211]: Pack version: 2
2022-05-29 19:50:00,486 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:197]: Pack UUID: d489f67b-0e51-4669-b1e1-1555f3c18541
2022-05-29 19:50:00,490 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:211]: Pack version: 1
2022-05-29 19:50:00,506 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:306]: Transferring pack folder to device: C:\Users\pierre\.studio\library\f78a860f-00bd-4bb3-a2c8-182344d6c2a7.converted_1653839350858
2022-05-29 19:50:00,528 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:397]: Uploading pack to folder: D:\\.content\44D6C2A7
2022-05-29 19:50:00,572 [TRACE] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:475]: Copying file C:\Users\pierre\.studio\library\f78a860f-00bd-4bb3-a2c8-182344d6c2a7.converted_1653839350858\li to D:\.content\44D6C2A7\li (60 bytes)
2022-05-29 19:50:00,577 [ERROR] [studio.webui.service.StoryTellerService] [StoryTellerService.java:323]: Failed to add pack to device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to copy pack folder
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: studio.driver.StoryTellerException: Failed to copy pack folder
	at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$copyPackFolder$20(FsStoryTellerAsyncDriver.java:495)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at studio.driver.fs.FsStoryTellerAsyncDriver.copyPackFolder(FsStoryTellerAsyncDriver.java:465)
	at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$uploadPack$12(FsStoryTellerAsyncDriver.java:405)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more
Caused by: java.nio.file.FileAlreadyExistsException: D:\.content\44D6C2A7\li
	at java.base/sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:124)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:284)
	at java.base/java.nio.file.Files.copy(Files.java:1305)
	at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$copyPackFolder$20(FsStoryTellerAsyncDriver.java:476)
	... 19 more

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.3.1

**Additional context**

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
