### ISSUE TITLE
error for installation STUdio on Mac Os

### ISSUE THREAD

**Issue by dimgod59** [marian-m12l/studio#291]
Hello, 
I can't install STUdio on MacOs. (OS X el capitan / mac core 2duo
I downloaded the studio web ui 3.1 folder
Installed Java 8, installed Jdk 18.

when I run studio-macos.sh with the terminal I get an error Unsupported major.minor version52 that I can't understand.
therefore impossible to do the localhost:8080 :(

Terminal : 

/Applications/studio-web-ui-0.3.1/studio-macos.sh; exit;
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/vertx/core/Launcher: Unsupported major.minor version 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Operation completed]

Please help me :)

**Comment by kevinvennitti** [comment]
Hi! Have you tried this? 
https://github.com/marian-m12l/studio/issues/244#issuecomment-1138296165

**Comment by dimgod59** [comment]
No, i tried and succès to windows pc ...

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
