### ISSUE TITLE
Failed to launch studio-web-ui

### ISSUE THREAD

**Issue by maymay37** [marian-m12l/studio#297]
**Describe the bug**
Can't launch studio-web-ui on windows

**To Reproduce**
I download studio-web-ui-0.3.1-dist.zip and unzip this file
Then I launch studio-windows.bat but it crashes some error
Same issue with previous version of studio-web-ui.

Note I used to create some histories on my previous Lunii with studi-web-ui without any problems: it worked well
But for HW issue, I changed my Lunii and so I tried to add same histories than the previous one
I didn't launch studio-web-ui for a long time at this moment. And when I tried, this problem has occured with same version I was working  before. I downloaded more recent version, but same problem.

Is there a configuration file to update?

**Expected behavior**

**Screenshots**

**Logs**
./studio-windows.bat
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 43 column 1518242 path $.14e4d427-0f07-481e-a77d-1d4efacec5eb.image
        at com.google.gson.internal.Streams.parse(Streams.java:60)
        at com.google.gson.JsonParser.parse(JsonParser.java:84)
        at com.google.gson.JsonParser.parse(JsonParser.java:59)
        at studio.metadata.DatabaseMetadataService.cleanUnofficialDatabase(DatabaseMetadataService.java:171)
        at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:63)
        at studio.webui.MainVerticle.start(MainVerticle.java:47)
        at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
        at io.vertx.core.Verticle.start(Verticle.java:66)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 43 column 1518242 path $.14e4d427-0f07-481e-a77d-1d4efacec5eb.image
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031)
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:702)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
        at com.google.gson.internal.Streams.parse(Streams.java:48)
        ... 17 more
2022-07-06 16:04:17,261 [ERROR] [i.v.c.i.l.c.VertxIsolatedDeployer]: Failed in deploying verticle

**Desktop and environment (please complete the following information):**
 - OS: windows10

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
