### ISSUE TITLE
Failed to load packs

### ISSUE THREAD

**Issue by BrunoCrFr** [marian-m12l/studio#300]
**Describe the bug**
Cannot get officials packs loaded on a Lunii (French, V1, fw 2.7)

**To Reproduce**
1. Launch studio
2. Error "Échec de la récupération des packs d'histoires de l'appareil."

**Expected behavior**
Studio should get the packs on the Lunii

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> Internal Server Error: Error 500: Internal Server Error	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.3.1

**Additional context**

2022-07-23 16:50:29,302 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card size: 7932694528
2022-07-23 16:50:29,306 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card used space: 1861210112
2022-07-23 16:50:30,798 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Firmware version: 2.7
2022-07-23 16:50:30,811 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Serial Number: 0************4
2022-07-23 16:50:30,814 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: UUID: 5**************************************************************************************************************************************************************************************************************************************************************************************************************************************************7
2022-07-23 16:50:30,817 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card size: 7932694528
2022-07-23 16:50:30,818 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card used space: 1861210112
2022-07-23 16:50:31,302 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Number of packs in index: 39
2022-07-23 16:50:31,310 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: c4139d59-872a-4d15-8cf1-76d34cdf38c6
2022-07-23 16:50:31,318 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 2
2022-07-23 16:50:31,349 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 6450ff5b-4cb1-4748-a847-5faba29be557
2022-07-23 16:50:31,364 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,408 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: be8949f6-0d85-4f54-8284-19a1bdaed36a
2022-07-23 16:50:31,415 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,426 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 104e310b-6d9d-4005-9960-5cc021e46155
2022-07-23 16:50:31,427 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,433 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: f3b887cb-6caf-4f2a-8242-154239383ad7
2022-07-23 16:50:31,434 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,468 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: ef541f96-fd23-4071-9759-dc1c930c5df4
2022-07-23 16:50:31,471 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,475 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 78ac7aea-cd3a-4b37-add4-697f61b32be1
2022-07-23 16:50:31,477 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,483 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 1076a5fd-2111-4cbc-ad9f-efc18d860336
2022-07-23 16:50:31,485 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,493 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: a1bd13a1-6694-4435-8e5d-40d655c57136
2022-07-23 16:50:31,494 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,498 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: d24e9ff7-80bf-4774-9bf2-01208a0be301
2022-07-23 16:50:31,500 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,509 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: e07c3196-e26a-41dc-93e6-a6b45cf5cfbb
2022-07-23 16:50:31,510 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,517 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: f676e912-21a3-4fff-95f2-d4f6b941eee2
2022-07-23 16:50:31,519 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,530 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: fb2b7df4-be3f-4998-83f0-bfbbda75b9d7
2022-07-23 16:50:31,533 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,541 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: ffb867e6-92ca-434e-be73-ff1c9789f148
2022-07-23 16:50:31,543 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,549 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: bd3d1a7a-9afb-48dd-881a-9375f96378a2
2022-07-23 16:50:31,551 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,558 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 17d39672-8e82-428d-8054-a903d1cd56c9
2022-07-23 16:50:31,560 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,564 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 3ade5403-0625-4fff-a22b-9025ac3678d9
2022-07-23 16:50:31,565 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,574 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 73a1d8af-457b-43d9-9e58-22e490ea75ba
2022-07-23 16:50:31,575 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,579 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: ccd0b1c2-5030-4c13-824a-ba6fa064a178
2022-07-23 16:50:31,580 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,586 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 2eec0b38-2cbd-4812-9621-8b157918bfa4
2022-07-23 16:50:31,589 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,595 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 955b9427-cd09-40f1-b729-c3c6f6399fee
2022-07-23 16:50:31,596 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,624 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: f57d70d2-d397-45e8-a0a8-3907924f89fe
2022-07-23 16:50:31,625 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,630 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 03933ba4-4fbf-475f-9ecc-35efb4d11dc9
2022-07-23 16:50:31,631 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,639 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 588130df-61c6-46ee-af95-017d9823734f
2022-07-23 16:50:31,640 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,647 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 22edd8d2-a599-4eec-aeae-3d6a40be0fa7
2022-07-23 16:50:31,648 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2022-07-23 16:50:31,657 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 22137b29-8646-4335-8069-4a4c9a2d7e89
2022-07-23 16:50:31,659 [ERROR] [s.w.a.DeviceController]: Failed to read packs from device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack metadata on device partition
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: studio.driver.StoryTellerException: Failed to read pack metadata on device partition
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$getPacksList$0(FsStoryTellerAsyncDriver.java:225)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        ... 8 more
Caused by: java.io.FileNotFoundException: D:\.content\9A2D7E89\ni (Le chemin dÔÇÖacc├¿s sp├®cifi├® est introuvable)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$getPacksList$0(FsStoryTellerAsyncDriver.java:206)
        ... 9 more
2022-07-23 16:50:31,663 [ERROR] [s.w.MainVerticle]: Exception thrown
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack metadata on device partition
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: studio.driver.StoryTellerException: Failed to read pack metadata on device partition
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$getPacksList$0(FsStoryTellerAsyncDriver.java:225)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        ... 8 more
Caused by: java.io.FileNotFoundException: D:\.content\9A2D7E89\ni (Le chemin dÔÇÖacc├¿s sp├®cifi├® est introuvable)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$getPacksList$0(FsStoryTellerAsyncDriver.java:206
![Capture d’écran 2022-07-23 165713](https://user-images.githubusercontent.com/25054951/180610494-d2b15733-3f51-4ffe-bcb1-f4992162a655.png))
)

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
