### ISSUE TITLE
Device not detected when recently reset with the latest luniistore version - Could not locate device partition

### ISSUE THREAD

**Issue by arnaudruffin** [marian-m12l/studio#327]
**Describe the bug**
A recently reset device (lunii v2) is not detected by Studio. The GUI doesn't show any error and the logs show a "Could not locate device partition" stacktrace (see more below)

**I have a second device available (lunii v1) that is still correctly detected.** So this is not a configuration issue.

The device that is not detected **was still detected two weeks ago.** In the meantime:
- I reset that device
- I upgraded my OS version

**To Reproduce**
1. Go to lunii store, reset a device
2. Quit store, restart device, restart computer
3. Start studio
4. See that the device is not detected

**Expected behavior**
The device should be detected

**Logs**
```

2022-11-17 13:56:20,043 [INFO ] [s.w.MainVerticle]: Opening URL in default browser...
2022-11-17 13:56:20,376 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle
2022-11-17 13:56:30,187 [ERROR] [s.d.LibUsbDetectionHelper]: An error occurred while handling device plug event
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Could not locate device partition
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: studio.driver.StoryTellerException: Could not locate device partition
	at studio.driver.fs.FsStoryTellerAsyncDriver$1.onDevicePlugged(FsStoryTellerAsyncDriver.java:78)
	at studio.driver.LibUsbDetectionHelper.lambda$registerCallback$1(LibUsbDetectionHelper.java:118)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	... 6 more
```

**Desktop and environment (please complete the following information):**
 - OS:  mac osX 13.0.1
 - Browser: all
 - Java version: zulu 11
 - Maven version: 3.8.4
 - STUdio application version 0.3.1

**Additional context**
I can see a difference between my two devices at the partitioning level. I don't know if this difference is due a recent change in luuni reset procedure or if it is due to being from two hardware with different versions (V1 vs V2)

The failing one is the first
```
/dev/disk4 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *7.9 GB     disk4
   1:                 DOS_FAT_32 LUNII                   7.9 GB     disk4s1

/dev/disk6 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                            LUNII                  *7.9 GB     disk6

```

**Comment by campafap** [comment]
I have the same issue...
My problem appears after Upgrading to OSX 13... Please contact me if you find a solution, i'll do the same for U.

**Comment by matsube11** [comment]
Have you tried the following, edit your studio-macos.sh file and add the following:
`FS_MOUNTPOINT="/dev/disk4s1"`
Add this line at the beginning, of course you have to specify the partition corresponding to your Lumii.

**Comment by campafap** [comment]
Thank, but ... What program can i use to add this line ?

**Comment by campafap** [comment]
i put this line with textedit ... Sorry i'm so a begginer 

i still have this : 

2022-11-30 22:20:51,521 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2022-11-30 22:20:51,521 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug event callback (0c45:6840): 1
2022-11-30 22:20:51,524 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Waiting for device partition...
2022-11-30 22:20:51,604 [INFO ] [s.w.MainVerticle]: Opening URL in default browser...
2022-11-30 22:20:51,822 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle
2022-11-30 22:21:01,630 [ERROR] [s.d.LibUsbDetectionHelper]: An error occurred while handling device plug event
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Could not locate device partition
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1803)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: studio.driver.StoryTellerException: Could not locate device partition
	at studio.driver.fs.FsStoryTellerAsyncDriver$1.onDevicePlugged(FsStoryTellerAsyncDriver.java:78)
	at studio.driver.LibUsbDetectionHelper.lambda$registerCallback$1(LibUsbDetectionHelper.java:118)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
	... 6 more

**Comment by Tolf1** [comment]
Même problème pour moi sur MacOS 13.0.1 avec une Lunii V2 (USB-C).
Je suis toujours bloqué, ajouter la ligne `FS_MOUNTPOINT` ne résout pas le problème.

En attendant la correction du bug, quelqu'un a réussi à contourner le problème ?

**Comment by gilles6** [comment]
Same problem here.

`mount` shows the following:
```
$ mount
/dev/disk1s1s1 on / (apfs, sealed, local, read-only, journaled)
devfs on /dev (devfs, local, nobrowse)
/dev/disk1s3 on /System/Volumes/Preboot (apfs, local, journaled, nobrowse)
/dev/disk1s5 on /System/Volumes/VM (apfs, local, noexec, journaled, noatime, nobrowse)
/dev/disk1s6 on /System/Volumes/Update (apfs, local, journaled, nobrowse)
/dev/disk1s2 on /System/Volumes/Data (apfs, local, journaled, nobrowse)
map auto_home on /System/Volumes/Data/home (autofs, automounted, nobrowse)
msdos://disk2/LUNII on /Volumes/LUNII (lifs, local, nodev, nosuid, noowners, noatime)
```

**Comment by veetrop** [comment]
J'ai le même problème avec un Mac sur lequel j'ai mis le MacOs Ventura 13.1
Y a-t-il un moyen de reconnaître ma Lumi sur un ancien OS ou sur Windows selon vous ?
N'étant pas programmeur, ni américain, êtes vous dans le même cas que moi en France ?
Merci à la communauté !
I have the same problem with a Mac on which I put the MacOs Ventura 13.1
Is there a way to recognize my Lumi on an older OS or on Windows according to you?
Not being a programmer, nor American, are you in the same case as me in France?
Thanks to the community !

**Comment by benjaminalhadef** [comment]
oui ça marche sur ma partition Windows de mon mac.

**Comment by veetrop** [comment]
> oui ça marche sur ma partition Windows de mon mac.

Merci de l'info. Quelle est ta config? (pour essayer de la reproduire)

**Comment by veetrop** [comment]
> J'ai mis Windows 10 avec Bootcamp mais c'est le marteau pour écraser la mouche. Hâte d'avoir un fix sur mac.

Merci, on se tient au courant si effectivement ça s'améliore sous Mac Ventura !

**Comment by yageek** [comment]
Je suis tombé la [dessus](https://threedots.ovh/blog/2022/06/quick-look-at-user-mode-file-systems-on-macos-ventura/) et j'ai réussi à faire quelque chose avec une lunii première génération sur Ventura.

On commence par brancher la lunii et on attends de voir le disque dans Finder

On ouvre le terminal et on utilise `mount` pour trouver la partition déjà monter en mode utilisateur par Ventura:

```sh
$ mount
/dev/disk1s5s1 on / (apfs, sealed, local, read-only, journaled)
...
msdos://disk2/LUNII on /Volumes/LUNII (lifs, local, nodev, nosuid, noowners, noatime) # ici
```

On la retire du système:

```sh
sudo diskutil unmount "/Volumes/LUNII"
```

Et on la remonte manuellement (en monde non utilisateur j'imagine)

```sh
mkdir ~/lunii # Creation d'un dossier pour le montage
sudo mount -t msdos /dev/disk2 ~/lunii
```

Ensuite on lance le studio. On devrait voir la lunii.

Une fois terminer, on démonte le tout

```sh
 sudo umount ~/lunii
```
