### ISSUE TITLE
Failed to read pack index on device partition

### ISSUE THREAD

**Issue by CStan77** [marian-m12l/studio#344]
**Describe the bug**
Impossible to recover the lunii packs

**Screenshots**
![image](https://user-images.githubusercontent.com/72907176/213546010-c4cbad17-bc8c-45af-a9e1-cede28792038.png)

correctly recognized under windows
![image](https://user-images.githubusercontent.com/72907176/213546832-cc24393d-ab6c-473a-a59f-d42a6ba19db2.png)

not recognized under Luniistore
![image](https://user-images.githubusercontent.com/72907176/213546998-1071affd-58eb-4800-857c-09e6e5352a18.png)

**Logs**
2023-01-19 20:18:50,336 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card size: 7939817472
2023-01-19 20:18:50,336 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card used space: 160137216
2023-01-19 20:18:51,277 [ERROR] [s.w.a.DeviceController]: Failed to read packs from device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:251)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 1 more
Caused by: java.io.IOException: Le fichier ou le r├⌐pertoire est endommag├⌐ et illisible
        at java.base/java.io.FileInputStream.readBytes(Native Method)
        at java.base/java.io.FileInputStream.read(FileInputStream.java:269)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:240)
        ... 2 more
2023-01-19 20:18:51,311 [ERROR] [s.w.MainVerticle]: Exception thrown
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:251)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 1 more
Caused by: java.io.IOException: Le fichier ou le r├⌐pertoire est endommag├⌐ et illisible
        at java.base/java.io.FileInputStream.readBytes(Native Method)
        at java.base/java.io.FileInputStream.read(FileInputStream.java:269)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:240)
        ... 2 more
2023-01-19 20:19:01,723 [ERROR] [s.w.a.EvergreenController]: Failed to get latest release
2023-01-19 20:19:01,731 [ERROR] [s.w.MainVerticle]: Exception thrown
java.net.UnknownHostException: H├┤te inconnu (api.github.com)
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:52)
        at java.base/java.net.InetAddress$PlatformResolver.lookupByName(InetAddress.java:1059)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1673)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1003)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1663)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1528)
        at java.base/java.net.InetAddress.getByName(InetAddress.java:1413)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
        at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:162)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
        at io.vertx.core.net.impl.ChannelProvider.handleConnect(ChannelProvider.java:140)
        at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:93)
        at io.vertx.core.http.impl.HttpChannelConnector.doConnect(HttpChannelConnector.java:166)
        at io.vertx.core.http.impl.HttpChannelConnector.connect(HttpChannelConnector.java:100)
        at io.vertx.core.http.impl.pool.Pool$Holder.connect(Pool.java:126)
        at io.vertx.core.http.impl.pool.Pool.checkPendingTasks(Pool.java:256)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1589)
2023-01-19 20:19:23,799 [INFO ] [s.d.LibUsbActivePollingWorker]: Active polling lost the device. Firing event.
2023-01-19 20:35:33,780 [INFO ] [s.d.LibUsbActivePollingWorker]: Active polling found a new device. Firing event.
2023-01-19 20:35:33,783 [INFO ] [s.w.s.StoryTellerService]: Device 2.x unplugged
2023-01-19 20:35:33,789 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Waiting for device partition...
2023-01-19 20:35:34,997 [INFO ] [s.d.f.FsStoryTellerAsyncDriver]: FS device partition located: E:\
2023-01-19 20:35:35,019 [INFO ] [s.w.s.StoryTellerService]: Device 2.x plugged
2023-01-19 20:35:35,029 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Firmware version: 2.22
2023-01-19 20:35:35,029 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Serial Number: 9115090199516560
2023-01-19 20:35:35,029 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: UUID: 56a71bd18528ec392a958b7365f2506321e56ce24206750753dadc59b118ec8f433421508ba3d9b3f6961e2f0ff45c738cebe948344d83ff5ebd91d17ad48ee98c1c4cc18cbf2b9f83a9a2f09f4f8102c008d7069a058f7a85880d0971f58c136dbf99f08cddc7e59376efe5170b9cbffce1f81d175cefbd86632912945f49ba8d98c01ab37febf65f48a0b39d0ac3478e3354de5a5784e353bfa1fa99da9a6dca81ec574c1a6cfb6d5c592fcec76fdb452f30d395bc6daa6cd74c4c05ec361f92dc648e2e868531cc3a89a48862cd73094a4d32432e7d12a0c3e812df7cabf2ba9262c7272c224937dc5e4d06ec3bb9e3340faa6e8a8f142ec999bc6d51c4eb
2023-01-19 20:35:35,033 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card size: 7939817472
2023-01-19 20:35:35,033 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card used space: 160137216
2023-01-19 20:35:45,575 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Firmware version: 2.22
2023-01-19 20:35:45,585 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Serial Number: 9115090199516560
2023-01-19 20:35:45,588 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: UUID: 56a71bd18528ec392a958b7365f2506321e56ce24206750753dadc59b118ec8f433421508ba3d9b3f6961e2f0ff45c738cebe948344d83ff5ebd91d17ad48ee98c1c4cc18cbf2b9f83a9a2f09f4f8102c008d7069a058f7a85880d0971f58c136dbf99f08cddc7e59376efe5170b9cbffce1f81d175cefbd86632912945f49ba8d98c01ab37febf65f48a0b39d0ac3478e3354de5a5784e353bfa1fa99da9a6dca81ec574c1a6cfb6d5c592fcec76fdb452f30d395bc6daa6cd74c4c05ec361f92dc648e2e868531cc3a89a48862cd73094a4d32432e7d12a0c3e812df7cabf2ba9262c7272c224937dc5e4d06ec3bb9e3340faa6e8a8f142ec999bc6d51c4eb
2023-01-19 20:35:45,589 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card size: 7939817472
2023-01-19 20:35:45,589 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card used space: 160137216
2023-01-19 20:35:45,795 [ERROR] [s.w.a.DeviceController]: Failed to read packs from device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: **Failed to read pack index on device partition**
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:251)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 1 more
Caused by: java.io.IOException: **Le fichier ou le r├⌐pertoire est endommag├⌐ et illisible**
        at java.base/java.io.FileInputStream.readBytes(Native Method)
        at java.base/java.io.FileInputStream.read(FileInputStream.java:269)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:240)
        ... 2 more
2023-01-19 20:35:45,798 [ERROR] [s.w.MainVerticle]: Exception thrown
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:251)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 1 more
Caused by: java.io.IOException: Le fichier ou le r├⌐pertoire est endommag├⌐ et illisible
        at java.base/java.io.FileInputStream.readBytes(Native Method)
        at java.base/java.io.FileInputStream.read(FileInputStream.java:269)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:240)
        ... 2 more
2023-01-19 20:44:26,977 [ERROR] [s.w.a.DeviceController]: Failed to transfer pack to device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:251)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 1 more
Caused by: java.io.IOException: Le fichier ou le r├⌐pertoire est endommag├⌐ et illisible
        at java.base/java.io.FileInputStream.readBytes(Native Method)
        at java.base/java.io.FileInputStream.read(FileInputStream.java:269)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:240)
        ... 2 more
2023-01-19 20:45:03,093 [ERROR] [s.w.MainVerticle]: Exception thrown
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:251)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 1 more
Caused by: java.io.IOException: Le fichier ou le r├⌐pertoire est endommag├⌐ et illisible
        at java.base/java.io.FileInputStream.readBytes(Native Method)
        at java.base/java.io.FileInputStream.read(FileInputStream.java:269)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:240)
        ... 2 more

**Desktop and environment (please complete the following information):**
 - OS: Windows10 x64
 - Browser Microsoft Edge Version 109.0.1518.55
 - Java version: jdk-19_windows-x64
 - STUdio application version: 0.3.1

**Comment by BaseZoubru** [comment]
Hello, j'ai le même problème :-(

**Comment by BaseZoubru** [comment]
Vas voir mon post, j'ai résolu, fais un chkdsk de ta card sd lunii ensuite fais comme moi

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
