### ISSUE TITLE
Failed to add pack to device

### ISSUE THREAD

**Issue by YundoRocket** [marian-m12l/studio#350]
**Describe the bug**
J'ai téléchargé le pack de 13 histoires, j'ai créé le story pack et ajouté les histoires. J'ai ensuite enregistré et jusque là tout va bien. 

Mais ensuite au moment ou je glisse le story pack de 13 histoires dans device il est bien converti mais ensuite une erreur apparait: "Failed to add pack to device."

Voici ce qui apparait dans le terminal:

2023-02-27 14:01:53,578 [ERROR] [s.w.s.StoryTellerService]: Failed to add pack to device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to copy pack folder
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: studio.driver.StoryTellerException: Failed to copy pack folder
	at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$copyPackFolder$20(FsStoryTellerAsyncDriver.java:495)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at studio.driver.fs.FsStoryTellerAsyncDriver.copyPackFolder(FsStoryTellerAsyncDriver.java:465)
	at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$uploadPack$12(FsStoryTellerAsyncDriver.java:405)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more
Caused by: java.nio.file.FileAlreadyExistsException: /Volumes/LUNII/.content/8D2C32C1/ni
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:577)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:257)
	at java.base/java.nio.file.Files.copy(Files.java:1304)
	at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$copyPackFolder$20(FsStoryTellerAsyncDriver.java:476)
	... 19 more

**Comment by AnthonyLeDu** [comment]
Merci pour le conseil @RoRoStar. C'est une erreur que j'ai de façon récurrente : le pack n'apparait pas à gauche mais est présent sur le storage et donc cela empêche le téléversement.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
