### ISSUE TITLE
fail to remove folder

### ISSUE THREAD

**Issue by daupalx** [marian-m12l/studio#362]
I fail to remove a file and also all my attempts to convert it in v2.x failed

To help you the log said that:
2023-04-13 00:01:59,698 [ERROR] [s.w.s.LibraryService]: Failed to convert archive format pack to FS format
java.lang.ArrayIndexOutOfBoundsException: Index 15 out of bounds for length 15
        at javazoom.jl.decoder.LayerIDecoder$SubbandLayer1Stereo.read_allocation(LayerIDecoder.java:396)
        at javazoom.jl.decoder.LayerIDecoder.readAllocation(LayerIDecoder.java:108)
        at javazoom.jl.decoder.LayerIDecoder.decodeFrame(LayerIDecoder.java:72)
        at javazoom.jl.decoder.Decoder.decodeFrame(Decoder.java:147)
        at javazoom.spi.mpeg.sampled.convert.DecodedMpegAudioInputStream.execute(DecodedMpegAudioInputStream.java:185)
        at org.tritonus.share.TCircularBuffer.read(TCircularBuffer.java:138)
        at org.tritonus.share.sampled.convert.TAsynchronousFilteredAudioInputStream.read(TAsynchronousFilteredAudioInputStream.java:197)
        at java.desktop/com.sun.media.sound.AudioFloatInputStream$DirectAudioFloatInputStream.read(AudioFloatInputStream.java:191)
        at java.desktop/com.sun.media.sound.AudioFloatFormatConverter$AudioFloatInputStreamChannelMixer.read(AudioFloatFormatConverter.java:187)
        at java.desktop/com.sun.media.sound.AudioFloatFormatConverter$AudioFloatInputStreamResampler.readNextBuffer(AudioFloatFormatConverter.java:384)
        at java.desktop/com.sun.media.sound.AudioFloatFormatConverter$AudioFloatInputStreamResampler.read(AudioFloatFormatConverter.java:423)
        at java.desktop/com.sun.media.sound.AudioFloatFormatConverter$AudioFloatFormatConverterInputStream.read(AudioFloatFormatConverter.java:81)
        at java.desktop/javax.sound.sampled.AudioInputStream.read(AudioInputStream.java:284)
        at java.desktop/com.sun.media.sound.AudioFloatInputStream$DirectAudioFloatInputStream.read(AudioFloatInputStream.java:191)
        at java.desktop/com.sun.media.sound.AudioFloatInputStream.read(AudioFloatInputStream.java:278)
        at java.desktop/com.sun.media.sound.AudioFloatFormatConverter$AudioFloatInputStreamResampler.readNextBuffer(AudioFloatFormatConverter.java:381)
        at java.desktop/com.sun.media.sound.AudioFloatFormatConverter$AudioFloatInputStreamResampler.read(AudioFloatFormatConverter.java:423)
        at java.desktop/com.sun.media.sound.AudioFloatFormatConverter$AudioFloatFormatConverterInputStream.read(AudioFloatFormatConverter.java:81)
        at java.desktop/javax.sound.sampled.AudioInputStream.read(AudioInputStream.java:284)
        at java.desktop/javax.sound.sampled.AudioInputStream.read(AudioInputStream.java:226)
        at studio.core.v1.utils.AudioConversion.anyToMp3(AudioConversion.java:137)
        at studio.core.v1.utils.PackAssetsCompression.withPreparedAssetsFirmware2dot4(PackAssetsCompression.java:186)
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:318)
        at studio.webui.api.LibraryController$2.run(LibraryController.java:102)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
Exception in thread "Timer-0" java.lang.RuntimeException: Failed to convert archive format pack to FS format
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:332)
        at studio.webui.api.LibraryController$2.run(LibraryController.java:102)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 15 out of bounds for length 15
        at javazoom.jl.decoder.LayerIDecoder$SubbandLayer1Stereo.read_allocation(LayerIDecoder.java:396)
        at javazoom.jl.decoder.LayerIDecoder.readAllocation(LayerIDecoder.java:108)
        at javazoom.jl.decoder.LayerIDecoder.decodeFrame(LayerIDecoder.java:72)
        at javazoom.jl.decoder.Decoder.decodeFrame(Decoder.java:147)
        at javazoom.spi.mpeg.sampled.convert.DecodedMpegAudioInputStream.execute(DecodedMpegAudioInputStream.java:185)
        at org.tritonus.share.TCircularBuffer.read(TCircularBuffer.java:138)
        at org.tritonus.share.sampled.convert.TAsynchronousFilteredAudioInputStream.read(TAsynchronousFilteredAudioInputStream.java:197)
        at java.desktop/com.sun.media.sound.AudioFloatInputStream$DirectAudioFloatInputStream.read(AudioFloatInputStream.java:191)
        at java.desktop/com.sun.media.sound.AudioFloatFormatConverter$AudioFloatInputStreamChannelMixer.read(AudioFloatFormatConverter.java:187)
        at java.desktop/com.sun.media.sound.AudioFloatFormatConverter$AudioFloatInputStreamResampler.readNextBuffer(AudioFloatFormatConverter.java:384)
        at java.desktop/com.sun.media.sound.AudioFloatFormatConverter$AudioFloatInputStreamResampler.read(AudioFloatFormatConverter.java:423)
        at java.desktop/com.sun.media.sound.AudioFloatFormatConverter$AudioFloatFormatConverterInputStream.read(AudioFloatFormatConverter.java:81)
        at java.desktop/javax.sound.sampled.AudioInputStream.read(AudioInputStream.java:284)
        at java.desktop/com.sun.media.sound.AudioFloatInputStream$DirectAudioFloatInputStream.read(AudioFloatInputStream.java:191)
        at java.desktop/com.sun.media.sound.AudioFloatInputStream.read(AudioFloatInputStream.java:278)
        at java.desktop/com.sun.media.sound.AudioFloatFormatConverter$AudioFloatInputStreamResampler.readNextBuffer(AudioFloatFormatConverter.java:381)
        at java.desktop/com.sun.media.sound.AudioFloatFormatConverter$AudioFloatInputStreamResampler.read(AudioFloatFormatConverter.java:423)
        at java.desktop/com.sun.media.sound.AudioFloatFormatConverter$AudioFloatFormatConverterInputStream.read(AudioFloatFormatConverter.java:81)
        at java.desktop/javax.sound.sampled.AudioInputStream.read(AudioInputStream.java:284)
        at java.desktop/javax.sound.sampled.AudioInputStream.read(AudioInputStream.java:226)
        at studio.core.v1.utils.AudioConversion.anyToMp3(AudioConversion.java:137)
        at studio.core.v1.utils.PackAssetsCompression.withPreparedAssetsFirmware2dot4(PackAssetsCompression.java:186)
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:318)
        ... 3 more

If you have something to help me, thanks

**Comment by daupalx** [comment]
I can't remove the file I made.

And also I never been able to convert to v2.x to drop it on my lunii.

if you have ways to find solutions, thanks to help me

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
