### ISSUE TITLE
SPG can't create directory if the podcast contains "?"

### ISSUE THREAD

**Issue by Aikino** [marian-m12l/studio#366]
**Describe the bug**
While trying to get the content of the podcast "Quand est-ce qu'on arrive?"
I got an error and SPG was not able to create the directory needed.

**To Reproduce**
>> studio-pack-generator https://radio.vinci-autoroutes.com/rss/quand-est-ce-quon-arrive

**Expected behavior**
Release a full package with all the podcast

**Screenshots**
N/A

**Logs**
Error: The filename, directory name, or volume label syntax is incorrect. (os error 123), mkdir 'Quand est-ce qu'on arrive ?'
    at async Object.mkdir (internal:runtime/js/30_fs.js:115:3)
    at async writeFolderWithUrl (file:///home/runner/work/studio-pack-generator/studio-pack-generator/generate/rss_parser.ts:79:5)
    at async downloadRss (file:///home/runner/work/studio-pack-generator/studio-pack-generator/generate/rss_parser.ts:107:5)
    at async generatePack (file:///home/runner/work/studio-pack-generator/studio-pack-generator/gen_pack.ts:31:25)
    at async Object.handler (file:///home/runner/work/studio-pack-generator/studio-pack-generator/utils/parse_args.ts:17:22)

**Desktop and environment (please complete the following information):**
 - OS: Win10
 - Browser : Chrome
 - SPG : { version: "v0.2.4", deno: "1.31.1", v8: "11.0.226.13", typescript: "4.9.4" }

**Additional context**

**Comment by marian-m12l** [comment]
Hi,
You'll probably want to open an issue here: https://github.com/jersou/studio-pack-generator
