### ISSUE TITLE
Lunii: Failed to add pack to device

### ISSUE THREAD

**Issue by Lark7777** [marian-m12l/studio#367]
Hello all,

J'ai un soucis en transférant des histoires depuis Studio vers ma Lunii v2.22. Je fais toutes les étapes de conversion nécessaires, j'obtiens bien le fichier au format FS, mais quand je click and drop vers ma Lunii, je reçois un message rouge "Failed to add pack to device". Certaines histoires fonctionnent, d'autres (la plupart) non. Est-ce que vous sauriez pourquoi? Comment remédier au soucis?

Merci d'avance,
Lark7777

**Comment by mjdmto** [comment]
Bonjour,
Idem pour moi pour le pack Une Histoire et OLI.
Un idée ?
En vous remerciant par avance.

**Comment by RoRoStar** [comment]
Moi j'ai eu le même souci, j'ai supprimer le contenu du répertoire de la lunii dans lequel il essayais de copier l'histoire (en ligne de commande), dans mon cas c'était le contenu de J:/.content/456D08DE/, et après c'est passé.

[https://github.com/marian-m12l/studio/issues/376](url)

**Comment by LeoShivas** [comment]
Je rencontre le même souci.
La suppression des dossiers n'a eu aucun effet.

**Comment by LeoShivas** [comment]
Voici la stack trace :
```
2023-07-06 22:57:55,000 [ERROR] [s.w.MainVerticle]: Exception thrown
java.lang.IllegalArgumentException: malformed input off : 30, length : 1
        at java.base/java.lang.String.throwMalformed(String.java:1260)
        at java.base/java.lang.String.decodeUTF8_UTF16(String.java:1216)
        at java.base/java.lang.String.newStringUTF8NoRepl(String.java:749)
        at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2473)
        at java.base/java.util.zip.ZipCoder$UTF8ZipCoder.toString(ZipCoder.java:199)
        at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:66)
        at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:516)
        at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:153)
        at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
        at studio.webui.service.LibraryService.readPackFile(LibraryService.java:436)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at studio.webui.service.LibraryService.packs(LibraryService.java:99)
        at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
```

**Comment by RoRoStar** [comment]
Il semblerait qu'il y'ai un souci de charactère non reconnu :  "MalformedInputException"
Vérifie qu'il n'y a pas d'espace ou d'accent dans le chemin du répertoire

**Comment by LeoShivas** [comment]
Je viens de faire quelques modifications (renommage de fichier, déplacement) et ça ne fonctionne toujours pas. Même message d'erreur.
Voici le fichier en question :
```
E:\Lunii\A_la_Decouverte_de_Nouveaux_Mondes.zip
```
Lorsque je l'importe, il arrive bien dans :
```
C:\Users\myuser\.studio\library\A_la_Decouverte_de_Nouveaux_Mondes.zip
```

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
