### ISSUE TITLE
studio web launch and close

### ISSUE THREAD

**Issue by cedrict25** [marian-m12l/studio#372]
hello,
First,my two young children want to thank you for your fantastic work but i got an issue !

I am on WIN 10
java version is build 1.8.0_371-b11
browser is firefox

i've try everything....reinstall lunii app,java,studio web 0.3.1,firefox

here is the log:

2023-06-01 17:39:20,454 [ERROR] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:77]: Failed in deploying verticle
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 143 column 7219823 path $.a24daf0f-d5a1-4032-8320-36b3033cc5c7.image
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at studio.metadata.DatabaseMetadataService.cleanUnofficialDatabase(DatabaseMetadataService.java:245)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:77)
	at studio.webui.MainVerticle.start(MainVerticle.java:47)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 143 column 7219823 path $.a24daf0f-d5a1-4032-8320-36b3033cc5c7.image
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031)
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:702)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 17 more

**Comment by cedrict25** [comment]
i find a solution ,i delete de official and unofficial json files and everything is back to normal !!
Thanks again this is really a perfect app.

**Comment by cedrict25** [comment]
just one things,is there a way to change the path C:\user\.studio\library ?
