### ISSUE TITLE
Studio (v. 0.3.1) Echec de rafraichissement de la bibliothèque

### ISSUE THREAD

**Issue by Guillaumecmoi** [marian-m12l/studio#373]
**Describe the bug**
Une fois un pack d'histoires téléchargé, et le "reversement" effectué, il y a un "échec de rafraichissement de la bibliothèque".

**To Reproduce**
1. Ajouter un pack d'histoires à la bibliothèque
2. Choix du pack téléchargé sur le disque dur, OK
3. Pack d'histoires téléversé
4. Echec du rafraichissement de la bibliothèque

**Expected behavior**
Pack installé.

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> malformed input off : 19, length : 1: Error 500: malformed input off : 19, length : 1	at java.base/java.lang.String.throwMalformed(String.java:1260)
	at java.base/java.lang.String.decodeUTF8_UTF16(String.java:1216)
	at java.base/java.lang.String.newStringUTF8NoRepl(String.java:749)
	at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2473)
	at java.base/java.util.zip.ZipCoder$UTF8ZipCoder.toString(ZipCoder.java:199)
	at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:66)
	at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:516)
	at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:153)
	at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
	at studio.webui.service.LibraryService.readPackFile(LibraryService.java:436)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at studio.webui.service.LibraryService.packs(LibraryService.java:99)
	at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)

**Desktop and environment (please complete the following information):**
 - OS: MacIntel
 - Browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/114.0
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.3.1

**Additional context**

**Comment by LeoShivas** [comment]
Je rencontre le même souci.
Version de Lunii : 2.22

**Comment by LeoShivas** [comment]
Voici la stack trace :
```
2023-07-06 22:57:55,000 [ERROR] [s.w.MainVerticle]: Exception thrown
java.lang.IllegalArgumentException: malformed input off : 30, length : 1
        at java.base/java.lang.String.throwMalformed(String.java:1260)
        at java.base/java.lang.String.decodeUTF8_UTF16(String.java:1216)
        at java.base/java.lang.String.newStringUTF8NoRepl(String.java:749)
        at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2473)
        at java.base/java.util.zip.ZipCoder$UTF8ZipCoder.toString(ZipCoder.java:199)
        at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:66)
        at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:516)
        at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:153)
        at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
        at studio.webui.service.LibraryService.readPackFile(LibraryService.java:436)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at studio.webui.service.LibraryService.packs(LibraryService.java:99)
        at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
```

**Comment by RomainHermenier** [comment]
Hello, I have the same issue. 
I upload ZIP files to the library but the page doesnt refresh and I get a Java exception.
See below. Any idea where to look?

Using STUdio 0.3.1, Lunii Firmware version 2.2
Cheers

2023-08-14 10:06:10,076 [ERROR] [s.w.MainVerticle]: Exception thrown
java.lang.IllegalArgumentException: malformed input off : 8, length : 1
        at java.base/java.lang.String.throwMalformed(String.java:1260)
        at java.base/java.lang.String.decodeUTF8_UTF16(String.java:1216)
        at java.base/java.lang.String.newStringUTF8NoRepl(String.java:749)
        at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2473)
        at java.base/java.util.zip.ZipCoder$UTF8ZipCoder.toString(ZipCoder.java:199)
        at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:66)
        at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:516)
        at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:153)
        at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
        at studio.webui.service.LibraryService.readPackFile(LibraryService.java:436)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at studio.webui.service.LibraryService.packs(LibraryService.java:99)
        at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        ... 30 more

**Comment by RomainHermenier** [comment]
I found the issue. I was uploading zip files directly via the "add a story pack to library" button. Instead, I had to create a new story pack with all the arctehicture (cover, menu, story nodes). It works now!
