### ISSUE TITLE
Aucun pack d'histoires dans l'appareil.

### ISSUE THREAD

**Issue by CasqueOuille** [marian-m12l/studio#379]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> Internal Server Error: Error 500: studio.core.v1.utils.exception.StoryTellerException: Failed to read pack metadata on device partition	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.4.2

**Additional context**

**Comment by CasqueOuille** [comment]
Décrire le bogue

J'ai une dizaine de pack d'histoires présents dans la lunii mais impossible de les visualiser et d'en ajouter/supprimer.
![echec lunii](https://github.com/marian-m12l/studio/assets/138936624/135eaaf4-9830-4f70-b78b-d90687cf8532)

**Comment by CasqueOuille** [comment]
![bug lunii](https://github.com/marian-m12l/studio/assets/138936624/9953cefb-0773-4ca3-a1b4-dac8bc9c818d)

**Comment by CasqueOuille** [comment]
Je précise que cela fonctionnait avant que que je charge le pack "Disney" qui a fonctionnait mais apparaissait en doublon. En an supprimant un ce bogue est alors apparu.

**Comment by bobosse86** [comment]
Bonjour,
Je ressort ce topic, car il m'arrive exactement la même chose avec un doublon "Bestioles" et la version "Studio-web-ui-0.5.2" sur Mac et version Lunii 1. Tous les packs fonctionnent sur la Lunii mais il est impossible d'en ajouter et supprimer.
 Dans la partie "Appareil" la capacité mémoire est indiquée mais en dessous il est indiqué "Aucun pack d'histoires dans l'appareil".
