### ISSUE TITLE
Echec de la récupération des packs d'histoire de l'appareil

### ISSUE THREAD

**Issue by brunoF782** [marian-m12l/studio#386]
**Describe the bug**
Bonjour,

ma lunii contient trois packs d'histoire. 
J'en avais ajouté un 4ème grâce au studio et tout fonctionnait correctement. J'ai modifié ce 4ème pack et ait voulu le réimporter sur la lunii. Cela n'était pas possible, une erreur de la log indiquait que le pack existait déjà. Je suis donc allé dans le répertoire E:\.content de la lunii et ait supprimé le répertoire crée ce jour (qui, je supposais, correspondait au contenu du 4ème pack). Grave erreur puisque depuis lorsque je lance le studio (cf. description erreur ci-dessous), je ne vois plus le contenu des packs présents sur la lunii....

Quelqu'un peut m'aider ? :)
Merci beaucoup !!!

**To Reproduce**
1. Allumer la lunii et la connecter en usb au pc
2. Lancer studio-web-ui-0.3.1-dist
3. Message : Echec de la récupération des packs d'histoire de l'appareil

les captures : 

![image](https://github.com/marian-m12l/studio/assets/143334715/1ef242f6-3765-42b4-affe-c25920442f3c)

![image](https://github.com/marian-m12l/studio/assets/143334715/bb4e31da-53c2-4689-8f34-395fa5de1c52)

**Logs**

2023-08-27 16:01:43,010 [INFO ] [s.w.s.StoryTellerService]: Setting up story teller driver
2023-08-27 16:01:43,025 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: Registering hotplug listener
2023-08-27 16:01:43,031 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2023-08-27 16:01:43,064 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2023-08-27 16:01:43,064 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2023-08-27 16:01:43,073 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Registering hotplug listener
2023-08-27 16:01:43,073 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2023-08-27 16:01:43,073 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2023-08-27 16:01:43,073 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2023-08-27 16:01:43,112 [INFO ] [s.d.LibUsbActivePollingWorker]: Active polling found a new device. Firing event.
2023-08-27 16:01:43,113 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Waiting for device partition...
2023-08-27 16:01:43,256 [INFO ] [s.w.MainVerticle]: Opening URL in default browser...
2023-08-27 16:01:43,411 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle
2023-08-27 16:01:44,131 [INFO ] [s.d.f.FsStoryTellerAsyncDriver]: FS device partition located: E:\
2023-08-27 16:01:44,131 [INFO ] [s.w.s.StoryTellerService]: Device 2.x plugged
2023-08-27 16:01:44,139 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Firmware version: 2.22
2023-08-27 16:01:44,139 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Serial Number: 9027061364556163
2023-08-27 16:01:44,139 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: UUID: 029c1c61c83036e60f0f624a27facde1457370a5b53abc6a5d97b3c5278365df8d0652f82319477e1bb6fb910b6f6ca20898d184e4bf274a98032791768d54161812b7eaa456c07d92ca9b1f80a41d138106e6e05fb8f1babc8f768bf378c6f9afddd3b2d8eed3fb7d8255db6e4f767ce0c23c6fab8fda9377407935e4cb8dd3dedca25c309178ca7ad34c12b773267299e73bd4ffb994361198048ba1b761b64b03d5dfab61fd76e710ae0df0144115f2d475c40d50bcd990602a6af6e5cb44dc6c310ede1cc8004beea5aeb91cf2ddfbe7afe03e7e779b3c02d2d39fcf1cd8c00c10a0ba898da6842a8aff721a85c5240ff2c1398bd6e0050d29e0574f97e8
2023-08-27 16:01:44,147 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card size: 7939817472
2023-08-27 16:01:44,147 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card used space: 482934784
2023-08-27 16:01:44,259 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Firmware version: 2.22
2023-08-27 16:01:44,259 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Serial Number: 9027061364556163
2023-08-27 16:01:44,259 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: UUID: 029c1c61c83036e60f0f624a27facde1457370a5b53abc6a5d97b3c5278365df8d0652f82319477e1bb6fb910b6f6ca20898d184e4bf274a98032791768d54161812b7eaa456c07d92ca9b1f80a41d138106e6e05fb8f1babc8f768bf378c6f9afddd3b2d8eed3fb7d8255db6e4f767ce0c23c6fab8fda9377407935e4cb8dd3dedca25c309178ca7ad34c12b773267299e73bd4ffb994361198048ba1b761b64b03d5dfab61fd76e710ae0df0144115f2d475c40d50bcd990602a6af6e5cb44dc6c310ede1cc8004beea5aeb91cf2ddfbe7afe03e7e779b3c02d2d39fcf1cd8c00c10a0ba898da6842a8aff721a85c5240ff2c1398bd6e0050d29e0574f97e8
2023-08-27 16:01:44,267 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card size: 7939817472
2023-08-27 16:01:44,267 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card used space: 482934784
2023-08-27 16:01:44,505 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Number of packs in index: 4
2023-08-27 16:01:44,505 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: c4139d59-872a-4d15-8cf1-76d34cdf38c6
2023-08-27 16:01:44,510 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 2
2023-08-27 16:01:44,532 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: d489f67b-0e51-4669-b1e1-1555f3c18541
2023-08-27 16:01:44,534 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2023-08-27 16:01:44,538 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 79c3b2b7-163e-4b3d-92d8-f8b63021cc85
2023-08-27 16:01:44,538 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2023-08-27 16:01:44,538 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 399d1cf1-92ec-4cf5-9a64-cb5da053be4a
2023-08-27 16:01:44,547 [ERROR] [s.w.a.DeviceController]: Failed to read packs from device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack metadata on device partition
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: studio.driver.StoryTellerException: Failed to read pack metadata on device partition
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$getPacksList$0(FsStoryTellerAsyncDriver.java:225)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        ... 8 more
Caused by: java.io.FileNotFoundException: E:\.content\A053BE4A\ni (Le chemin d鈥檃cc猫s sp茅cifi茅 est introuvable)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$getPacksList$0(FsStoryTellerAsyncDriver.java:206)
        ... 9 more
2023-08-27 16:01:44,554 [ERROR] [s.w.MainVerticle]: Exception thrown
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack metadata on device partition
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: studio.driver.StoryTellerException: Failed to read pack metadata on device partition
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$getPacksList$0(FsStoryTellerAsyncDriver.java:225)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        ... 8 more
Caused by: java.io.FileNotFoundException: E:\.content\A053BE4A\ni (Le chemin d鈥檃cc猫s sp茅cifi茅 est introuvable)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$getPacksList$0(FsStoryTellerAsyncDriver.java:206)
        ... 9 more

**Comment by BaseZoubru** [comment]
Conseil, tout effacer via explorateur les repertoires de la card sd de la Lunii, repasser par l'application officielle, "réparer" et remettre les packs originales de la lunii, fermer l'application officielle. Ensuite lancer studio.

**Comment by BaseZoubru** [comment]
Vas voir mon post, j'ai résolu le pbm...

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
