### ISSUE TITLE
Add a pack directly to the SD card

### ISSUE THREAD

**Issue by drskullster** [marian-m12l/studio#388]
Hi,

I Can't connect my device to my computer anymore (I had to resolder the micro-USB chip, figure I did something wrong to the data track.

I tried mounting the SD card with [this trick](https://github.com/marian-m12l/studio/issues/327#issuecomment-1477593344) to no avail (it worked before I mingled with the PCB).

My question is: is there a way to add packs directly to the SD cards?

I tried copying the files converted to "FS format" that I found in STUdio library folder (`~/.studio/library`) to the `.content` folder on the SD card but it didn't work. I guess there is something else I need to do, anyone here has any idea ?

Thanks !

**Comment by marian-m12l** [comment]
The story pack folders are named after a partial uuid, and the pack uuid must be added to the "pack index" `.pi` file.
You can trick STUdio into using any folder as a device partition by running it with `-Denv=dev` (`mvn exec:exec` should do that iirc) and adjusting `devicePath()` here: https://github.com/marian-m12l/studio/blob/5150a157c94f64292a3fbc6ce6764274c608e249/web-ui/src/main/java/studio/webui/service/mock/MockStoryTellerService.java#L62-L64

**Comment by Coolkeum** [comment]
Hi,

I also have some troubles with Lunii v2 USB-C port, that's why I want to copy packs directly to SD card.

The converted files (I try v1 and v2 conversions) from `~/.studio/library` were well copied to the `.content` folder on the SD card :

![Image](https://github.com/user-attachments/assets/69b09077-a780-4de8-bd29-4bf7173cdfc6)

![Image](https://github.com/user-attachments/assets/8717007d-af24-480d-879c-8243c49d0599)

The "pack index" `.pi` file was also edited using HxD editor and respecting the following rules : https://github.com/o-daneel/Lunii.RE/blob/main/ANALYSIS.md#pi

![Image](https://github.com/user-attachments/assets/0dbf02da-2e7a-44dc-b4cd-2ef5f321b62e)

However, the unofficial packs are not displayed on the Lunii (only default official packs `F3C18541` and `4CDF38C6` are showed). Is there something else to do ? Is it necessary to edit another file ?

Moreover, I try the method explained by @marian-m12l with `-Denv=dev` option, the studio software takes this option into account but when I want to move a pack into the mock device, the following error is displayed 👍 

![Image](https://github.com/user-attachments/assets/6fb9391c-fc52-41a1-aa88-f2cc2385cf24)

```
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
2025-01-22 22:40:03,029 [WARN ] [s.w.MainVerticle]: [DEV MODE] Initializing mock storyteller service
2025-01-22 22:40:03,033 [INFO ] [s.w.s.m.MockStoryTellerService]: Setting up mocked story teller service
2025-01-22 22:40:03,143 [INFO ] [s.w.MainVerticle]: Opening URL in default browser...
2025-01-22 22:40:03,467 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle
2025-01-22 22:42:12,595 [ERROR] [s.w.MainVerticle]: Exception thrown
2025-01-22 22:42:13,622 [ERROR] [s.w.s.m.MockStoryTellerService]: Failed to add pack to mocked device
java.io.FileNotFoundException: C:\Users\Romain\.studio\library\null (Le fichier sp├®cifi├® est introuvable)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
        at studio.webui.service.mock.MockStoryTellerService$1.run(MockStoryTellerService.java:157)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
```

The folder `C:\Users\Romain\.studio\device` exists and I copy all the SD card content (`.content`, `.cfg`, `.md`, `.pi` and `version`) into but the same error is still here. Finally,

I try with the `set "FS_MOUNTPOINT=D:\"` variable definition to use directly SD card mounted under Windows OS in D drive but in this case, no Lunii is displayed under Studio.

I really appreciated if someone could help me about that 😉
