### ISSUE TITLE
Failed in deploying verticle (new)

### ISSUE THREAD

**Issue by MahaultGalibert** [marian-m12l/studio#389]
**Describe the bug**
Hello, I have been using the studio for a long time on several computers already but can't manage to launch it (for the first time) on my current machine

**To Reproduce**
When I launch the "studio-macos.sh" I get the following error message :

2023-08-31 20:55:47,932 [ERROR] [i.v.c.i.l.c.VertxIsolatedDeployer]: Failed in deploying verticle
java.lang.ExceptionInInitializerError
	at studio.driver.LibUsbDetectionHelper.initializeLibUsb(LibUsbDetectionHelper.java:50)
	at studio.driver.raw.RawStoryTellerAsyncDriver.<init>(RawStoryTellerAsyncDriver.java:45)
	at studio.webui.service.StoryTellerService.<init>(StoryTellerService.java:54)
	at studio.webui.MainVerticle.start(MainVerticle.java:60)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: org.usb4java.LoaderException: Native library not found in classpath: /org/usb4java/darwin-aarch64/libusb4java.dylib
	at org.usb4java.Loader.extractLibrary(Loader.java:246)
	at org.usb4java.Loader.load(Loader.java:323)
	at org.usb4java.LibUsb.<clinit>(LibUsb.java:690)
	... 16 more

I am still a beginner in development and am not able to understand what the problem is here : is it related to java ? does anyone have a clue on how to fix the issue ? any help would be much appreciated !! :)

**Expected behavior**
Launching the .sh file usually opens the localhost:8080 window and allows me to use the studio.

**Desktop and environment**
 - OS: macOS Monterery Version 12.5 - MacBook Air (M1, 2020)
 - Browser: safari
 - Java version: JDK 17.0.8
 - STUdio application version: 0.3.1

PS: thanks a lot Marian for this amazing tool I love it and my children too !!

**Comment by MahaultGalibert** [comment]
Closing this issue as replicates #380
