### ISSUE TITLE
echec du rafraichissement de la bibliothèque

### ISSUE THREAD

**Issue by LaetitiaVerriere** [marian-m12l/studio#392]
1 fichier(s) copié(s).
        1 fichier(s) copié(s).
2023-09-06 17:28:02,829 [INFO ] [s.w.s.StoryTellerService]: Setting up story teller driver
2023-09-06 17:28:02,834 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: Registering hotplug listener
2023-09-06 17:28:02,836 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2023-09-06 17:28:02,860 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2023-09-06 17:28:02,860 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2023-09-06 17:28:02,865 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Registering hotplug listener
2023-09-06 17:28:02,866 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2023-09-06 17:28:02,867 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2023-09-06 17:28:02,868 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2023-09-06 17:28:02,964 [INFO ] [s.w.MainVerticle]: Opening URL in default browser...
2023-09-06 17:28:03,011 [INFO ] [s.d.LibUsbActivePollingWorker]: Active polling found a new device. Firing event.
2023-09-06 17:28:03,017 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Waiting for device partition...
2023-09-06 17:28:03,162 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle
2023-09-06 17:28:04,685 [ERROR] [s.w.s.LibraryService]: Failed to read archive-format pack C:\Users\korna\.studio\library\Lunii.Pack1...wawacity.cloud.zip from local library
java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor
        at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:313)
        at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:125)
        at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
        at studio.webui.service.LibraryService.readPackFile(LibraryService.java:436)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at studio.webui.service.LibraryService.packs(LibraryService.java:99)
        at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-09-06 17:28:04,698 [ERROR] [s.w.s.LibraryService]: Failed to read archive-format pack C:\Users\korna\.studio\library\Lunii.Pack1.zip from local library
java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor
        at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:313)
        at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:125)
        at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
        at studio.webui.service.LibraryService.readPackFile(LibraryService.java:436)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at studio.webui.service.LibraryService.packs(LibraryService.java:99)
        at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-09-06 17:28:04,941 [ERROR] [s.w.MainVerticle]: Exception thrown
java.lang.IllegalArgumentException: malformed input off : 29, length : 1
        at java.base/java.lang.StringCoding.throwMalformed(StringCoding.java:707)
        at java.base/java.lang.StringCoding.decodeUTF8_0(StringCoding.java:894)
        at java.base/java.lang.StringCoding.newStringUTF8NoRepl(StringCoding.java:990)
        at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2218)
        at java.base/java.util.zip.ZipCoder$UTF8.toString(ZipCoder.java:60)
        at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:87)
        at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:303)
        at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:125)
        at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
        at studio.webui.service.LibraryService.readPackFile(LibraryService.java:436)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at studio.webui.service.LibraryService.packs(LibraryService.java:99)
        at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        ... 30 more
2023-09-06 17:28:29,052 [ERROR] [s.w.s.LibraryService]: Failed to read archive-format pack C:\Users\korna\.studio\library\Lunii.Pack1...wawacity.cloud.zip from local library
java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor
        at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:313)
        at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:125)
        at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
        at studio.webui.service.LibraryService.readPackFile(LibraryService.java:436)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at studio.webui.service.LibraryService.packs(LibraryService.java:99)
        at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-09-06 17:28:29,053 [ERROR] [s.w.s.LibraryService]: Failed to read archive-format pack C:\Users\korna\.studio\library\Lunii.Pack1.zip from local library
java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor
        at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:313)
        at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:125)
        at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
        at studio.webui.service.LibraryService.readPackFile(LibraryService.java:436)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at studio.webui.service.LibraryService.packs(LibraryService.java:99)
        at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-09-06 17:28:29,231 [ERROR] [s.w.MainVerticle]: Exception thrown
java.lang.IllegalArgumentException: malformed input off : 29, length : 1
        at java.base/java.lang.StringCoding.throwMalformed(StringCoding.java:707)
        at java.base/java.lang.StringCoding.decodeUTF8_0(StringCoding.java:894)
        at java.base/java.lang.StringCoding.newStringUTF8NoRepl(StringCoding.java:990)
        at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2218)
        at java.base/java.util.zip.ZipCoder$UTF8.toString(ZipCoder.java:60)
        at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:87)
        at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:303)
        at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:125)
        at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
        at studio.webui.service.LibraryService.readPackFile(LibraryService.java:436)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at studio.webui.service.LibraryService.packs(LibraryService.java:99)
        at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        ... 30 more

**Comment by marian-m12l** [comment]
Looks like a corrupted archive in the library.

I'm closing issues from past years. Feel free to reopen if needed.
