### ISSUE TITLE
echec du rafraichissement de la bibliothèque

### ISSUE THREAD

**Issue by 221989** [marian-m12l/studio#397]
Bonsoir ! 

Je n'arrive pas à mettre les histoires sur la LUNII. Le téléversement fonctionne mais studio m'indique ensuite "echec du rafraichissement de la bibliothèque"

Voilà ce que j'ai :

2023-09-22 23:18:41,034 [WARN ] [i.v.c.i.BlockedThreadChecker]: Thread Thread[#27,vert.x-eventloop-thread-0,5,main]=Thread[#27,vert.x-eventloop-thread-0,5,main] has been blocked for 2749 ms, time limit is 2000 ms
2023-09-22 23:19:05,872 [ERROR] [s.w.MainVerticle]: Exception thrown
java.lang.IllegalArgumentException: malformed input off : 19, length : 1
	at java.base/java.lang.String.throwMalformed(String.java:1279)
	at java.base/java.lang.String.decodeUTF8_UTF16(String.java:1235)
	at java.base/java.lang.String.newStringUTF8NoRepl(String.java:759)
	at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2486)
	at java.base/java.util.zip.ZipCoder$UTF8ZipCoder.toString(ZipCoder.java:270)
	at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:91)
	at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:519)
	at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:153)
	at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
	at studio.webui.service.LibraryService.readPackFile(LibraryService.java:436)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at studio.webui.service.LibraryService.packs(LibraryService.java:99)
	at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	... 30 more

Je suis sous mac os et ne trouve pas la solution ! J'ai même réinitialisé la LUNII, en vain 

HELP ME PLEASE :'(

**Comment by marian-m12l** [comment]
Probably a corrupted archive in the library.

I'm closing issues from past years. Feel free to reopen if needed.
