### ISSUE TITLE
Le studio 0.5 ne reconnait plus ma lunii V3

### ISSUE THREAD

**Issue by Heracec** [marian-m12l/studio#418]
**Describe the bug**
Le studio Luni n'arrive plus à télécharger ma bibliothèque Luni V3. Cela a très bien fonctionné la 1ère fois, et depuis impossible. Message d'erreur systématique.

**To Reproduce**
Je lance mon studio, et au branchement de la Lunii j'ai le message d'erreur qui s'affiche.

**Expected behavior**
Comment faire pour retrouver ma bibliothèque ? Le java est pourtant à jour.
Merci d'avance pour votre aide !!!

**Screenshots**
![Capture d'écran 2023-12-25 154641](https://github.com/marian-m12l/studio/assets/154813360/3ed118a0-14bb-4656-b138-c33e23dbf36d)

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> Internal Server Error: Error 500: studio.core.v1.utils.exception.StoryTellerException: Failed to read pack metadata on device partition	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.5.0

**Additional context**

**Comment by julienezekiel** [comment]
Please where can we fin studio 0.5 for Lunii3 ???? don't find it

**Comment by antoinecoulon** [comment]
https://github.com/DantSu/studio/releases/tag/0.5.1

**Comment by marian-m12l** [comment]
Experimental support for V3 devices has been merged on master. This remains mostly untested.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
