### ISSUE TITLE
Lunii transfer - Not enough space available with Lunii almost empty

### ISSUE THREAD

**Issue by parmend** [marian-m12l/studio#431]
**Describe the bug**
When trying to transfer to Lunii's a story, it finally crash

**To Reproduce**

Drag and drop a converted story to Lunii, wait for conversion and at the end, the error appears

**Expected behavior**

transfer to Lunii expected

**Screenshots**
See logs

**Logs**

2024-01-12 22:03:59,975 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-10) Request failed: java.util.concurrent.CompletionException: studio.core.v1.exception.StoryTellerException: Failed to check device space
        at java.base@17.0.5/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base@17.0.5/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base@17.0.5/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
        at java.base@17.0.5/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base@17.0.5/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        at java.base@17.0.5/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base@17.0.5/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base@17.0.5/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base@17.0.5/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base@17.0.5/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base@17.0.5/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178)
Caused by: studio.core.v1.exception.StoryTellerException: Failed to check device space
        at studio.driver.service.fs.FsStoryTellerAsyncDriver.uploadPack(FsStoryTellerAsyncDriver.java:384)
        at studio.webui.service.StoryTellerService.upload(StoryTellerService.java:174)
        at studio.webui.service.StoryTellerService.lambda$addPack$3(StoryTellerService.java:116)
        at java.base@17.0.5/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        ... 10 more
Caused by: java.nio.file.NoSuchFileException: .\library\.\library\48607610-7287-4bc5-a320-e4055a93bff1.converted_1705093439411
        at java.base@17.0.5/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base@17.0.5/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base@17.0.5/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
        at java.base@17.0.5/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base@17.0.5/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
        at java.base@17.0.5/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
        at java.base@17.0.5/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
        at java.base@17.0.5/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
        at java.base@17.0.5/java.nio.file.Files.walk(Files.java:3918)
        at java.base@17.0.5/java.nio.file.Files.walk(Files.java:3973)
        at studio.core.v1.utils.io.FileUtils.getFolderSize(FileUtils.java:42)
        at studio.driver.service.fs.FsStoryTellerAsyncDriver.uploadPack(FsStoryTellerAsyncDriver.java:371)
        ... 13 more

**Desktop and environment (please complete the following information):**
 - OS: Windows 10 Professionnel
 - Browser : mozilla
 - Java version: [e.g. JDK 11.0.6] 8.0-391-b13
 - Maven version: [e.g. 3.6.0]
 - STUdio application version [e.g. 0.1.11] portable 1.0.2

**Additional context**

Thanks

**Comment by marian-m12l** [comment]
Thanks for the feedback @parmend 
It looks like you're using a fork of STUdio, latest release in this repository is 0.4.1.
