### ISSUE TITLE
Can't open STUdio on Windows

### ISSUE THREAD

**Issue by Cuhesse** [marian-m12l/studio#432]
**Describe the bug**
When I launch studio-windows.bat i have the traditional 1 files copied then a lot of lines. The cmd.exe shutdown and nothing happen.

**Expected behavior**
STUdio to launch and work fine.

**Logs**
2024-02-08 18:02:05,414 [ERROR] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:77]: Failed in deploying verticle
java.lang.ClassCastException: class com.google.gson.JsonPrimitive cannot be cast to class com.google.gson.JsonObject (com.google.gson.JsonPrimitive and com.google.gson.JsonObject are in unnamed module of loader 'app')
	at com.google.gson.JsonObject.getAsJsonObject(JsonObject.java:205)
	at studio.metadata.DatabaseMetadataService.lambda$new$0(DatabaseMetadataService.java:50)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:49)
	at studio.webui.MainVerticle.start(MainVerticle.java:47)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Desktop and environment (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Java version: JDK 21
 - STUdio application version 3.1

**Comment by marian-m12l** [comment]
Thanks for the feedback. Sounds like your story pack metdata database file`official.json` is corrupted. Remove it and it should be created again by STUdio.
