### ISSUE TITLE
OutOfMemory (java heap space) while uncompressing pack assets

### ISSUE THREAD

**Issue by dasebasto** [marian-m12l/studio#44]
Java 13 on Windows 10.

I created a big pack containing approximately 50 MP3 files (biggest audio file is about 24MB), which is about 400MB (25 stories).

I get the following error after a couple of minutes:

`WARNING: Uncompressing pack assets
Exception in thread "Timer-8" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3746)
        at java.base/java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:185)
        at studio.core.v1.utils.AudioConversion.anyToWave(AudioConversion.java:65)
        at studio.core.v1.utils.AudioConversion.mp3ToWave(AudioConversion.java:27)
        at studio.core.v1.utils.PackAssetsCompression.withUncompressedAssets(PackAssetsCompression.java:116)
        at studio.webui.service.LibraryService.getBinaryPackFile(LibraryService.java:134)
        at studio.webui.api.DeviceController$1.run(DeviceController.java:66)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
mars 31, 2020 8:40:04 PM studio.webui.service.LibraryService`

I guess memory management could be improved, as working with the same kind of files (~20MB MP3s) on a smaller pack (2 stories) does not cause OOM.

I did find an easy workaround (running STUdio with increased JVM heap size) though, so I have been able to transfer the pack successfully eventually:

In `studio-windows.bat` replace
`java -cp studio-web-ui-0.1.11.jar;lib/*;%DOT_STUDIO%/lib/*;. io.vertx.core.Launcher run studio.webui.MainVerticle`

with 
`java -Xmx6g -cp studio-web-ui-0.1.11.jar;lib/*;%DOT_STUDIO%/lib/*;. io.vertx.core.Launcher run studio.webui.MainVerticle`

**Comment by marian-m12l** [comment]
Hi,

Indeed, memory management have plenty of room for improvement! Actually the whole story pack is held in memory, so this is not a surprise that a pack with plenty of assets fills up memory. Your workaround is right, but theoretically for even bigger packs we'd still be limited by the RAM / swap available on the computer and need better memory management.
Not sure this is a priority, though. 400 MB of MP3 isn't exactly your everyday story pack, and must take a good chunk of the Lunii memory too!

Thank for the feedback!

**Comment by freeKC** [comment]
Hi,
Thanks for the soft, really good.

Same problem on my side with a not-so-small pack :
2020-04-08 10:44:29,871 [WARN ] [s.w.s.LibraryService]: Reading archive format pack
2020-04-08 10:44:31,593 [WARN ] [s.w.s.LibraryService]: Uncompressing pack assets
Exception in thread "Timer-0" java.lang.OutOfMemoryError: **Java heap space**
	at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
	at java.base/java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:120)
	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:156)
	at java.desktop/com.sun.media.sound.WaveFileWriter.writeWaveFile(WaveFileWriter.java:225)
	at java.desktop/com.sun.media.sound.WaveFileWriter.write(WaveFileWriter.java:103)
	at java.desktop/javax.sound.sampled.AudioSystem.write(AudioSystem.java:1197)
	at studio.core.v1.utils.AudioConversion.anyToWave(AudioConversion.java:64)
	at studio.core.v1.utils.AudioConversion.mp3ToWave(AudioConversion.java:27)
	at studio.core.v1.utils.PackAssetsCompression.withUncompressedAssets(PackAssetsCompression.java:116)
	at studio.webui.service.LibraryService.getBinaryPackFile(LibraryService.java:134)
	at studio.webui.api.DeviceController$1.run(DeviceController.java:66)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)


Thanks for the workaround.

**Comment by marian-m12l** [comment]
@freeKC Thanks for the feedback. I'm guessing the workaround did the trick for you too? Improving memory management would imply an overhaul of the core library, so this is not planned as I'm not sure it is _that_ common. For my information, how big was your story pack (compressed and uncompressed)?

**Comment by freeKC** [comment]
Yep, it worked fine, and probably enough for exotic uses.
Compressed : 472MB
Uncompressed : 461MB (yes ... smaller than compressed)

**Comment by marian-m12l** [comment]
@freeKC That's strange. How big are your compressed files? Did all the files make it into the binary pack file?

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.

**Comment by PEGARifrouf** [comment]
Hello,

I get the same issue here. I was able to fix it on my case by increasing the maximum memory allocation pool for java with the -Xmx argument.

Open the studio-xxxx.sh that you are using to launch the application.
On the last line with the "java" call add "-Xmx2G" argument to increase the pool size to 2GB.

In my case:
`java -Xmx2G -Dvertx.disableDnsResolver=true -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -Dfile.encoding=UTF-8 -cp $STUDIO_PATH/studio-web-ui-0.4.1.jar:$STUDIO_PATH/lib/*:. io.vertx.core.Launcher run studio.webui.MainVerticle
`

regards
