### ISSUE TITLE
Fail to add pack to the device

### ISSUE THREAD

**Issue by BileeRedram** [marian-m12l/studio#441]
**Describe the bug**
Impossible to add a homemade pack on my lunii v2.22

**To Reproduce**
I crated a pack
Convert it in FS format
Drag and drop the created file in the lunii memory

**Expected behavior**
It worked before, the new stories were in the lunii

**Screenshots**

![Capture d’écran 2024-02-23 113023](https://github.com/marian-m12l/studio/assets/161022709/ece1092b-ded0-4e7d-aef9-6879b72e75ac)

**Logs**
2024-02-23 11:33:13,578 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Number of packs in index: 13
2024-02-23 11:33:13,579 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: cd7e7168-5c39-4cf4-8a13-843ee3d8e79d
2024-02-23 11:33:13,583 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-02-23 11:33:13,592 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 430286d5-ee93-41ca-ac12-e3448a707c89
2024-02-23 11:33:13,595 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-02-23 11:33:13,602 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 61e5658e-0eee-4da1-b4cb-e4ec11f51d4e
2024-02-23 11:33:13,605 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-02-23 11:33:13,612 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 0fd7c1fb-5a32-4039-ba88-d93f18618237
2024-02-23 11:33:13,615 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-02-23 11:33:13,622 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: d489f67b-0e51-4669-b1e1-1555f3c18541
2024-02-23 11:33:13,626 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-02-23 11:33:13,632 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 3ade5403-0625-4fff-a22b-9025ac3678d9
2024-02-23 11:33:13,636 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 2
2024-02-23 11:33:13,644 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 127620b4-09ab-4c0b-a8b6-8f2ce8f8b533
2024-02-23 11:33:13,647 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-02-23 11:33:13,653 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: c4139d59-872a-4d15-8cf1-76d34cdf38c6
2024-02-23 11:33:13,657 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 2
2024-02-23 11:33:13,671 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 4563d17e-fae9-4093-9306-13a14267b26a
2024-02-23 11:33:13,674 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-02-23 11:33:13,682 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: afd29d56-1dc6-475b-94b1-6ed67114305d
2024-02-23 11:33:13,686 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-02-23 11:33:13,696 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 2f0f3109-bfae-4e09-91d7-ca0c2643948d
2024-02-23 11:33:13,699 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-02-23 11:33:13,706 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: f1d57999-06cb-4f94-bcea-8da27f3fff50
2024-02-23 11:33:13,709 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-02-23 11:33:13,717 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 1d33c52d-0945-4de5-8344-69880c0dd0d3
2024-02-23 11:33:13,720 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-02-23 11:33:13,726 [INFO ] [s.w.s.StoryTellerService]: Transferring pack folder to device: C:\Users\R├®mi\.studio\library\1782b2ac-4066-45d6-8d81-6f2f7b157b2b.converted_1708683514069
2024-02-23 11:33:13,730 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Uploading pack to folder: F:\\.content\7B157B2B
2024-02-23 11:33:13,735 [TRACE] [s.d.f.FsStoryTellerAsyncDriver]: Copying file C:\Users\R├®mi\.studio\library\1782b2ac-4066-45d6-8d81-6f2f7b157b2b.converted_1708683514069\li to F:\.content\7B157B2B\li (92 bytes)
2024-02-23 11:33:13,740 [ERROR] [s.w.s.StoryTellerService]: Failed to add pack to device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to copy pack folder
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: studio.driver.StoryTellerException: Failed to copy pack folder
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$copyPackFolder$20(FsStoryTellerAsyncDriver.java:495)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at studio.driver.fs.FsStoryTellerAsyncDriver.copyPackFolder(FsStoryTellerAsyncDriver.java:465)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$uploadPack$12(FsStoryTellerAsyncDriver.java:405)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 6 more
Caused by: java.nio.file.FileAlreadyExistsException: F:\.content\7B157B2B\li
        at java.base/sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:133)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:282)
        at java.base/java.nio.file.Files.copy(Files.java:1303)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$copyPackFolder$20(FsStoryTellerAsyncDriver.java:476)
        ... 19 more

**Desktop and environment (please complete the following information):**
 - OS: Win32 windows 11
 - Browser Crome Version 121.0.6167.185 (Build officiel) (64 bits)
 - STUdio application version: 0.3.1

**Comment by marian-m12l** [comment]
Thanks for the feedback. It looks like your device already contains a folder with the same UUID (see error message "FileAlreadyExistsException: F:.contant\7B157B2B\li"), possibly from en earlier failed transfer. You may remove this folder manually and transfer again.
