### ISSUE TITLE
problème stockage histoire

### ISSUE THREAD

**Issue by Matheoheriquet** [marian-m12l/studio#445]
**Describe the bug**
voir les copies d'écran. merci de me renseigner, cordialement

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**

![image](https://github.com/marian-m12l/studio/assets/162692134/95bcf5b5-e579-4c9b-8f36-8ec6cfcbe124)
![image](https://github.com/marian-m12l/studio/assets/162692134/f1452720-1e99-40fc-b827-cc09f35bdc16)
![image](https://github.com/marian-m12l/studio/assets/162692134/30e62f8e-8ce2-4a49-bfa1-09d76b4a5aab)
> Internal Server Error: Error 500: JsonNull	at com.google.gson.JsonElement.getAsShort(JsonElement.java:304)
	at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:65)
	at studio.webui.service.LibraryService.readMetadata(LibraryService.java:334)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at studio.webui.service.LibraryService.packs(LibraryService.java:99)
	at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:45)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Desktop and environment (please complete the following information):**- 
C:\Users\ledai\OneDrive\Bureau\LUNII\studio-web-ui-0.5.0-dist\studio-web-ui-0.5.0\lib\vorbis-java-1.0.0-beta.jarzilla/5.0 
(Windows NT 11.0; Win64; x64) 
 - STUdio application version: 0.5.0

**Additional context**

**Comment by marian-m12l** [comment]
Merci pour le retour. Votre bibliothèque contient potentiellement un pack d'histoire corrompu ?
