### ISSUE TITLE
PROBLEME : echec de la recuperation des packs d'histoire de l'appareil

### ISSUE THREAD

**Issue by AndrejP82** [marian-m12l/studio#449]
Bonjour,
depuis hier les packs présents sur ma lunii ne sont plus visibles. J'ai redémarré plusieurs fois windows, changé l'entrée USB mais rien ne change . à chaque fois j'ai le même message "echec de la recuperation des packs d'histoire de l'appareil"
Auriez-vous une idée du problème?
![lunii_error](https://github.com/marian-m12l/studio/assets/167515787/af7cb946-7aa6-496c-9f98-70292a2b33bc)

> Internal Server Error: Error 500: studio.core.v1.utils.exception.StoryTellerException: Failed to read pack metadata on device partition	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.5.2

**Comment by AndrejP82** [comment]
> Bonjour, depuis hier les packs présents sur ma lunii ne sont plus visibles. J'ai redémarré plusieurs fois windows, changé l'entrée USB mais rien ne change . à chaque fois j'ai le même message "echec de la recuperation des packs d'histoire de l'appareil" Auriez-vous une idée du problème? ![lunii_error](https://private-user-images.githubusercontent.com/167515787/323885315-af7cb946-7aa6-496c-9f98-70292a2b33bc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NDg5NTgsIm5iZiI6MTcxMzY0ODY1OCwicGF0aCI6Ii8xNjc1MTU3ODcvMzIzODg1MzE1LWFmN2NiOTQ2LTdhYTYtNDk2Yy05Zjk4LTcwMjkyYTJiMzNiYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQyMTMwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2JhNzNkZmZlMjlhNTZiYTcyZThmZTRkYTkzNmM5NTkzYjZiNjhmODY0YmM4NmZmMmFjZDM5ZTg1ZTY4OWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4s6-MPisMYLX8UdVtp8M6RR0E5BK5cU9gOoMR8TFDMI)
> 
> > Internal Server Error: Error 500: studio.core.v1.utils.exception.StoryTellerException: Failed to read pack metadata on device partition	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
> > at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
> > at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
> > at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
> > at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
> > at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
> > at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
> > at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
> > at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
> > at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
> > at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
> 
> **Desktop and environment (please complete the following information):**
> 
> * OS: Win32
> * Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0
> * Java version: [e.g. JDK 11.0.6]
> * Maven version: [e.g. 3.6.0]
> * STUdio application version: 0.5.2

**Comment by AndrejP82** [comment]
J'ai résolu le problème. Celà venait d'un fichier corrompu. Vu que je ne parvenais plus à visualiser les fichiers présents sur la lunii, j'ai téléchargé le logiciel lunii.QT qui permet de gérer ses fichiers. Là les fichiers apparaissaient, notamment un uploadé récemment dont la taille était de 0ko. Je l'ai supprimé et tout à fonctionné. J'ai pû visualiser les fichiers sur studio et en uploader de nouveaux.
