### ISSUE TITLE
Echec de la récupération des packs d'histoires de l'appareil

### ISSUE THREAD

**Issue by Notwilly34** [marian-m12l/studio#453]
Je n'arrive plus a recupérer les histoires sur l'appareil. 
La seconde conséquence est que je ne peut plus ajouter d'histoire sur l'appareil non plus.

J'ai pourtant bien fait les mis a jour java mais rien a faire.

Pouvez vous m'aider ?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> Internal Server Error: Error 500: studio.core.v1.utils.exception.StoryTellerException: Failed to read pack metadata on device partition	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.5.0

**Additional context**

**Comment by Didzzzzz** [comment]
Bonjour,

J'ai le même problème que vous, auriez-vous trouvé une solution depuis ?

Merci d'avance et bonne soirée à vous.

**Comment by marian-m12l** [comment]
Bonjour. Merci pour le retour. Il n'y a pas plus de logs d'erreur ? Notamment une ligne "caused by" qui pourrait indiquer le problème source.
Est-ce que vous utilisez un fork ? La dernière version sur ce dépôt est la 0.4.0

**Comment by Phallardel** [comment]
@marian-m12l 
Quelle est la solution alors ? j'ai exactement le même problème de lecture de la Lunii et ajout de packs
