### ISSUE TITLE
Lunii V3 - library refresh fails

### ISSUE THREAD

**Issue by mikhailo34** [marian-m12l/studio#468]
**Describe the bug**
After adding 3 stories (which makes it total 4 with the default one), it is impossible to add more. When trying to import a new pack, or even on launch of the app, error message appears: "Failed to refresh library
![2024-08-09 22_34_31-STUdio - Story Teller Unleashed — Mozilla Firefox](https://github.com/user-attachments/assets/1ef7e5f6-f6e5-41e7-b6ec-2996737db36c)
".

**Logs**
`        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
2024-08-09 22:30:06,597 [INFO ] [s.w.s.StoryTellerService]: Setting up story teller driver
2024-08-09 22:30:06,601 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: Registering hotplug listener
2024-08-09 22:30:06,601 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2024-08-09 22:30:06,617 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2024-08-09 22:30:06,617 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2024-08-09 22:30:06,621 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Registering hotplug listener
2024-08-09 22:30:06,621 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2024-08-09 22:30:06,621 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2024-08-09 22:30:06,621 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2024-08-09 22:30:06,638 [INFO ] [s.d.LibUsbActivePollingWorker]: Active polling found a new device. Firing event.
2024-08-09 22:30:06,638 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Waiting for device partition...
2024-08-09 22:30:06,685 [INFO ] [s.w.MainVerticle]: Opening URL in default browser...
2024-08-09 22:30:06,774 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle
2024-08-09 22:30:07,477 [ERROR] [s.w.MainVerticle]: Exception thrown
java.nio.channels.ClosedChannelException
        at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
        at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.write(WebSocketServerExtensionHandler.java:151)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
        at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:124)
        at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:205)
        at io.vertx.core.http.impl.Http1xServerConnection.writeToChannel(Http1xServerConnection.java:267)
        at io.vertx.core.net.impl.ConnectionBase.sendFileRegion(ConnectionBase.java:417)
        at io.vertx.core.net.impl.ConnectionBase.sendFile(ConnectionBase.java:444)
        at io.vertx.core.http.impl.Http1xServerConnection.sendFile(Http1xServerConnection.java:456)
        at io.vertx.core.http.impl.HttpServerResponseImpl.doSendFile(HttpServerResponseImpl.java:514)
        at io.vertx.core.http.impl.HttpServerResponseImpl.sendFile(HttpServerResponseImpl.java:433)
        at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:365)
        at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:351)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendFile$11(StaticHandlerImpl.java:457)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.wrapInTCCLSwitch(StaticHandlerImpl.java:266)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.sendFile(StaticHandlerImpl.java:392)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$null$0(StaticHandlerImpl.java:231)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.getFileProps(StaticHandlerImpl.java:299)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:208)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1570)
2024-08-09 22:30:07,650 [INFO ] [s.d.f.FsStoryTellerAsyncDriver]: FS device partition located: D:\
2024-08-09 22:30:07,650 [INFO ] [s.w.s.StoryTellerService]: Device 2.x plugged
2024-08-09 22:30:07,653 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Firmware version: 3.1
2024-08-09 22:30:07,654 [INFO ] [s.d.f.FsStoryTellerAsyncDriver]: Serial Number: 23023040005105
2024-08-09 22:30:07,656 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: UUID: 3233303233303430303035313035000000000000000000003233303233303430239bc5175ebf60ec15ae06278482759ca71e2ca74e9a8b4ebb021ede7be9d1ba
2024-08-09 22:30:07,660 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card size: 7939817472
2024-08-09 22:30:07,660 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card used space: 190676992
2024-08-09 22:30:07,677 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Number of packs in index: 4
2024-08-09 22:30:07,678 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 3d411a00-3437-4939-a60d-71b038260255
2024-08-09 22:30:07,682 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 2
2024-08-09 22:30:07,693 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 00cf78ed-00ce-4d3a-a848-4910ddbc692e
2024-08-09 22:30:07,694 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-08-09 22:30:07,699 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 15924fbd-229d-4efc-80c2-4383304d64a4
2024-08-09 22:30:07,700 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-08-09 22:30:07,703 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: fa7050b8-1a17-4ce5-9b4b-b1ee59b23073
2024-08-09 22:30:07,704 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-08-09 22:30:08,093 [ERROR] [s.w.MainVerticle]: Exception thrown
java.lang.IllegalArgumentException: malformed input off : 15, length : 1
        at java.base/java.lang.String.throwMalformed(String.java:1291)
        at java.base/java.lang.String.decodeUTF8_UTF16(String.java:1247)
        at java.base/java.lang.String.newStringUTF8NoRepl(String.java:772)
        at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2495)
        at java.base/java.util.zip.ZipCoder$UTF8ZipCoder.toString(ZipCoder.java:270)
        at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:91)
        at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:519)
        at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:153)
        at studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:41)
        at studio.webui.service.LibraryService.readPackFile(LibraryService.java:440)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2688)
        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1918)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2686)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2669)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
        at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
        at studio.webui.service.LibraryService.lambda$packs$2(LibraryService.java:99)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:194)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:194)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:702)
        at studio.webui.service.LibraryService.packs(LibraryService.java:103)
        at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:40)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        ... 37 more
`

**Desktop and environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox, Chrome
 - Java version: JDK 22.0.2.0
 - STUdio application version: 0.4.0

**Comment by mkay1905** [comment]
Same issue there, lunii v3 and i can't add any pack into STUdio 0.4.0, win11.

**Comment by marian-m12l** [comment]
Ce type d'erreur indique généralement que le dossier `library` contient une archive qui n'est pas au format STUdio.

**Comment by mkay1905** [comment]
> Ce type d'erreur indique généralement que le dossier `library` contient une archive qui n'est pas au format STUdio.

Merci pour ton aide.
Effectivement, j'ai supprimé le dossier library est maintenant ça fonctionne !

**Comment by marian-m12l** [comment]
En remettant un par un les packs dans le dossier, il est possible d'identifier le fichier problématique, potentiellement une archive zip corrompue.
Idéalement STUdio devrait pouvoir gérer l'erreur...

**Comment by marian-m12l** [comment]
Je viens de publier un petit correctif qui devrait rendre l'erreur plus claire et ne plus faire planter la lecture de la bibliothèque quand un fichier est défectueux.

**Comment by mikhailo34** [comment]
Merci beaucoup, j'ai viré le contenu du library, et effectivement ça a débloqué la chose. Pas vu le correctif en ligne, en revanche, mais je suis tout fraichement inscrit sur Github.

**Comment by marian-m12l** [comment]
Pour tester le correctif, deux possibilités :
- cloner le dépôt git et compiler vous-même
- télécharger l'artifact généré lar l'intégration continue dans les actions github (par exemple ici pour la dernioère exécution : https://github.com/marian-m12l/studio/actions/runs/10332786536)

**Comment by mikhailo34** [comment]
Merci (y)

**Comment by marian-m12l** [comment]
La nouvelle version 0.4.1 devrait être plus robuste à ce niveau-là.
