### ISSUE TITLE
Deploying error : "Failed to create cache dir"

### ISSUE THREAD

**Issue by jin146** [marian-m12l/studio#47]
Hi, 
while trying to deploy the latest version I encounter this error : 
```
$ sh studio-linux.sh
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
avr. 03, 2020 1:06:26 PM io.vertx.core.impl.launcher.commands.RunCommand
GRAVE: Failed to create the vert.x instance
java.lang.IllegalStateException: Failed to create cache dir
	at io.vertx.core.file.impl.FileResolver.setupCacheDir(FileResolver.java:332)
	at io.vertx.core.file.impl.FileResolver.<init>(FileResolver.java:87)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:168)
	at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:93)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:34)
	at io.vertx.core.Vertx.vertx(Vertx.java:85)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.create(ClasspathHandler.java:113)
	at io.vertx.core.impl.launcher.commands.BareCommand.startVertx(BareCommand.java:278)
	at io.vertx.core.impl.launcher.commands.BareCommand.run(BareCommand.java:192)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:249)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:361)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
	at io.vertx.core.Launcher.main(Launcher.java:45)
```

**Comment by marian-m12l** [comment]
Hi,

Looks like a permission issue. Some file are extracted to a temporary file by Vert.x. Can you check the permission for your temp folder (`/tmp` should be the default) ?

**Comment by jin146** [comment]
Yep, solved ! Thank you !
It was indeed a permission issue : doing `ls -l /tmp` helped me realize there was a "vertx-cache" folder owned by root, probably created when I tried `sudo sh studio-linux.sh` wich doesn't work as the assets are in my personal folder. After removing the folder and relaunching the script everything went fine.
Maybe editing the readme with "don't sudo when deploying" would help others. I may do this, but am a beginner in git.
