### ISSUE TITLE
Problem converting

### ISSUE THREAD

**Issue by venezia85** [marian-m12l/studio#472]
Hello, I cannot convert the file to FS format either by clicking on the icon or by dragging the file to the device

Log :
     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at studio.core.v1.utils.PackAssetsCompression.processAudioAssets(PackAssetsCompression.java:178)
        at studio.core.v1.utils.PackAssetsCompression.processFirmware2dot4(PackAssetsCompression.java:117)
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:252)
        ... 10 more
Caused by: javax.sound.sampled.UnsupportedAudioFileException: Stream of unsupported format
        at java.desktop/javax.sound.sampled.AudioSystem.getAudioFileFormat(Unknown Source)
        at studio.core.v1.utils.PackAssetsCompression.lambda$processFirmware2dot4$5(PackAssetsCompression.java:127)
        at studio.core.v1.utils.stream.ThrowingFunction.lambda$unchecked$0(ThrowingFunction.java:24)
        ... 28 more
2024-08-23 09:53:54,458 [ERROR] [s.w.MainVerticle]: Exception thrown
java.lang.NullPointerException
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.nio.file.Path.resolve(Unknown Source)
        at studio.webui.api.DeviceController.lambda$apiRouter$8(DeviceController.java:56)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)

can anyone help me to resolve this problem?
![problem Studio](https://github.com/user-attachments/assets/05b493d1-1966-4696-8f5a-61b280e3a02d)

**Comment by marian-m12l** [comment]
This error message means the story pack uses an audio file of an unsupported format.

**Comment by marian-m12l** [comment]
Closing issue, see #473
