### ISSUE TITLE
Not working with Firmware version 3.1.5?

### ISSUE THREAD

**Issue by chickentuna** [marian-m12l/studio#476]
**Describe the bug**

**To Reproduce**
1. Buy brand new storybox (Firmware version 3.1.5)
2. Try to fetch official pack: Failed to fetch + device is now empty.
3. Try to add a custom pack: Failed to add pack
4. Edit a pack, convert it, its name is replace by a handle and the thumbnail is deleted.

**Desktop and environment (please complete the following information):**
 - OS: Win64

**Logs**

on startup

```
        1 file(s) copied.
2024-08-29 09:28:34,065 [INFO ] [s.w.s.StoryTellerService]: Setting up story teller driver
2024-08-29 09:28:34,072 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: Registering hotplug listener
2024-08-29 09:28:34,073 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2024-08-29 09:28:34,093 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2024-08-29 09:28:34,093 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2024-08-29 09:28:34,098 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Registering hotplug listener
2024-08-29 09:28:34,109 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2024-08-29 09:28:34,109 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2024-08-29 09:28:34,109 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2024-08-29 09:28:34,205 [INFO ] [s.w.MainVerticle]: Opening URL in default browser...
2024-08-29 09:28:34,420 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle
2024-08-29 09:28:54,135 [INFO ] [s.d.LibUsbActivePollingWorker]: Active polling found a new device. Firing event.
2024-08-29 09:28:54,137 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Waiting for device partition...
2024-08-29 09:28:55,159 [INFO ] [s.d.f.FsStoryTellerAsyncDriver]: FS device partition located: F:\
2024-08-29 09:28:55,160 [INFO ] [s.w.s.StoryTellerService]: Device 2.x plugged
2024-08-29 09:28:55,165 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Firmware version: 3.1
2024-08-29 09:28:55,166 [INFO ] [s.d.f.FsStoryTellerAsyncDriver]: Serial Number: 23424020000416
2024-08-29 09:28:55,169 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: UUID: 3233343234303230303030343136000000000000000000003233343234303230c7837b111d99254a3e62a48d97a921b8035652e780ba57e9609746bf0b919dac
2024-08-29 09:28:55,171 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card size: 7939817472
2024-08-29 09:28:55,172 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card used space: 97550336
2024-08-29 09:28:55,188 [ERROR] [s.w.a.DeviceController]: Failed to read packs from device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:305)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 6 more
Caused by: java.io.FileNotFoundException: F:\.pi (The system cannot find the file specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:291)
        ... 7 more
2024-08-29 09:28:55,199 [ERROR] [s.w.MainVerticle]: Exception thrown
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:305)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 6 more
Caused by: java.io.FileNotFoundException: F:\.pi (The system cannot find the file specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:291)
        ... 7 more
```

on pack add

```
2024-08-29 09:30:30,755 [ERROR] [s.w.a.DeviceController]: Failed to transfer pack to device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:305)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 6 more
Caused by: java.io.FileNotFoundException: F:\.pi (The system cannot find the file specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:291)
        ... 7 more
2024-08-29 09:30:30,758 [ERROR] [s.w.MainVerticle]: Exception thrown
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: studio.driver.StoryTellerException: Failed to read pack index on device partition
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:305)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 6 more
Caused by: java.io.FileNotFoundException: F:\.pi (The system cannot find the file specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$readPackIndex$1(FsStoryTellerAsyncDriver.java:291)
        ... 7 more

```

**Comment by marian-m12l** [comment]
Hi,

It looks like STUdio does not find `.pi` file (the index of installed story packs) in your device's partition. Can you see it when the device is plugged and mounted?

**Comment by chickentuna** [comment]
> It looks like STUdio does not find `.pi` file (the index of installed story packs) in your device's partition. Can you see it when the device is plugged and mounted?

Yes I can see it:
![image](https://github.com/user-attachments/assets/0b35715a-2e19-4d0b-8590-43742ec0e801)

I'm using the latest release, do you recommend I build the project from source maybe?

**Comment by chickentuna** [comment]
There must be something wrong with my windows set up, I'll try and figure out what exactly if maybe it can help; On my linux pc I'm having zero trouble so far

**Comment by marian-m12l** [comment]
Yes, there may be something preventing access to the file, possibly antivirus software or the likes?
I can only encourage using STUdio on linux of course :+1: 
I'm closing the issue, but feel free to reopen should it happen again.
