### ISSUE TITLE
Can't import packs if moving library to D drive

### ISSUE THREAD

**Issue by christopheparis** [marian-m12l/studio#484]
**Describe the bug**
I tried to move the library to a different drive to save space on C Drive.
When doing this, I get in the GUI the right message displayed however when to try to import a pack from a zip,I get a confirmation but the pack won't appear and the import will fail.
I checked folder permission the path has no special characters or spaces and it exists. I tried with quotes and without.

**To Reproduce**
1. Studio path
2. Edit Windows BAT and change command to : 
`java -Dvertx.disableDnsResolver=true -Dstudio.library=D:/Lunii/library -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -Dfile.encoding=UTF-8 -cp "%STUDIO_PATH%/studio-web-ui-0.4.1.jar";"%STUDIO_PATH%/lib/*";. io.vertx.core.Launcher run studio.webui.MainVerticle`
3. Run the BAT
4. Click the icon to import and pick a ZIP

**Expected behavior**
The ZIP should be imported.

**Screenshots**

![Capture d'écran 2024-09-16 135735](https://github.com/user-attachments/assets/e50f6e3b-58b0-4d95-8ef3-081db3ef7147)

**Logs**

[studio-20240916-10.log](https://github.com/user-attachments/files/17012728/studio-20240916-10.log)

**Desktop and environment (please complete the following information):**
 - OS: Win 11
 - Browser Firefox
 - Java version: Java(TM) SE Runtime Environment (build 22.0.2+9-70)
 - Maven version: 
 - STUdio application version [e.g. 0.4.1]

**Additional context**
Works fine when I remove Dstudio.librar

**Comment by christopheparis** [comment]
Il fallait mettre un / à la fin... 🤦‍♂️

**Comment by christopheparis** [comment]
Ah par contre la conversion ne marche pas sur D mais marche sur c

```
2024-09-16 14:48:47,396 [INFO ] [studio.webui.service.LibraryService] [LibraryService.java:312]: Pack to transfer is in archive format. Converting to FS format and storing in temporary folder: C:\Users\Christophe\.studio\tmp\pack.zip4603751635849360852
2024-09-16 14:48:47,396 [INFO ] [studio.webui.service.LibraryService] [LibraryService.java:314]: Reading archive format pack
2024-09-16 14:48:47,526 [INFO ] [studio.webui.service.LibraryService] [LibraryService.java:321]: Converting assets if necessary
2024-09-16 14:48:47,528 [DEBUG] [studio.core.v1.utils.ID3Tags] [ID3Tags.java:61]: Removing ID3v2 tag at beginning of file (143 bytes).
2024-09-16 14:48:47,528 [DEBUG] [studio.core.v1.utils.ID3Tags] [ID3Tags.java:61]: Removing ID3v2 tag at beginning of file (44 bytes).
2024-09-16 14:48:47,532 [DEBUG] [studio.core.v1.utils.PackAssetsCompression] [PackAssetsCompression.java:160]: Converting image asset into 4-bits/RLE BMP
2024-09-16 14:48:47,712 [DEBUG] [studio.core.v1.utils.ID3Tags] [ID3Tags.java:61]: Removing ID3v2 tag at beginning of file (44 bytes).
2024-09-16 14:48:47,736 [DEBUG] [studio.core.v1.utils.PackAssetsCompression] [PackAssetsCompression.java:160]: Converting image asset into 4-bits/RLE BMP
2024-09-16 14:48:47,856 [DEBUG] [studio.core.v1.utils.ID3Tags] [ID3Tags.java:61]: Removing ID3v2 tag at beginning of file (44 bytes).
2024-09-16 14:48:47,884 [DEBUG] [studio.core.v1.utils.PackAssetsCompression] [PackAssetsCompression.java:160]: Converting image asset into 4-bits/RLE BMP
2024-09-16 14:48:48,006 [DEBUG] [studio.core.v1.utils.ID3Tags] [ID3Tags.java:61]: Removing ID3v2 tag at beginning of file (44 bytes).
2024-09-16 14:48:48,031 [DEBUG] [studio.core.v1.utils.PackAssetsCompression] [PackAssetsCompression.java:160]: Converting image asset into 4-bits/RLE BMP
2024-09-16 14:48:48,108 [DEBUG] [studio.core.v1.utils.ID3Tags] [ID3Tags.java:61]: Removing ID3v2 tag at beginning of file (44 bytes).
2024-09-16 14:48:48,132 [INFO ] [studio.webui.service.LibraryService] [LibraryService.java:324]: Writing FS format pack
2024-09-16 14:48:48,358 [INFO ] [studio.webui.service.LibraryService] [LibraryService.java:330]: Moving FS format pack into local library: D:\Lunii\library\1d4565b8-fa11-4e56-b3ce-b6c625e37fba.converted_1726490928358
2024-09-16 14:48:48,362 [ERROR] [studio.webui.service.LibraryService] [LibraryService.java:335]: Failed to convert archive format pack to FS format
java.nio.file.DirectoryNotEmptyException: C:\Users\Christophe\.studio\tmp\pack.zip4603751635849360852\25E37FBA
	at java.base/sun.nio.fs.WindowsFileCopy.ensureEmptyDir(WindowsFileCopy.java:276)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:440)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:291)
	at java.base/java.nio.file.Files.move(Files.java:1430)
	at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:331)
	at studio.webui.api.LibraryController$2.run(LibraryController.java:102)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:571)
	at java.base/java.util.TimerThread.run(Timer.java:521)
```

**Comment by marian-m12l** [comment]
Est-ce que configurer le dossier temporaire sur le même disque règle le problème ? Par exemple `-Dstudio.tmpdir=D:/Lunii/tmp` ?
