### ISSUE TITLE
Issue with RollingFileManager on system startup

### ISSUE THREAD

**Issue by JonathanOMT** [marian-m12l/studio#49]
Hi, 
I tried to use studio on Linux Mint without building it myself. I followed steps recommended and everything went well until the 'Starting the application'.

When I start the application with ./studio-linux.sh, I get an error message (see below for log).
I am running this from an account with no root or admin privilege. I also tried to run the same with sudo but it didn't help.

Any idea of what might be causing this?

Thanks

Jonathan
ps: I have the openjdk-11-jre debian package

2020-04-11 11:12:15,517 main ERROR RollingFileManager (studio-latest.log) java.io.FileNotFoundException: studio-latest.log (Permission non accordée) java.io.FileNotFoundException: studio-latest.log (Permission non accordée)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:158)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:640)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:608)
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:113)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:114)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:188)
	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:145)
	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:61)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:123)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:959)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:899)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:891)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:514)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:238)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:250)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:547)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:619)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:636)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:231)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:243)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:648)
	at io.vertx.core.logging.Log4j2LogDelegate.<init>(Log4j2LogDelegate.java:31)
	at io.vertx.core.logging.Log4j2LogDelegateFactory.createDelegate(Log4j2LogDelegateFactory.java:28)
	at io.vertx.core.logging.LoggerFactory.getLogger(LoggerFactory.java:74)
	at io.vertx.core.logging.LoggerFactory.getLogger(LoggerFactory.java:67)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.<init>(ClasspathHandler.java:45)
	at io.vertx.core.impl.launcher.commands.BareCommand.<init>(BareCommand.java:49)
	at io.vertx.core.impl.launcher.commands.RunCommand.<init>(RunCommand.java:39)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.vertx.core.cli.impl.ReflectionUtils.newInstance(ReflectionUtils.java:32)
	at io.vertx.core.spi.launcher.DefaultCommandFactory.create(DefaultCommandFactory.java:44)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.getNewCommandInstance(VertxCommandLauncher.java:158)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:213)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:361)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
	at io.vertx.core.Launcher.main(Launcher.java:45)

2020-04-11 11:12:15,564 main ERROR Could not create plugin of type class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile: java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@6200f9cb] unable to create manager for [studio-latest.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@2002fc1d[pattern=studio-%d{yyyyMMdd}-%i.log, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[OnStartupTriggeringPolicy]), strategy=DefaultRolloverStrategy(min=1, max=10, useMax=true), advertiseURI=null, layout=%date [%-5level] [%logger] [%file:%line]: %msg%n%throwable, filePermissions=null, fileOwner=null]] java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@6200f9cb] unable to create manager for [studio-latest.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@2002fc1d[pattern=studio-%d{yyyyMMdd}-%i.log, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[OnStartupTriggeringPolicy]), strategy=DefaultRolloverStrategy(min=1, max=10, useMax=true), advertiseURI=null, layout=%date [%-5level] [%logger] [%file:%line]: %msg%n%throwable, filePermissions=null, fileOwner=null]]
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:115)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:114)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:188)
	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:145)
	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:61)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:123)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:959)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:899)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:891)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:514)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:238)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:250)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:547)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:619)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:636)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:231)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:243)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:648)
	at io.vertx.core.logging.Log4j2LogDelegate.<init>(Log4j2LogDelegate.java:31)
	at io.vertx.core.logging.Log4j2LogDelegateFactory.createDelegate(Log4j2LogDelegateFactory.java:28)
	at io.vertx.core.logging.LoggerFactory.getLogger(LoggerFactory.java:74)
	at io.vertx.core.logging.LoggerFactory.getLogger(LoggerFactory.java:67)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.<init>(ClasspathHandler.java:45)
	at io.vertx.core.impl.launcher.commands.BareCommand.<init>(BareCommand.java:49)
	at io.vertx.core.impl.launcher.commands.RunCommand.<init>(RunCommand.java:39)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.vertx.core.cli.impl.ReflectionUtils.newInstance(ReflectionUtils.java:32)
	at io.vertx.core.spi.launcher.DefaultCommandFactory.create(DefaultCommandFactory.java:44)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.getNewCommandInstance(VertxCommandLauncher.java:158)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:213)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:361)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
	at io.vertx.core.Launcher.main(Launcher.java:45)

2020-04-11 11:12:15,628 main ERROR Unable to invoke factory method in class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile: java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingFileAppender java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingFileAppender
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:235)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:135)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:959)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:899)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:891)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:514)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:238)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:250)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:547)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:619)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:636)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:231)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:243)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:648)
	at io.vertx.core.logging.Log4j2LogDelegate.<init>(Log4j2LogDelegate.java:31)
	at io.vertx.core.logging.Log4j2LogDelegateFactory.createDelegate(Log4j2LogDelegateFactory.java:28)
	at io.vertx.core.logging.LoggerFactory.getLogger(LoggerFactory.java:74)
	at io.vertx.core.logging.LoggerFactory.getLogger(LoggerFactory.java:67)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.<init>(ClasspathHandler.java:45)
	at io.vertx.core.impl.launcher.commands.BareCommand.<init>(BareCommand.java:49)
	at io.vertx.core.impl.launcher.commands.RunCommand.<init>(RunCommand.java:39)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.vertx.core.cli.impl.ReflectionUtils.newInstance(ReflectionUtils.java:32)
	at io.vertx.core.spi.launcher.DefaultCommandFactory.create(DefaultCommandFactory.java:44)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.getNewCommandInstance(VertxCommandLauncher.java:158)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:213)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:361)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
	at io.vertx.core.Launcher.main(Launcher.java:45)

2020-04-11 11:12:15,685 main ERROR Null object returned for RollingFile in Appenders.
2020-04-11 11:12:15,785 main ERROR Unable to locate appender "RollingFile" for logger config "root"
2020-04-11 11:12:15,788 main ERROR Unable to locate appender "RollingFile" for logger config "studio"
com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 2 column 1 path $.-M4KG_qZGfRomDK3oxhk
	at com.google.gson.internal.Streams.parse(Streams.java:58)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:35)
	at studio.webui.MainVerticle.start(MainVerticle.java:48)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: End of input at line 2 column 1 path $.-M4KG_qZGfRomDK3oxhk
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1401)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:482)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 14 more
2020-04-11 11:12:18,446 [ERROR] [i.v.c.i.l.c.VertxIsolatedDeployer]: Failed in deploying verticle
com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 2 column 1 path $.-M4KG_qZGfRomDK3oxhk
	at com.google.gson.internal.Streams.parse(Streams.java:58)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:35)
	at studio.webui.MainVerticle.start(MainVerticle.java:48)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: End of input at line 2 column 1 path $.-M4KG_qZGfRomDK3oxhk
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1401)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:482)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 14 more
com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 2 column 1 path $.-M4KG_qZGfRomDK3oxhk
	at com.google.gson.internal.Streams.parse(Streams.java:58)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:35)
	at studio.webui.MainVerticle.start(MainVerticle.java:48)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: End of input at line 2 column 1 path $.-M4KG_qZGfRomDK3oxhk
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1401)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:482)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 14 more

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

**Desktop and environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version [e.g. 0.1.11]

**Additional context**

**Comment by marian-m12l** [comment]
Hi, and thanks for the feedback. It looks like you have two errors:
- The app fails to create a log file. It tries to create studio-latest.log in-place. Did you run the script from the folder where its located or from another place? Can you also double-check the permissions of the folder containing the script? I'm not sure this error prevents the app from running correctly (apart from logging to file).
- Your metadata database file (located in `~/.studio/db/official.json`) cannot be read. It may be corrupted (or the Luniistore may have changed the file format since I last checked it). Can you check it and/or fetch it again from the Luniistore?
