### ISSUE TITLE
Contents of the lunii will no longer show up in Studio

### ISSUE THREAD

**Issue by MimiToucas** [marian-m12l/studio#493]
Studio will no longer display the contents of the lunii
![image](https://github.com/user-attachments/assets/0c4bce18-f5ff-482b-983c-2c85bbd86cee)

**Details of the problem**
I was copying packs into the lunii. Everything was going ok. I noticed an original packed copied twice in the machine. I deleted one of the 2 identical packs but I got an error message (which I can't remember exactly)
I later removed the machine. When wanting to resume copying packs onto the machine after a while, I could no longer see the contents of the machine It displays the message shown in the image above each time I connect the lunii. Tried to relaunch studio, stop the lunii and start it again, connect disconnect...nothing will work. The contents will no longer display. I tried with a different machine and no problem, everything works fine.
The log shows an error when loading the contents (Failed to read packs from device) but I am not able to comprehend how to fix the bug. The described file from the log is nowhere to be found in the machine

**Expected behavior**
I should see the contents of the lunii in the left side of Studio

**Screenshots**
![image](https://github.com/user-attachments/assets/6729cd5a-8292-466a-84fb-8adb0f1f55a0)

**Logs**
2024-10-16 18:25:58,975 [INFO ] [s.d.LibUsbActivePollingWorker]: Active polling found a new device. Firing event.
2024-10-16 18:25:58,975 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Waiting for device partition...
2024-10-16 18:25:59,996 [INFO ] [s.d.f.FsStoryTellerAsyncDriver]: FS device partition located: E:\
2024-10-16 18:25:59,996 [INFO ] [s.w.s.StoryTellerService]: Device 2.x plugged
2024-10-16 18:25:59,996 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Firmware version: 2.22
2024-10-16 18:25:59,996 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Serial Number: 9027129019734085
2024-10-16 18:25:59,996 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: UUID: 50d90c1c3723dbfda1f646e1f41f2eb26e4c8c5a05ef846e0039d097aa62a620ca645e5b2482d55cb69f087c85d8e2fdb640f9036b0ff5b531d0e790c06bbdb83bd7d461f8cb9825744e017c25b955241bfe190e11e975718cccb913fab2d8a078bc677f37f375abffc1fda5f016041ae28a28a6cd7151cddecd46687ef3a5c4b08024210955dee7842b0c687a5dec2d446322273a9a5a0098a1d28d669427a3c021c719d2ef29200f835e5a5758f079c6369603c8f1f23475f10d574ecd2903916a93874f2096980c262f06ae996f2ad6695fca405a4a57d16caabb470616004620fa4e3c0f70b4d65ab7460edc7d01dbf45c34a7d8f69653bde85b27f029a6
2024-10-16 18:26:00,012 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card size: 7939817472
2024-10-16 18:26:00,012 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: SD card used space: 1029603328
2024-10-16 18:26:00,041 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Number of packs in index: 17
2024-10-16 18:26:00,042 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: c4139d59-872a-4d15-8cf1-76d34cdf38c6
2024-10-16 18:26:00,049 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 2
2024-10-16 18:26:00,077 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 4563d17e-fae9-4093-9306-13a14267b26a
2024-10-16 18:26:00,082 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-10-16 18:26:00,092 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: aa0bc5dd-16fa-4362-859c-0db158139fe6
2024-10-16 18:26:00,092 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-10-16 18:26:00,108 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: f0428504-4aab-468c-b995-db88c8c907af
2024-10-16 18:26:00,108 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-10-16 18:26:00,123 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 422fb92b-8026-4e74-b500-0b03fba79e1d
2024-10-16 18:26:00,123 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-10-16 18:26:00,139 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 3712af6d-cf9d-4154-8e98-56821362862a
2024-10-16 18:26:00,139 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-10-16 18:26:00,155 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: ce80a2b6-9f62-47f1-82d8-396c24d70175
2024-10-16 18:26:00,155 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack version: 1
2024-10-16 18:26:00,170 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Pack UUID: 59a710e9-2f7a-4d0c-ab2d-47e8dd2e29b7
2024-10-16 18:26:00,170 [ERROR] [s.w.a.DeviceController]: Failed to read packs from device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack metadata on device partition
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: studio.driver.StoryTellerException: Failed to read pack metadata on device partition
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$getPacksList$0(FsStoryTellerAsyncDriver.java:279)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        ... 8 more
Caused by: java.io.FileNotFoundException: E:\.content\DD2E29B7\ni (Le chemin dÔÇÖacc├¿s sp├®cifi├® est introuvable)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$getPacksList$0(FsStoryTellerAsyncDriver.java:260)
        ... 9 more
2024-10-16 18:26:00,170 [ERROR] [s.w.MainVerticle]: Exception thrown
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack metadata on device partition
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: studio.driver.StoryTellerException: Failed to read pack metadata on device partition
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$getPacksList$0(FsStoryTellerAsyncDriver.java:279)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        ... 8 more
Caused by: java.io.FileNotFoundException: E:\.content\DD2E29B7\ni (Le chemin dÔÇÖacc├¿s sp├®cifi├® est introuvable)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
        at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$getPacksList$0(FsStoryTellerAsyncDriver.java:260)
        ... 9 more

**Desktop and environment (please complete the following information):**
 - OS: Windows 10 family
 - Browser: Brave
 - Java version: "20.0.2" 2023-07-18
 - Maven version: N/A
 - STUdio application version: 0.4.1

**Additional context**

**Comment by MimiToucas** [comment]
Forgot to mention that the Lunii works just fine when disconnect from the computer

**Comment by cocodirasta** [comment]
Hello, I think I have the same problem. Yesterday, I was able to read the content of my Lunii V3 for the first time. I unplugged my Lunii, then turned off and restarted the Studio, and I could no longer access the content of my Lunii. I have the logs from when it worked, and I also have the logs from after, which show an error. When looking at the log with the error, I get a line like this:

NoSuchFileException: D:\.content\38260255\ni

And when checking this path with Windows Explorer, I noticed that the file names contain strange characters, as if they were corrupted. It might be an encoding problem. Do you have any ideas on how to solve this issue?

**Screenshot windows explorer at** D:\.content\38260255\
![image](https://github.com/user-attachments/assets/512eaf33-ce72-4b3c-802f-ac95dcea34f2)


**Logs**
2024-10-17 07:32:36,236 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:53]: Setting up story teller driver
2024-10-17 07:32:36,244 [DEBUG] [studio.driver.raw.RawStoryTellerAsyncDriver] [RawStoryTellerAsyncDriver.java:44]: Registering hotplug listener
2024-10-17 07:32:36,247 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:48]: Initializing libusb...
2024-10-17 07:32:36,272 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:73]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2024-10-17 07:32:36,272 [DEBUG] [studio.driver.LibUsbAsyncEventsWorker] [LibUsbAsyncEventsWorker.java:32]: Starting worker thread to handle libusb async events...
2024-10-17 07:32:36,278 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:57]: Registering hotplug listener
2024-10-17 07:32:36,279 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:48]: Initializing libusb...
2024-10-17 07:32:36,280 [INFO ] [studio.driver.LibUsbDetectionHelper] [LibUsbDetectionHelper.java:73]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2024-10-17 07:32:36,280 [DEBUG] [studio.driver.LibUsbAsyncEventsWorker] [LibUsbAsyncEventsWorker.java:32]: Starting worker thread to handle libusb async events...
2024-10-17 07:32:36,416 [INFO ] [studio.webui.MainVerticle] [MainVerticle.java:106]: Opening URL in default browser...
2024-10-17 07:32:36,428 [INFO ] [studio.driver.LibUsbActivePollingWorker] [LibUsbActivePollingWorker.java:65]: Active polling found a new device. Firing event.
2024-10-17 07:32:36,432 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:62]: Waiting for device partition...
2024-10-17 07:32:36,688 [INFO ] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:81]: Succeeded in deploying verticle
2024-10-17 07:32:37,472 [INFO ] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:71]: FS device partition located: D:\
2024-10-17 07:32:37,475 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:113]: Device 2.x plugged
2024-10-17 07:32:37,481 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:182]: Firmware version: 3.1
2024-10-17 07:32:37,482 [INFO ] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:188]: Serial Number: XXXXX
2024-10-17 07:32:37,485 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:210]: UUID: XXXXX
2024-10-17 07:32:37,506 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:139]: SD card size: 7939817472
2024-10-17 07:32:37,508 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:140]: SD card used space: 3855319040
2024-10-17 07:32:37,664 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:182]: Firmware version: 3.1
2024-10-17 07:32:37,669 [INFO ] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:188]: Serial Number: XXXXX
2024-10-17 07:32:37,675 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:210]: UUID: XXXXX
2024-10-17 07:32:37,678 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:139]: SD card size: 7939817472
2024-10-17 07:32:37,680 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:140]: SD card used space: 3855319040
2024-10-17 07:32:37,918 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:246]: Number of packs in index: 70
2024-10-17 07:32:37,921 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:251]: Pack UUID: 2bd0b283-acaf-43d4-b621-3c1c49208c60
2024-10-17 07:32:37,935 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:265]: Pack version: 1
2024-10-17 07:32:38,006 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:251]: Pack UUID: c4139d59-872a-4d15-8cf1-76d34cdf38c6
2024-10-17 07:32:38,008 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:265]: Pack version: 2
2024-10-17 07:32:38,020 [DEBUG] [studio.driver.fs.FsStoryTellerAsyncDriver] [FsStoryTellerAsyncDriver.java:251]: Pack UUID: 3d411a00-3437-4939-a60d-71b038260255
2024-10-17 07:32:38,022 [ERROR] [studio.webui.api.DeviceController] [DeviceController.java:54]: Failed to read packs from device
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack metadata on device partition
	at java.base/java.util.concurrent.CompletableFuture.wrapInCompletionException(CompletableFuture.java:323)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:359)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:364)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:693)
	at java.base/java.util.concurrent.CompletableFuture.unipush(CompletableFuture.java:637)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2244)
	at studio.driver.fs.FsStoryTellerAsyncDriver.getPacksList(FsStoryTellerAsyncDriver.java:244)
	at studio.webui.service.StoryTellerService.packsV2(StoryTellerService.java:216)
	at studio.webui.service.StoryTellerService.packs(StoryTellerService.java:200)
	at studio.webui.api.DeviceController.lambda$apiRouter$5(DeviceController.java:51)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:160)
	at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:235)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:160)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:296)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:276)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:87)
	at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:521)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:507)
	at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:176)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:138)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: studio.driver.StoryTellerException: Failed to read pack metadata on device partition
	at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$getPacksList$0(FsStoryTellerAsyncDriver.java:279)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:690)
	... 51 more
Caused by: java.io.FileNotFoundException: D:\.content\38260255\ni (Le fichier spécifié est introuvable)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:159)
	at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$getPacksList$0(FsStoryTellerAsyncDriver.java:260)
	... 52 more
2024-10-17 07:32:38,026 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
java.util.concurrent.CompletionException: studio.driver.StoryTellerException: Failed to read pack metadata on device partition
	at java.base/java.util.concurrent.CompletableFuture.wrapInCompletionException(CompletableFuture.java:323)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:359)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:364)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:693)
	at java.base/java.util.concurrent.CompletableFuture.unipush(CompletableFuture.java:637)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2244)
	at studio.driver.fs.FsStoryTellerAsyncDriver.getPacksList(FsStoryTellerAsyncDriver.java:244)
	at studio.webui.service.StoryTellerService.packsV2(StoryTellerService.java:216)
	at studio.webui.service.StoryTellerService.packs(StoryTellerService.java:200)
	at studio.webui.api.DeviceController.lambda$apiRouter$5(DeviceController.java:51)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:160)
	at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:235)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:160)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:296)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:276)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:87)
	at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:521)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:507)
	at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:176)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:138)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: studio.driver.StoryTellerException: Failed to read pack metadata on device partition
	at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$getPacksList$0(FsStoryTellerAsyncDriver.java:279)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:690)
	... 51 more
Caused by: java.io.FileNotFoundException: D:\.content\38260255\ni (Le fichier spécifié est introuvable)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:159)
	at studio.driver.fs.FsStoryTellerAsyncDriver.lambda$getPacksList$0(FsStoryTellerAsyncDriver.java:260)
	... 52 more


Desktop and environment (please complete the following information):

OS: Windows 10 family
Browser: Chrome
Java version: "23.0.1" 2024-10-15
Maven version: N/A
STUdio application version: 0.4.1

**Comment by valentinloiseau** [comment]
I have exactly the same issue happened after removed one of the duplicated pack displayed in the device section 😢

**Comment by valentinloiseau** [comment]
I found the problem: for one reason, after removing the duplicated pack, this one is removed but always listed in the node index file. And if one pack cannot be found the content listing is stopped

I found a way to use the Studio with the duplicated pack, look at this release : https://github.com/valentinloiseau/studio/releases/tag/0.5.3

This not fix the duplicated pack issue, but this made my kid stop crying 😅

**Comment by marian-m12l** [comment]
Hi. Thanks for the feedback!
It sounds like the lunii still has a reference to a story pack that was (probably) removed incorrectly. If any of you still has the log file with the error that happened at this point (the failed removal), maybe it could help fix the underlying issue.

**Comment by MimiToucas** [comment]
Hi Marian
The log was copied in the initial request dated Oct 16th. Do you need anything else? I do not have the machine anymore
Do you have a fix suggestion?
Thanks
