### ISSUE TITLE
Setup on windows 10

### ISSUE THREAD

**Issue by gael4910** [marian-m12l/studio#54]
Hello, i would like to install studio web on windows 10 but i don't understand what version of Java i should install ? 
I read :
"Prérequis
Pour exécuter l'application :
JRE 11+"
But when i search on google, i only find JRE 8, version 11 is only available for JDK...

Thanks for your help

**Comment by gael4910** [comment]
with latest JRE i get error while launching studio-windows.bat  : 
**" [ERROR] [i.v.c.i.l.c.RunCommand]: Failed to deploy verticle studio.webui.MainVerticle
java.lang.UnsupportedClassVersionError: studio/webui/MainVerticle has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0"**

**Comment by Bobet21** [comment]
Yep same question here trying to install on Ubuntu 18.04 LTS - got the error

**Comment by Bobet21** [comment]
> Hello, i would like to install studio web on windows 10 but i don't understand what version of Java i should install ?
> I read :
> "Prérequis
> Pour exécuter l'application :
> JRE 11+"
> But when i search on google, i only find JRE 8, version 11 is only available for JDK...
> 
> Thanks for your help

Gael, you may want to try that out 
https://www.journaldunet.fr/web-tech/developpement/1203047-unsupported-major-minor-version-52-0-comment-eviter-cette-erreur/

**Comment by gael4910** [comment]
Is it necessary to recompile the program ? i don't know hox to do it...

**Comment by marian-m12l** [comment]
Hi.
The error message means the Java runtime you are using (Java 8 / 52.0) is too old to run classes compiled with Java 11 (55.0). No need to recompile, you just have to use a Java 11 runtime. I'll need to check what's available to download, but you may need to install the whole JDK 11, if the JRE is not distributed in newer versions.

**Comment by gael4910** [comment]
I already tried JDK 11 and now JDK 14, but always the same error. It seems that it's always JRE 8 that is used to launch your program...

**Comment by marian-m12l** [comment]
The bat script calls the `java` command that is in your path, which may be from the JRE 8 in your case.
You can either fix your path, or get rid of JRE 8 if you don't need it anywhere else. Or you could alter the script to use the explicit path to the correct `java` command.

**Comment by marian-m12l** [comment]
@Bobet21 On Ubuntu, use `sudo update-alternatives --config java` to select your default java runtime

**Comment by gael4910** [comment]
Thank you ! I added "SET PATH=C:\Program Files\Java\jdk-14.0.1\bin" in the BAT file and it works !!
Have a nice week-end
Gaël

**Comment by Bobet21** [comment]
> @Bobet21 On Ubuntu, use `sudo update-alternatives --config java` to select your default java runtime

Thanks, I now have this (even after launching and connecting the official store)

`2020-04-17 15:22:16,051 [ERROR] [s.m.DatabaseMetadataService]: Missing official metadata database file
java.io.FileNotFoundException: /home/louis/.studio/db/official.json (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:212)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:154)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:109)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:35)
	at studio.webui.MainVerticle.start(MainVerticle.java:48)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
2020-04-17 15:22:18,533 [WARN ] [i.v.c.i.BlockedThreadChecker]: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2544 ms, time limit is 2000 ms
2020-04-17 15:22:19,534 [WARN ] [i.v.c.i.BlockedThreadChecker]: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3545 ms, time limit is 2000 ms
2020-04-17 15:22:19,629 [INFO ] [s.w.s.StoryTellerService]: Setting up story teller driver
2020-04-17 15:22:19,721 [INFO ] [c.l.d.g.r.AbstractUsb4JavaLuniiDriver]: Initializing libusb...
2020-04-17 15:22:19,767 [INFO ] [c.l.d.g.r.AbstractUsb4JavaLuniiDriver]: libusb initialized
2020-04-17 15:22:20,533 [WARN ] [i.v.c.i.BlockedThreadChecker]: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4544 ms, time limit is 2000 ms
2020-04-17 15:22:21,052 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle
2020-04-17 15:22:54,159 [INFO ] [c.l.d.g.r.AbstractUsb4JavaLuniiDriver]: Exiting libusb
`

**Comment by marian-m12l** [comment]
@Bobet21 Looks like you're missing `~/.studio/db/official.json`. You need to download the json file and save it manually.

**Comment by Bobet21** [comment]
You are right i only have the unofficial one, where are those file coming from ? where can i find the official.json?

**Comment by marian-m12l** [comment]
You need to fetch the json file from lunii servers, using your (fresh) authentication token. Here's the relevant part from the readme:

> Query https://lunii-data-prod.firebaseio.com/packs.json?auth=TOKEN and save the result as $DOT_STUDIO/db/official.json (e.g. curl -v -X GET https://lunii-data-prod.firebaseio.com/packs.json?auth=TOKEN > ~/.studio/db/official.json)

**Comment by vwasteels** [comment]
hello, i have same issue here on macos 10.14 , 
I'm trying to get the file from lunii but how do you get the token ?
thank you

**Comment by vwasteels** [comment]
Sorry I just saw the explanation in the Readme File ...

Thanks !

**Comment by marian-m12l** [comment]
Don't be sorry :-) Glad you had it working!

**Comment by marian-m12l** [comment]
Closing this issue as it's starting go be a little too crowded :-)
