### ISSUE TITLE
Win10 - USB error

### ISSUE THREAD

**Issue by gael4910** [marian-m12l/studio#55]
On windows 10, I can create storys but my lunii device can't be connected and I get some "LIBUSB_ERROR_NOT_SUPPORTED" when i launch BAT file.
Lunii box is connected and recognized in official "luniistore".

**Screenshots**
https://i.ibb.co/NVyNmqp/2020-04-17-17-09-03-STUdio-Story-Teller-Unleashed.jpg

**Logs**
`2020-04-17 17:06:26,362 [INFO ] [s.w.s.StoryTellerService]: Setting up story teller driver
2020-04-17 17:06:26,368 [INFO ] [c.l.d.g.r.AbstractUsb4JavaLuniiDriver]: Initializing libusb...
2020-04-17 17:06:26,380 [INFO ] [c.l.d.g.r.AbstractUsb4JavaLuniiDriver]: libusb initialized
2020-04-17 17:06:26,392 [INFO ] [c.l.d.g.r.AbstractUsb4JavaLuniiDriver]: New handler detected : Usb4JavaLuniiDevice{path=[2, 0, 0, 0, 0, 0, 2], busNumber=2, portNumber=1, deviceAddress=5, deviceHandle=null, handler=libusb device 0x1b1a9e09130}
2020-04-17 17:06:26,393 [INFO ] [s.w.s.StoryTellerService]: Device plugged
2020-04-17 17:06:26,397 [INFO ] [c.l.d.g.r.AbstractUsb4JavaLuniiDriver]: Get handler handle for handler : Usb4JavaLuniiDevice{path=[2, 0, 0, 0, 0, 0, 2], busNumber=2, portNumber=1, deviceAddress=5, deviceHandle=null, handler=libusb device 0x1b1a9e09130}
2020-04-17 17:06:26,398 [ERROR] [c.l.d.g.r.AbstractUsb4JavaLuniiDriver]: Cannot get handle for handler, code : LIBUSB_ERROR_NOT_SUPPORTED
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.resolver.dns.DnsNameResolver (file:/C:/studio-web-ui-0.1.13/lib/netty-resolver-dns-4.1.30.Final.jar) to method sun.net.dns.ResolverConfiguration.open()
WARNING: Please consider reporting this to the maintainers of io.netty.resolver.dns.DnsNameResolver
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-04-17 17:06:26,564 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle
2020-04-17 17:06:31,404 [ERROR] [c.l.d.g.r.AbstractUsb4JavaLuniiDriver]: Cannot get handle for handler, code : LIBUSB_ERROR_NOT_SUPPORTED
2020-04-17 17:06:31,407 [ERROR] [s.w.s.StoryTellerService]: Failed to plug device
com.lunii.device.wrapper.raw.handler.DeviceHandlerException: com.lunii.device.gateway.DriverException: Cannot get handle for handler, code : LIBUSB_ERROR_NOT_SUPPORTED
        at com.lunii.device.wrapper.raw.handler.RawDeviceHandler.constructException(RawDeviceHandler.java:1458)
        at com.lunii.device.wrapper.raw.handler.RawDeviceHandler.readUUIDFromSPI(RawDeviceHandler.java:936)
        at com.lunii.device.wrapper.raw.handler.RawDeviceHandler.load(RawDeviceHandler.java:59)
        at studio.webui.service.StoryTellerService$1.onPlugged(StoryTellerService.java:58)
        at com.lunii.device.gateway.raw.AbstractUsb4JavaLuniiDriver.fireDevicePlugged(AbstractUsb4JavaLuniiDriver.java:383)
        at com.lunii.device.gateway.raw.AbstractUsb4JavaLuniiDriver$CheckDeviceTimerTask.run(AbstractUsb4JavaLuniiDriver.java:147)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: com.lunii.device.gateway.DriverException: Cannot get handle for handler, code : LIBUSB_ERROR_NOT_SUPPORTED
        at com.lunii.device.gateway.raw.AbstractUsb4JavaLuniiDriver.getDeviceHandle(AbstractUsb4JavaLuniiDriver.java:224)
        at com.lunii.device.gateway.raw.AbstractUsb4JavaLuniiDriver.openDevice(AbstractUsb4JavaLuniiDriver.java:451)
        at com.lunii.device.wrapper.raw.handler.RawDeviceHandler.readUUIDFromSPI(RawDeviceHandler.java:930)
        ... 10 more
2020-04-17 17:07:43,413 [ERROR] [s.w.MainVerticle]: Exception thrown
java.lang.NullPointerException
        at studio.webui.service.StoryTellerService.deviceInfos(StoryTellerService.java:98)
        at studio.webui.api.DeviceController.lambda$apiRouter$2(DeviceController.java:36)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
2020-04-17 17:07:46,056 [WARN ] [i.v.c.i.BlockedThreadChecker]: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2643 ms, time limit is 2000 ms
2020-04-17 17:08:37,836 [ERROR] [s.w.MainVerticle]: Exception thrown
java.lang.IllegalStateException: Response is closed
        at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:575)
        at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:157)
        at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:54)
        at studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:41)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
2020-04-17 17:08:37,838 [ERROR] [i.v.c.i.ContextImpl]: Unhandled exception
java.lang.IllegalStateException: Response is closed
        at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:575)
        at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:323)
        at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:312)
        at io.vertx.ext.web.impl.RoutingContextImplBase.unhandledFailure(RoutingContextImplBase.java:169)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:142)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:134)
        at io.vertx.ext.web.impl.RoutingContextImpl.doFail(RoutingContextImpl.java:483)
        at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:179)
        at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:172)
        at io.vertx.ext.web.impl.RoutingContextWrapper.fail(RoutingContextWrapper.java:73)
        at io.vertx.ext.web.impl.RoutingContextWrapper.fail(RoutingContextWrapper.java:73)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$1(BlockingHandlerDecorator.java:53)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:284)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
2020-04-17 17:08:37,896 [ERROR] [s.w.MainVerticle]: Exception thrown
java.lang.NullPointerException
        at studio.webui.service.StoryTellerService.deviceInfos(StoryTellerService.java:98)
        at studio.webui.api.DeviceController.lambda$apiRouter$2(DeviceController.java:36)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
2020-04-17 17:08:41,199 [ERROR] [i.v.c.i.ContextImpl]: Unhandled exception
java.lang.IllegalStateException: Response is closed
        at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:575)
        at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:157)
        at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:54)
        at studio.webui.api.EvergreenController.lambda$apiRouter$2(EvergreenController.java:42)
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125)
        at studio.webui.service.EvergreenService.lambda$latest$1(EvergreenService.java:60)
        at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:285)
        at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:272)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:250)
        at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
        at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:247)
        at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:257)
        at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:218)
        at io.vertx.ext.web.client.impl.HttpContext.lambda$null$2(HttpContext.java:341)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
2020-04-17 17:08:41,654 [ERROR] [i.v.c.i.ContextImpl]: Unhandled exception
java.lang.IllegalStateException: Response is closed
        at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:575)
        at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:157)
        at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:54)
        at studio.webui.api.WatchdogController.lambda$apiRouter$2(WatchdogController.java:42)
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125)
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86)
        at io.vertx.core.Future.lambda$map$2(Future.java:306)
        at io.vertx.core.impl.CompositeFutureImpl.lambda$all$1(CompositeFutureImpl.java:49)
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125)
        at studio.webui.service.WatchdogService.lambda$latest$2(WatchdogService.java:92)
        at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:285)
        at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:272)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:250)
        at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
        at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:247)
        at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:257)
        at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:218)
        at io.vertx.ext.web.client.impl.HttpContext.lambda$null$2(HttpContext.java:341)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
`

**Desktop and environment (please complete the following information):**
 - OS: Windows 10
 - Browser :chrome, safari
 - Java version: JDK 14
 - STUdio application version : 0.1.13

**Comment by gael4910** [comment]
sorry, just needed to reboot PC...

**Comment by marian-m12l** [comment]
That's strange, it's not the first time I'm seeing libusb errors, but I cannot pinpoint the problem here. Those errors seem to vanish for no reason...
