### ISSUE TITLE
Windows launch: problems with space in directory and SDK

### ISSUE THREAD

**Issue by xberg** [marian-m12l/studio#58]
Hi,
I'm trying to launch this based on the executable in Windows. 
The BATCH files seems to create the directories OK and copy the files OK. But at the end of the batch file I have the following error: 
Erreur : impossible de trouver ou charger la classe principale Documents\studio-web-ui-0.1.13\.studio-web-ui-0.1.13.jar;Q:\Mes

This was caused by the presence of a SPACE in my directory. So I changed your .BAT file to:
java -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -Dfile.encoding=UTF-8 -cp "%STUDIO_PATH%/studio-web-ui-0.1.13.jar";"%STUDIO_PATH%/lib/*";"%DOT_STUDIO%/lib/*";. io.vertx.core.Launcher run studio.webui.MainVerticle

This fixed the above issue but I now have a new error:
2020-04-21 14:20:16,615 [ERROR] [i.v.c.i.l.c.RunCommand]: Failed to deploy verticle studio.webui.MainVerticle
java.lang.UnsupportedClassVersionError: studio/webui/MainVerticle has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:37)
        at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:242)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:215)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:182)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:155)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:144)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:677)
        at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:159)
        at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:403)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:361)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
        at io.vertx.core.Launcher.main(Launcher.java:45)

FYI I'm running Java SE Development Kit 12

Then trying to launch http://localhost:8080/ does not work. 
I have luniistore open.
Am I supposed to do anything else before running the .BAT file?

**Comment by xberg** [comment]
Updated to Java SE Development Kit 14.0.1 and I'm getting the same error. Please note that I'm using your compiled version. 
In the install notes you mention JRE11 but I can't find it so instead am using the SE Development Kit. Perhaps this is wrong?

**Comment by wistof** [comment]
Hi,
Same issue here, 

> 2020-04-21 14:20:16,615 [ERROR] [i.v.c.i.l.c.RunCommand]: Failed to deploy verticle studio.webui.MainVerticle
> java.lang.UnsupportedClassVersionError: studio/webui/MainVerticle has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

- JDK 14 fresh install
- Windows 10

I have notice that the Lunii software had made an update when I  start it. All lunii-*.jar have been updated.

**Comment by wistof** [comment]
Hi,

We run the wrong version of Java. We need to install JAVA JDK 14.
I modify the studio-windows.bat to force the path and it did the trick.

`"C:\Progra~1\Java\jdk-14.0.1\bin\java.exe" -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -Dfile.encoding=UTF-8 -cp %STUDIO_PATH%/studio-web-ui-0.1.14-SNAPSHOT.jar;%STUDIO_PATH%/lib/*;%DOT_STUDIO%/lib/*;. io.vertx.core.Launcher run studio.webui.MainVerticle`

**Comment by marian-m12l** [comment]
@xberg Your last error (UnsupportedClassVersionError) means that you're running Java 8 (supported class version 52.0). You probably have JRE 8's `java` command by default. Your can either fix your path, remove Java 8 or replace the `java` command inside the bat script with the absolute path to your `java.exe`. Any Java version from 11 and up should be OK, but I'm not always testing with the most recent JDKs.
Yes, there are some manual steps that you need to do before running the script, explained in the readme.

**Comment by marian-m12l** [comment]
Keeping the issue open regarding the support for spaces in path.

**Comment by xberg** [comment]
Hi,
Yes: changing the Java path to the JDK 14 worked. Thanks.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
