### ISSUE TITLE
Failed in deploying verticle

### ISSUE THREAD

**Issue by noctanvol** [marian-m12l/studio#66]
**Describe the bug**
Hi since this morning i can no longer lauche Studio

**To Reproduce**
When I lauch "studio-windows.bat"
the windows close after a few second, instead of staying active, it was working perectly fine yesterday

It throw the error bellow
[ERROR] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:77]: Failed in deploying verticle

full logs files
[2020-04-23 14:11:52,622 [ERROR] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:77]: Failed in deploying verticle
java.lang.ClassCastException: class com.google.gson.JsonPrimitive cannot be cast to class com.google.gson.JsonObject (com.google.gson.JsonPrimitive and com.google.gson.JsonObject are in unnamed module of loader 'app')
	at com.google.gson.JsonObject.getAsJsonObject(JsonObject.java:205)
	at studio.metadata.DatabaseMetadataService.lambda$new$0(DatabaseMetadataService.java:38)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:37)
	at studio.webui.MainVerticle.start(MainVerticle.java:48)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
]

**Desktop and environment (please complete the following information):**
 - OS: win 10  (1909)
 - Browser chrome v81
 - Java version: jdk-14.0.1 x64

 - STUdio application version [e.g. 0.1.13]

PS: thx for your fantastic work on this. my daughter love the new story i created for her with your studio

**Comment by marian-m12l** [comment]
Hi, and thanks for the feeback. Glad you could put the app to good use :)
Looks like the `official.json` content is not as expected. Can you check if it looks ok? It's also possible that the file format recently evolved and cannot be read correctly by the application.

**Comment by thekyz** [comment]
I had that issue by not using the right token when downloading the json so probably something in that fashion. In my case the wrong json looked like this:
```
{
  "error" : "Invalid claim 'kid' in auth header: 'd7635ab646e07fd199f74b016a9543922a0cff9a' with iat: '1577304034'"
}
```

**Comment by marian-m12l** [comment]
> I had that issue by not using the right token when downloading the json so probably something in that fashion. In my case the wrong json looked like this:
> 
> ```
> {
>   "error" : "Invalid claim 'kid' in auth header: 'd7635ab646e07fd199f74b016a9543922a0cff9a' with iat: '1577304034'"
> }
> ```

Would make sense and match the error message.

**Comment by noctanvol** [comment]
indeed that fixed it !

thx a lot

I went to %UserProfile%\.studio and I removed or remaned the file official.json
