### ISSUE TITLE
Instllation issue : java version too old despite beeing the latest

### ISSUE THREAD

**Issue by appenzellois** [marian-m12l/studio#77]
**Describe the bug**

Despite installing latest java JDK and JRE and there is an error while lauching the bat from the web ui package telling the version used to compile is to recent.

studio/webui/MainVerticle has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**To Reproduce**
1. Remove all versions of Java
2. Install JDK 14.0.1 and JRE 1.8.0_251
3. Define Windows PATH variable to 'bin' folders and JAVA_HOME
4. Unzip studio web UI distrib to c:\tmp\studio-ui
5. Launch windows-studio.bat

**Expected behavior**
I was excepting the web ui to launch.

**Logs**
2020-04-27 11:53:43,177 [ERROR] [io.vertx.core.impl.launcher.commands.RunCommand] [ClasspathHandler.java:161]: Failed to deploy verticle studio.webui.MainVerticle
java.lang.UnsupportedClassVersionError: studio/webui/MainVerticle has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:37)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:242)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:215)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:182)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:155)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:144)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:677)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:159)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:403)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:361)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
	at io.vertx.core.Launcher.main(Launcher.java:45)

**Desktop and environment (please complete the following information):**
 - OS: Win 10
 - Java version: JDK 14.0.1 + JRE 1.8.0_251
 - Maven version: none
 - STUdio application version 0.1.13

**Additional context**
Jabva versio check from CMD :
C:\tmp\studio-ui>java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

**Comment by appenzellois** [comment]
I did a mvn clean install and the issue is the same with the resulting compilation

**Comment by appenzellois** [comment]
Adding SET PATH="C:\Program Files\Java\jdk-14.0.1\bin" in the first line of the BAT file did solve the issue
