### ISSUE TITLE
Install problem with new java version ?

### ISSUE THREAD

**Issue by Anonymous-style** [marian-m12l/studio#82]
**Describe the bug**
When i execute studio-windows.bat, there is a problem:

2020-04-28 14:34:27,043 [ERROR] [i.v.c.i.l.c.RunCommand]: Failed to deploy verticle studio.webui.MainVerticle
java.lang.UnsupportedClassVersionError: studio/webui/MainVerticle has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:37)
        at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:242)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:215)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:182)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:155)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:144)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:677)
        at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:159)
        at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:403)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
        at .vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:361)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
        at io.vertx.core.Launcher.main(Launcher.java:45).

**Desktop and environment (please complete the following information):**
 - OS: Windows 64-bits
 - Browser: firefox
 - Java version: 
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode)
 - Maven version: ??
 - STUdio application version [0.1.13]

**Comment by marian-m12l** [comment]
Hi,
I think the documentation is confusing to many people and I'll need to fix it somehow, but you shouldn't be running on JRE 8.

**Comment by Anonymous-style** [comment]
Hi, 
thank you for your answer.

JRE is now OK. I have to add in java configure, the path of the correct version of JRE.
And i have to include it in the path.

But now, i have another problem :(

2020-04-29 10:28:59,877 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:45]: Setting up story teller driver
2020-04-29 10:28:59,890 [INFO ] [com.lunii.device.gateway.raw.AbstractUsb4JavaLuniiDriver] [AbstractUsb4JavaLuniiDriver.java:155]: Initializing libusb...
2020-04-29 10:28:59,936 [INFO ] [com.lunii.device.gateway.raw.AbstractUsb4JavaLuniiDriver] [AbstractUsb4JavaLuniiDriver.java:164]: libusb initialized
2020-04-29 10:29:00,250 [INFO ] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:81]: Succeeded in deploying verticle
2020-04-29 10:29:20,085 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:100]: Exception thrown
java.nio.channels.ClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
2020-04-29 10:29:25,531 [WARN ] [io.netty.resolver.dns.DnsNameResolver] [DnsNameResolver.java:863]: Failed to notify success ([api.github.com/140.82.118.5]) to a promise: DefaultPromise@5fb63eb2(success: [api.github.com/140.82.118.5])
2020-04-29 10:29:26,088 [WARN ] [io.netty.resolver.dns.DnsNameResolver] [DnsNameResolver.java:1123]: [id: 0x7ed50f7c, L:/[0:0:0:0:0:0:0:0]:57859] Received a DNS response with an unknown ID: 55258


Thank you for your work.

**Comment by marian-m12l** [comment]
Hi,
The app should be working anyway.
I'll need to investigate what causes DNS resolution issues, might be coming from vert.x / netty configuration. However your error simply means the app fails to get the latest version available on github (to notify if you are up-to-date), but the rest should still work.

**Comment by Anonymous-style** [comment]
Hi,
the app is working but there is no story in my library :/.
The official.json is 487ko, is that ok ?

thank you for your help (and sorry for my noobiness)

**Comment by marian-m12l** [comment]
Hi,
Your local library is supposed to be empty, indeed, until you create some story packs.
When you plug your device, another panel should appear on the left side of the library, showing the packs that are currently on the device. If your `official.json` is correct, you'll see the cover artwork and pack name, otherwise you'll just see a generic image and the uuid (unique identifier) of the packs. A few hundred KB sounds alright, but what matters is (obviously) the actual content.

**Comment by marian-m12l** [comment]
Leaving this issue open as the message shown when local library is empty could be better.

**Comment by Anonymous-style** [comment]
Ah sorry, i have plugged my lunii but it wasn't recognized by the luniistore and neither it was recognized by your software.
i thank that i could have been able to download the stories of my account without connecting my lunii.

Then i will wait until the after sale service reopening.

Thank you for your work again.

**Comment by marian-m12l** [comment]
This application does not have access to your Luniistore account, the only data linked to the store are the pack metadata that you retrieve during installation.

**Comment by krissprolls** [comment]
Hi, I have the same issue with the newer jav version, where can i change the path ? Thanks in advance !

**Comment by krissprolls** [comment]
Ok with SET PATH=C:\Program Files\Java\jdk-14.0.1\bin at the first row of .bat file ! ;-)
