### ISSUE TITLE
"Failed to check device"

### ISSUE THREAD

**Issue by bobbywax2** [marian-m12l/studio#91]
**Describe the bug**
When I go to http://localhost:8080/ with the lunii aready connected and started, I don't this it on the localhost interface andI have this message in red box "Failed to check device"

By the way, I installed JAVA and JDK and I had some issues to start the program. I had to change the studios-windows.bat with this at the last line :
"C:\Program Files\Java\jdk-14.0.1\bin\java.exe"

But I don't think it is linked with my problem

**To Reproduce**
1. Go to http://localhost:8080/
2. See error

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> Internal Server Error: Error 500: Internal Server Error	at studio.webui.service.StoryTellerService.deviceInfos(StoryTellerService.java:98)
	at studio.webui.api.DeviceController.lambda$apiRouter$2(DeviceController.java:36)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.1.14

**Additional context**
I'm installing Eclipse to loock at the code, maybe I will have a clue :)
Thanks anyway the project is exciting and maybe I will be able to create more russian story (for now the official bibliotheque is way to small in russian)

**Comment by bobbywax2** [comment]
Ok, so sorry, I restart everything and it's now OK, I read the #40 issue, and I think it was something like there : not properly closed. Luniistore has to be closed before launch STUdio
