### ISSUE TITLE
Workers timeout exception while reading my unofficial stories

### ISSUE THREAD

**Issue by DevUzer** [marian-m12l/studio#95]
**Describe the bug**
Exception while reading the unofficial stories

2020-05-12 08:33:01,438 [WARN ] [i.v.c.i.BlockedThreadChecker]: Thread Thread[vert.x-worker-thread-9,5,main] has been blocked for 264976 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.7/java.util.zip.Inflater.inflateBytesBytes(Native Method)
	at java.base@11.0.7/java.util.zip.Inflater.inflate(Inflater.java:385)
	at java.base@11.0.7/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:153)
	at java.base@11.0.7/java.util.zip.ZipInputStream.read(ZipInputStream.java:195)
	at java.base@11.0.7/java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:141)
	at java.base@11.0.7/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:119)
	at app//studio.core.v1.reader.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:37)
	at app//studio.webui.service.LibraryService.readPackFile(LibraryService.java:244)
	at app//studio.webui.service.LibraryService.lambda$packs$7(LibraryService.java:98)
	at app//studio.webui.service.LibraryService$$Lambda$304/0x0000000800403440.apply(Unknown Source)
	at java.base@11.0.7/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base@11.0.7/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base@11.0.7/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base@11.0.7/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base@11.0.7/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base@11.0.7/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base@11.0.7/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base@11.0.7/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base@11.0.7/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@11.0.7/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at app//studio.webui.service.LibraryService.packs(LibraryService.java:103)
	at app//studio.webui.api.LibraryController.lambda$apiRouter$1(LibraryController.java:39)
	at app//studio.webui.api.LibraryController$$Lambda$177/0x0000000800314840.handle(Unknown Source)
	at app//io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at app//io.vertx.ext.web.impl.BlockingHandlerDecorator$$Lambda$251/0x00000008003e1440.handle(Unknown Source)
	at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$208/0x0000000800358c40.run(Unknown Source)
	at app//io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at app//io.vertx.core.impl.TaskQueue$$Lambda$110/0x0000000800253040.run(Unknown Source)
	at java.base@11.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.7/java.lang.Thread.run(Thread.java:834)

**To Reproduce**
1. Launch the server with heavy .ZIP stories
2. See error

**Expected behavior**
Increase the timeout

**Screenshots**
Cf. description.

**Logs**
Cf. description.

**Desktop and environment (please complete the following information):**
 - OS: MACOSX
 - Browser CHROME
 - Java version: openjdk version "11.0.7" 2020-04-14
 - Maven version: N.A
 - STUdio application version 0.1.14

**Additional context**
None

**Comment by marian-m12l** [comment]
Hi,
Thanks for the feedback. It's strange that it takes so long to read the metadata.. How many packs and how big a pack are we talking about?

**Comment by DevUzer** [comment]
My biggest ZIP packs are around 250MB but actually I do not know if they are the faulty ones. 
I have created almost 40 private story packs with mp3 which I have ripped from CDs my kid receives every month by subscription.

**Comment by marian-m12l** [comment]
I'll need to take a better look. Only metadata should be read, which shouldn't be that costly..

**Comment by DevUzer** [comment]
It occurs in v0.2beta also

**Comment by JacquesSchreiber** [comment]
**Describe the bug**
same behaviour observed as explained by DevUzer. It takes up to two minute only to display 38 stories (in ZIP-format between 3Mo and 1.6Go)

**Desktop** and environment (please complete the following information):
    OS: Ubuntu 20.04
    Browser Firefox
    Java version: openjdk version 11
    Maven version: N.A
    STUdio application version 0.3.0

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
